{
  "hash": "1086e875d50bc849848c3ad82a857193",
  "result": {
    "markdown": "---\ntitle: \"Coding workshop: Week 4\"\ndescription: \"t-tests\"\nfreeze: auto\nauthor:\n  - name: An Bui\n    url: https://an-bui.com/\n    affiliation: UC Santa Barbara, Ecology, Evolution, and Marine Biology\n    affiliation-url: https://www.eemb.ucsb.edu/\ndate: 2023-04-26\ncategories: [tidyverse, lterdatasampler, t-test]\ncitation:\n  url: https://an-bui.github.io/ES-193DS-W23/workshop/workshop-04_2023-04-26.html\n---\n\n\n# 0. set up\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lterdatasampler)\n```\n:::\n\n\n# 1. Data\n\nWhat is the first step to working with data?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(hbr_maples)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntibble [359 × 11] (S3: tbl_df/tbl/data.frame)\n $ year               : num [1:359] 2003 2003 2003 2003 2003 ...\n $ watershed          : Factor w/ 2 levels \"Reference\",\"W1\": 1 1 1 1 1 1 1 1 1 1 ...\n $ elevation          : Factor w/ 2 levels \"Low\",\"Mid\": 1 1 1 1 1 1 1 1 1 1 ...\n $ transect           : Factor w/ 12 levels \"R1\",\"R2\",\"R3\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ sample             : Factor w/ 20 levels \"1\",\"2\",\"3\",\"4\",..: 1 2 3 4 5 6 7 8 9 10 ...\n $ stem_length        : num [1:359] 86.9 114 83.5 68.1 72.1 77.7 85.5 81.6 92.9 59.6 ...\n $ leaf1area          : num [1:359] 13.84 14.57 12.45 9.97 6.84 ...\n $ leaf2area          : num [1:359] 12.13 15.27 9.73 10.07 5.48 ...\n $ leaf_dry_mass      : num [1:359] 0.0453 0.0476 0.0423 0.0397 0.0204 0.0317 0.0382 0.0179 0.0286 0.0125 ...\n $ stem_dry_mass      : num [1:359] 0.03 0.0338 0.0248 0.0194 0.018 0.0246 0.0316 0.015 0.0291 0.0149 ...\n $ corrected_leaf_area: num [1:359] 29.1 33 25.3 23.2 15.5 ...\n```\n:::\n\n```{.r .cell-code}\n# use View(hbr_maples) in the console to see the data frame\n```\n:::\n\n\nAre there any missing observations?  \n\nUse `install.packages(\"naniar\")` in the console before running the chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(naniar)\n\ngg_miss_var(hbr_maples)\n```\n\n::: {.cell-output-display}\n![](workshop-04_2023-04-26_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n# 2. Do sugar maple stem lengths differ between reference and calcium-treated watersheds in 2003?\n\n## a. initial wrangling\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmaples_2003 <- hbr_maples %>% \n  filter(year == 2003) %>% \n  mutate(watershed = case_when(\n    watershed == \"Reference\" ~ \"Reference\", \n    watershed == \"W1\" ~ \"Calcium-treated\"\n  ))\n\nhead(maples_2003, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 11\n   year watershed eleva…¹ trans…² sample stem_…³ leaf1…⁴ leaf2…⁵ leaf_…⁶ stem_…⁷\n  <dbl> <chr>     <fct>   <fct>   <fct>    <dbl>   <dbl>   <dbl>   <dbl>   <dbl>\n1  2003 Reference Low     R1      1         86.9   13.8    12.1   0.0453  0.03  \n2  2003 Reference Low     R1      2        114     14.6    15.3   0.0476  0.0338\n3  2003 Reference Low     R1      3         83.5   12.5     9.73  0.0423  0.0248\n4  2003 Reference Low     R1      4         68.1    9.97   10.1   0.0397  0.0194\n5  2003 Reference Low     R1      5         72.1    6.84    5.48  0.0204  0.018 \n# … with 1 more variable: corrected_leaf_area <dbl>, and abbreviated variable\n#   names ¹​elevation, ²​transect, ³​stem_length, ⁴​leaf1area, ⁵​leaf2area,\n#   ⁶​leaf_dry_mass, ⁷​stem_dry_mass\n```\n:::\n:::\n\n\n## b. summary statistics\n\nRemember, we're interested in **stem lengths** in **2003** between **reference** and **calcium-treated** watersheds. What groups would be useful if that was the case?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlengths_2003_summary <- maples_2003 %>% \n  group_by(watershed) %>% \n  summarize(mean_l = mean(stem_length),\n            sd_l = sd(stem_length),\n            var_l = var(stem_length),\n            count_l = length(stem_length),\n            se_l = sd_l/sqrt(count_l),\n            margin_l = qt(0.95, df = count_l - 1) * se_l) \n\nlengths_2003_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 7\n  watershed       mean_l  sd_l var_l count_l  se_l margin_l\n  <chr>            <dbl> <dbl> <dbl>   <int> <dbl>    <dbl>\n1 Calcium-treated   87.9  14.3  206.     120  1.31     2.17\n2 Reference         81.0  13.9  194.     120  1.27     2.11\n```\n:::\n\n```{.r .cell-code}\n# not getting the digits after the decimal point that you're expecting?\n# try `as.data.frame()` piped in after the summarize call.\n```\n:::\n\n\n## c. check for normally distributed data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = maples_2003) +\n  stat_qq(aes(sample = stem_length)) +\n  stat_qq_line(aes(sample = stem_length), color = \"red\") +\n  facet_wrap(~ watershed)\n```\n\n::: {.cell-output-display}\n![](workshop-04_2023-04-26_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n## c. Check for equal variances\n\nWith an F-test, you can ask: are the sample variances between my two groups equal?  \nThe assumption is that your data are normally distributed.\n\n$$\nH0: s^2_1 = s^2_2\nH1: s^2_1 \\neq s^2_2\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength_var <- var.test(stem_length ~ watershed, data = maples_2003)\n\nlength_var\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tF test to compare two variances\n\ndata:  stem_length by watershed\nF = 1.0587, num df = 119, denom df = 119, p-value = 0.7563\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.7378244 1.5190473\nsample estimates:\nratio of variances \n          1.058674 \n```\n:::\n:::\n\n\n## c. decide on a critical value\n\nTwo-tailed with significance level $\\alpha$ = 0.05:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(p = .05/2, df = 119)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -1.9801\n```\n:::\n:::\n\n\nIf your test statistic is less than -1.98 or greater than 1.98, then you have evidence to reject the null hypothesis.\n\n## d. Do a t-test \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength_ttest <- t.test(stem_length ~ watershed, data = maples_2003, var.equal = TRUE)\n\nlength_ttest\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  stem_length by watershed\nt = 3.7797, df = 238, p-value = 0.0001985\nalternative hypothesis: true difference in means between group Calcium-treated and group Reference is not equal to 0\n95 percent confidence interval:\n  3.304134 10.497532\nsample estimates:\nmean in group Calcium-treated       mean in group Reference \n                     87.88583                      80.98500 \n```\n:::\n:::\n\n\n## e. Calculate Cohen's d effect size\n\n**Cohen's d** is a measure of how many standard deviations apart the two sample means are. \n\n$$\nCohen's d = \\frac{\\bar{x_1} - \\bar{x_2}}{\\sqrt{(s^2_1 + s^2_2)/2}}\n$$\n\nNote that you are using sample means in the numerator and sample variances in the denominator.  \n\nWe can calculate this by hand (use `install.packages(\"data.table\")` in the console before running the chunk below):  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(data.table)\n\n# create a data frame in data table format from lengths_2003_summary\nlengths_dt <- setDT(lengths_2003_summary)\n\n# pull out mean and variance values from the data table \nmean_ref_2003 <- lengths_dt[watershed == \"Reference\", mean_l]\nmean_w1_2003 <- lengths_dt[watershed == \"Calcium-treated\", mean_l]\nvar_ref_2003 <- lengths_dt[watershed == \"Reference\", var_l]\nvar_w1_2003 <- lengths_dt[watershed == \"Calcium-treated\", var_l]\n\n# calculate Cohen's d\nd_byhand <- (mean_w1_2003 - mean_ref_2003) / sqrt((var_w1_2003 + var_ref_2003)/2)\nd_byhand\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4879597\n```\n:::\n:::\n\n\nOr using a function in a package:  \n\nUse `install.packages(\"effsize\")` in the console before running the chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(effsize)\n\nd_effsize <- cohen.d(stem_length ~ watershed, data = maples_2003)\n```\n:::\n\n\nCompare the two calculations:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd_byhand\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4879597\n```\n:::\n\n```{.r .cell-code}\nd_effsize\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCohen's d\n\nd estimate: 0.4879597 (small)\n95 percent confidence interval:\n    lower     upper \n0.2298792 0.7460402 \n```\n:::\n:::\n\n\n## make a plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lengths_2003_summary, aes(x = watershed, y = mean_l, color = watershed)) +\n  geom_point(size = 3) +\n  geom_linerange(aes(ymin = mean_l - margin_l, ymax = mean_l + margin_l), linewidth = 1) +\n  geom_jitter(data = maples_2003, aes(x = watershed, y = stem_length), alpha = 0.3) +\n  scale_color_manual(values = c(\"Reference\" = \"#E57B33\", \"Calcium-treated\" = \"#039199\")) +\n  labs(x = \"Watershed\", y = \"Stem length (mm)\") +\n  theme_classic() +\n  theme(legend.position = \"none\",\n        text = element_text(family = \"Times New Roman\"),\n        axis.title = element_text(size = 14),\n        axis.text = element_text(size = 12),\n        plot.caption = element_text(hjust = 0),\n        plot.caption.position = \"plot\",\n        plot.title.position = \"plot\")\n```\n\n::: {.cell-output-display}\n![](workshop-04_2023-04-26_files/figure-html/unnamed-chunk-13-1.png){width=768}\n:::\n:::\n\n\n## f. Communicating about the results of a t-test\n\n### figure caption\n\n**Figure 1. Sugar maple stem lengths in calcium-treated and reference watersheds.** Stem lengths (mm) for calcium-treated (turquoise) and reference (orange) watersheds from Hubbard Brook Long-term Ecological Research site (HBR LTER). Dark points represent mean stem length and vertical lines represent confidence intervals with a 95% confidence level. Transparent points represent stem lengths.\n\n### in-text references\n\nThere is a moderate (Cohen's d = 0.49) but significant effect of calcium treatment on sugar maple stem lengths (Student's t-test, t(238) = 3.78, _p_ < 0.001, $\\alpha$ = 0.05). On average, sugar maple stem lengths in calcium-treated watersheds were 6.9 mm longer than those in reference watersheds (95% confidence interval: [3.3, 10.5] mm, Figure 1). \n\n### bonus in-text references, using in-line R\n\n**When rendering your document, compare the text above with the text below. Are there any differences?**  \n\nThere is a moderate (Cohen's d = 0.49) but significant effect of calcium treatment on sugar maple stem lengths (Student's t-test, t(238) = 3.8, _p_ < 0.001, $\\alpha$ = 0.05). On average, sugar maple stem lengths in calcium-treated watersheds were 6.9 mm longer than those in reference watersheds (CI = [3.3, 10.5] mm, Figure 1). \n",
    "supporting": [
      "workshop-04_2023-04-26_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}