{
  "hash": "30024aa1c6cca63d72bf01c6d3e1be6d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 5 figures - Lectures 9 and 10\"\neditor: source\nfreeze: auto\nexecute:\n  message: false\n  warning: false\nformat:\n  html: \n    code-fold: true\nauthor:\n  - name: An Bui\n    url: https://an-bui.com/\n    affiliation: UC Santa Barbara, Ecology, Evolution, and Marine Biology\n    affiliation-url: https://www.eemb.ucsb.edu/\npublished-title: \"Lecture date\"\ndate: 2024-04-29\ndate-modified: last-modified\ncategories: [analysis of variance, eta squared, shapiro-wilk, levene, mann-whitney U, wilcoxon signed-rank, kruskal-wallis, cliffs delta]\ncitation:\n  url: https://spring-2024.envs-193ds.com/lecture/lecture_week-05.html\n---\n\n\n## 0. Set up\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# cleaning\nlibrary(tidyverse)\n\n# visualization\ntheme_set(theme_classic() +\n            theme(panel.grid = element_blank(),\n                  axis.text = element_text(size = 18),\n                  axis.title = element_text(size = 18),\n                  text = element_text(family = \"Lato\")))\nlibrary(patchwork)\n\n# data\nlibrary(palmerpenguins)\n\n# analysis\nlibrary(car)\nlibrary(effectsize)\n```\n:::\n\n\n## 1. Math\n\n### a. sum of squares\n\nAmong groups:\n\n$$\n\\sum^k_{i = 1}\\sum^n_{j = 1}(\\bar{y_i} - \\bar{y})^2\n$$\n\nwhere k is the number of groups, i is ith group, n is the number of observations per group, j is the jth observation. $\\bar{y_i}$ is the mean of group i, while $\\bar{y}$ is the grand mean (of all samples pooled together).  \n\nWithin groups:\n\n$$\n\\sum^k_{i = 1}\\sum^n_{j = 1}(y_{ij} - \\bar{y_i})^2\n$$\n\nwhere $y_{ij}$ is the jth observation in the ith group, and $\\bar{y_i}$ is the mean of group i.  \n\nTotal sum of squares:  \n\n$$\n\\sum^k_{i = 1}\\sum^n_{j = 1}(y_{ij} - \\bar{y})^2\n$$\n\nwhere $y_{ij}$ is the jth observation in the ith group, and $\\bar{y}$ is the grand mean.\n\n### b. mean squares\n\nAmong groups:\n\n$$\n\\frac{SS_{among \\ group}}{k - 1}\n$$\n\nWithin groups:  \n\n$$\n\\frac{SS_{within \\ group}}{n - k}\n$$\n\n### c. F-ratio/F-statistic\n\n$$\n\\frac{MS_{among \\ group}}{MS_{within \\ group}}\n$$\n\nPut another way, the F-ratio is the ratio of among group variance to within group variance. If the among group variance is larger than within group variance, the F-ratio is large, and therefore the probability of among group variance being equal to within group variance is small. Thus, you would reject the null hypothesis if the F-ratio is large.\n\n### d. η squared\n\n$$\n\\eta^2 = \\frac{SS_{among \\ group}}{SS_{among \\ group} + SS_{within \\ group}}\n$$\n### e. U statistic\n$$\n\\begin{align}\nU_1 &= \\Sigma R_1 - n_1(n_1 + 1)/2 = 17 - 5(5+1)/2 = 2 \\\\\nU_2 &= \\Sigma R_2 - n_2(n_2 + 1)/2 = 38 - 5(5+1)/2 = 23\n\\end{align}\n$$\n\n## 2. Warm up: code for a figure\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# random sample of 10 rows from data frame\nsample_n(chickwts, 10) %>% \n  arrange(feed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   weight      feed\n1     318    casein\n2     217 horsebean\n3     140 horsebean\n4     141   linseed\n5     257   linseed\n6     206  meatmeal\n7     316   soybean\n8     327   soybean\n9     318 sunflower\n10    339 sunflower\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data = chickwts,           # data frame: chickwts\n       aes(x = feed,              # x-axis: feed type\n           y = weight,            # y-axis: chick weight\n           fill = feed)) +        # fill by feed type  \n  geom_boxplot() +                # creates a boxplot\n  geom_jitter(height = 0,         # prevents jitter from moving points along y-axis\n              width = 0.2) +      # narrows spread of jitter along x-axis\n  theme(legend.position = \"none\") # removes legend\n```\n\n::: {.cell-output-display}\n![](lecture_week-05_files/figure-html/chickwts-figure-1.png){width=1152}\n:::\n:::\n\n\n\n## 3. Analysis of variance\n\nCentral question: How does bill length differ between penguin species?\n\n### a. Exploratory data visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_jitter <- ggplot(data = penguins,\n                          aes(x = species,\n                              y = bill_length_mm,\n                              color = species)) +\n  geom_jitter(width = 0.2,\n              height = 0,\n              shape = 21) +\n  scale_color_manual(values = c(\"#209c90\", \"#018ca9\", \"#27c839\")) +\n  labs(x = \"Species\",\n       y = \"Bill length (mm)\") +\n  theme(legend.position = \"none\")\n\npenguins_jitter\n```\n\n::: {.cell-output-display}\n![](lecture_week-05_files/figure-html/penguins-explore-1.png){width=672}\n:::\n:::\n\n\n### b. histogram and qq plots\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist <- ggplot(data = penguins,\n       aes(x = bill_length_mm,\n           fill = species)) +\n  geom_histogram(bins = 14,\n                 color = \"black\") +\n  scale_fill_manual(values = c(\"#209c90\", \"#018ca9\", \"#27c839\")) +\n  scale_y_continuous(expand = c(0, 0)) +\n  facet_wrap(~ species, scales = \"free\", ncol = 1) +\n  labs(x = \"Bill length (mm)\",\n       y = \"Count\") +\n  theme(legend.position = \"none\",\n        strip.background = element_rect(color = \"white\"),\n        strip.text = element_text(size = 20))\n\nqq <- ggplot(data = penguins,\n       aes(sample = bill_length_mm)) +\n  geom_qq_line() +\n  geom_qq(aes(color = species)) +\n  scale_color_manual(values = c(\"#209c90\", \"#018ca9\", \"#27c839\")) +\n  facet_wrap(~ species, scales = \"free\", ncol = 1) +\n  labs(x = \"Theoretical quantile\",\n       y = \"Value\") +\n  theme(legend.position = \"none\",\n        strip.background = element_rect(color = \"white\"),\n        strip.text = element_text(size = 20))\n\nhist + qq\n```\n\n::: {.cell-output-display}\n![](lecture_week-05_files/figure-html/penguins-hist-and-qq-1.png){width=1152}\n:::\n:::\n\n\n### c. Shapiro-Wilk normality test\n\nGeneral: Is the response variable normally distributed?  \nExample: Is bill length normally distributed?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# first, wrangle\nadelie <- penguins %>% \n  filter(species == \"Adelie\") %>% \n  pull(bill_length_mm)\n\nchinstrap <- penguins %>% \n  filter(species == \"Chinstrap\") %>% \n  pull(bill_length_mm)\n\ngentoo <- penguins %>% \n  filter(species == \"Gentoo\") %>% \n  pull(bill_length_mm)\n\n# then, do the shapiro-wilk test\nshapiro.test(adelie)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  adelie\nW = 0.99336, p-value = 0.7166\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(chinstrap)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  chinstrap\nW = 0.97525, p-value = 0.1941\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(gentoo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  gentoo\nW = 0.97272, p-value = 0.01349\n```\n\n\n:::\n:::\n\n\n### d. Levene test of variances\n\nGeneral: Are the group variances equal?  \nExample: Are the species variances equal?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleveneTest(bill_length_mm ~ species,\n           data = penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   2  2.2425 0.1078\n      339               \n```\n\n\n:::\n:::\n\n\n### e. analysis of variance\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# do the actual test\n# model object stored as `penguins_anova`\npenguins_anova <- aov(bill_length_mm ~ species,\n                      data = penguins)\n\n# output of the test\npenguins_anova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\n   aov(formula = bill_length_mm ~ species, data = penguins)\n\nTerms:\n                 species Residuals\nSum of Squares  7194.317  2969.888\nDeg. of Freedom        2       339\n\nResidual standard error: 2.959853\nEstimated effects may be unbalanced\n2 observations deleted due to missingness\n```\n\n\n:::\n\n```{.r .cell-code}\n# more information\nsummary(penguins_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \nspecies       2   7194    3597   410.6 <2e-16 ***\nResiduals   339   2970       9                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n2 observations deleted due to missingness\n```\n\n\n:::\n:::\n\n\n### f. post hoc test\n\nWhich group comparisons are different?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(penguins_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = bill_length_mm ~ species, data = penguins)\n\n$species\n                      diff       lwr        upr     p adj\nChinstrap-Adelie 10.042433  9.024859 11.0600064 0.0000000\nGentoo-Adelie     8.713487  7.867194  9.5597807 0.0000000\nGentoo-Chinstrap -1.328945 -2.381868 -0.2760231 0.0088993\n```\n\n\n:::\n:::\n\n\n### g. effect size\n\n\n::: {.cell}\n\n```{.r .cell-code}\neta_squared(penguins_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA\n\nParameter | Eta2 |       95% CI\n-------------------------------\nspecies   | 0.71 | [0.67, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n### h. example of writing\n\nWithout the stats: Our results suggest a difference in bill length between species, with a large effect of species. Species differed in bill length, and pairwise comparisons between species showed that all three species differed from each other. Generally, Adelie penguins tend to have shorter bills than Chinstrap and Gentoo penguins. Gentoo penguins tend to have shorter bills than  Chinstrap penguins.\n\nWith the stats: Our results suggest a difference in bill length between species, with a large ($\\eta^2$ = 0.71) effect of species. Species differed in bill length (one-way ANOVA, F(2, 339) = 410.6, p < 0.001, $\\alpha$ = 0.05), and pairwise comparisons between species showed that all three species differed from each other. Generally, Adelie penguins tend to have 10.0 mm shorter bills than Chinstrap (Tukey HSD, p < 0.001, 95% confidence interval: [9.0, 11.1] mm) penguins and 8.7 mm shorter than Gentoo (Tukey HSD, p < 0.001, 95% confidence interval: [7.9, 9.6] mm) penguins. Gentoo penguins tend to have 1.3 mm shorter bills than Chinstrap penguins (Tukey HSD, p = 0.008, 95% confidence interval: [0.3, 2.4] mm).  \n\n### i. a \"finalized\" figure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = penguins,\n       aes(x = species,\n           y = bill_length_mm,\n           color = species)) +\n  geom_jitter(width = 0.2,\n              height = 0,\n              shape = 21,\n              alpha = 0.4) +\n  stat_summary(geom = \"pointrange\",\n               fun.data = mean_cl_normal,\n               size = 0.8,\n               linewidth = 1) +\n  scale_color_manual(values = c(\"#209c90\", \"#018ca9\", \"#27c839\")) +\n  labs(x = \"Species\",\n       y = \"Bill length (mm)\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](lecture_week-05_files/figure-html/penguins-final-fig-1.png){width=672}\n:::\n:::\n\n\n## 4. Non parametric tests\n\n### a. Mann-Whitney U\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox_df <- cbind(Sample1 = c(1.1, 2.4, 1.8, 0.4, 1.6), \n                   Sample2 = c(5.4, 3.1, 2.3, 1.9, 4.2)) %>% \n  as_tibble() %>% \n  pivot_longer(cols = Sample1:Sample2) %>% \n  rename(sample = name) %>% \n  arrange(sample)\n\nwilcox_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 2\n   sample  value\n   <chr>   <dbl>\n 1 Sample1   1.1\n 2 Sample1   2.4\n 3 Sample1   1.8\n 4 Sample1   0.4\n 5 Sample1   1.6\n 6 Sample2   5.4\n 7 Sample2   3.1\n 8 Sample2   2.3\n 9 Sample2   1.9\n10 Sample2   4.2\n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox.test(value ~ sample,\n            data = wilcox_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  value by sample\nW = 2, p-value = 0.03175\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n### b. Wilcoxon signed-rank\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# for a comparison of one group against a theoretical median\nwilcox.test(Sample1, mu = theoretical)\n\n# for a comparison of two groups\nwilcox.test(value ~ sample,\n            data = wilcox_df, \n            paired = TRUE)\n```\n:::\n\n\n### c. Kruskal-Wallis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal_df <- cbind(Sample1 = round(rnorm(n = 5, mean = 4, sd = 1), 1), \n                    Sample2 = round(rnorm(n = 5, mean = 6, sd = 1), 1),\n                    Sample3 = round(rnorm(n = 5, mean = 8, sd = 1), 1)) %>% \n  as_tibble() %>% \n  pivot_longer(cols = Sample1:Sample3) %>% \n  rename(sample = name) %>% \n  arrange(sample)\n\nrank_by_hand <- kruskal_df %>% \n  arrange(value) %>% \n  rownames_to_column(\"ranks\") %>% \n  mutate(ranks = as.numeric(ranks)) %>% \n  group_by(sample) %>% \n  reframe(sum_ranks = sum(ranks))\n\nR1 <- rank_by_hand[1, 2]\nR2 <- rank_by_hand[2, 2]\nR3 <- rank_by_hand[3, 2]\nn <- 15\nn1 <- 5\nn2 <- 5\nn3 <- 5\n\nrstatix::kruskal_test(value ~ sample,\n             data = kruskal_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  .y.       n statistic    df      p method        \n* <chr> <int>     <dbl> <int>  <dbl> <chr>         \n1 value    15      12.1     2 0.0024 Kruskal-Wallis\n```\n\n\n:::\n\n```{.r .cell-code}\nkruskal.test(value ~ sample,\n             data = kruskal_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  value by sample\nKruskal-Wallis chi-squared = 12.063, df = 2, p-value = 0.002402\n```\n\n\n:::\n\n```{.r .cell-code}\n#((12 * STATISTIC / (n * (n + 1)) - 3 * (n + 1)) / (1 - sum(TIES^3 - TIES) / (n^3 - n)))\n\n(12/(n*(n+1)))*((R1^2)/n1 + (R2^2)/n2 + (R3^2)/n3) - 3*(n + 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sum_ranks\n1     12.02\n```\n\n\n:::\n\n```{.r .cell-code}\nrstatix::kruskal_effsize(value ~ sample,\n                         data = kruskal_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  .y.       n effsize method  magnitude\n* <chr> <int>   <dbl> <chr>   <ord>    \n1 value    15   0.839 eta2[H] large    \n```\n\n\n:::\n\n```{.r .cell-code}\nrstatix::dunn_test(value ~ sample,\n                         data = kruskal_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  .y.   group1  group2     n1    n2 statistic        p   p.adj p.adj.signif\n* <chr> <chr>   <chr>   <int> <int>     <dbl>    <dbl>   <dbl> <chr>       \n1 value Sample1 Sample2     5     5      1.84 0.0655   0.131   ns          \n2 value Sample1 Sample3     5     5      3.47 0.000518 0.00156 **          \n3 value Sample2 Sample3     5     5      1.63 0.103    0.131   ns          \n```\n\n\n:::\n:::\n",
    "supporting": [
      "lecture_week-05_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}