project:
  type: website
  output-dir: docs

website:
  title: "Statistics for Environmental Studies"
  favicon: images/icons8-graph.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    code-fold: true



