project:
  type: website
  output-dir: docs

website:
  title: "ENVS 193DS - 2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: workshop.qmd
        text: Workshops
      - href: lecture.qmd
        text: Lecture figures
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



