project:
  type: website
  output-dir: docs

website:
  title: "Spring 2024"
  favicon: images/icons8-graph.png
  navbar:
    left:
      - href: https://docs.google.com/document/d/19ljdUvLlH-8yNGZ6Uw1rrkBe8FlSLNCRfIIwTtHjCUg/edit?usp=sharing
        text: Syllabus
      - href: assignments.qmd
        text: Assignments
      - href: workshop.qmd
        text: Workshops
      - href: lecture.qmd
        text: Lecture figures
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: 
    - minty
    - custom.scss
    mainfont: Lato
    toc: true
    toc-location: left
    code-tools: true



