project:
  type: website
  output-dir: docs

website:
  title: "ENVS 193DS - UCSB"
  favicon: images/icons8-graph.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    code-fold: true



