{
  "hash": "7bcda2993b4c877815645225ce1bfe88",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Coding workshop: Week 3\"\nsubtitle: \"basic t-tests and their assumptions\"\ndate: 2026-04-17\ncategories: [tidyverse, lterdatasampler, data, geom_qq, geom_qq_line, facet_wrap, var.test, t.test, rownames_to_column, geom_pointrange, pipe operators, '|>', mutate, case_when, gglpot, geom_boxplot, geom_jitter, geom_histogram, group_by, ungroup, summarize]\n---\n\n\n[Workshop date: Friday 17 April]{style=\"color: #79ACBD; font-size: 24px;\"}\n\n## 1. Summary\n\n### Packages\n\n- `tidyverse`\n- `lterdatasampler`\n\n### Operations\n\n#### New functions\n\n- display data from package using `data()`\n- visualize QQ plots using `geom_qq()` and `geom_qq_line()`\n- create multi-panel plots using `facet_wrap()`\n- compare group variances using `var.test()`\n- do t-tests using `t.test()`\n- make rownames into a separate column using `rownames_to_column()`\n- use `geom_pointrange()` to show means and 95% CI\n\n#### Review\n\n- chain functions together using ` |> `\n- filtering observations using `filter()`\n- manipulate columns using `mutate()` and `case_when()`\n- visualize data using `ggplot()`\n- create boxplots using `geom_boxplot()` and show observation values using `geom_jitter()`\n- create histograms using `geom_histogram()`\n- group data using `group_by()`\n- undo grouping using `ungroup()`\n- summarize data using `summarize()`\n\n### General Quarto formatting tips\n\nYou can control the appearance of text, links, images, etc. using this [guide](https://quarto.org/docs/authoring/markdown-basics.html).\n\n### Data source\n\nThe data on sugar maples is from the `lterdatasampler` package. The package developers (alumni of the Bren Masters of Environmental Data Science program!) curated a bunch of datasets from the LTER network into this package for teaching and learning. Read about the package [here](https://lter.github.io/lterdatasampler/index.html).  \n\nThe source of the data is Hubbard Brook Experimental Forest. Read more about the data [here](https://lter.github.io/lterdatasampler/articles/hbr_maples_vignette.html).\n\n## 2. Code\n\n**Remember to set up an Rproject before starting!**\n\n### 1. Set up\n\nInsert a code chunk below to read in your packages. Name the code chunk `packages`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lterdatasampler)\n```\n:::\n\n\nBecause we are using data from the package `lterdatasampler`, we don't need to use `read_csv()`.  \n\nInstead, we can use `data()` to make the data frame show up in the environment.  \n\nInsert a code chunk below to display `hbr_maples` in the environment using `data(\"hbr_maples\")`. Name the code chunk `data`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"hbr_maples\")\n```\n:::\n\n\n### 2. Cleaning and wrangling\n\nInsert a code chunk to:  \n\n1. create a new object from `hbr_maples` called `maples_2003`  \n2. filter observations to only include the year 2003  \n3. mutate the `watershed` column so that `W1` is filled in as `Calcium-treated`  \n\nName the code chunk `data cleaning`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# start with hbr_maples data frame\nmaples_2003 <- hbr_maples |> \n   # filter to only include observations from 2003\n  filter(year == \"2003\") |>\n  # rename watersheds\n  mutate(watershed = case_when( \n    watershed == \"Reference\" ~ \"Reference\",\n    watershed == \"W1\" ~ \"Calcium-treated\"\n  ))\n```\n:::\n\n\n### 3. Exploratory data visualization\n\nInsert a code chunk to make a boxplot + jitter plot comparing stem lengths between watersheds. Remember to:  \n\n1. color by watershed  \n2. control the jitter so that the points don't move up and down the y-axis  \n\nName the code chunk `boxplot-with-jitter`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = maples_2003, # starting data frame\n       mapping = aes(x = watershed, # x-axis\n                     y = stem_length, # y-axis\n                     color = watershed)) + # coloring by watershed\n  # first layer: boxplot\n  geom_boxplot() +\n  # second layer: jitter plot\n  geom_jitter(height = 0, # making sure points don't move along y-axis\n              width = 0.2) # narrowing width of jitter\n```\n\n::: {.cell-output-display}\n![](workshop-03_2026-04-17_files/figure-html/boxplot-with-jitter-1.png){width=672}\n:::\n:::\n\n\n### 4. Checks for t-test assumptions\n\n#### a. Normally distributed response variable\n\n##### Histogram\n\nInsert a code chunk to create a histogram. Name the code chunk `histogram`.  \n\nUse `facet_wrap()` to create separate panels for each watershed. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# starting data frame\nggplot(data = maples_2003, \n       # x-axis (no y-axis for histogram)\n       mapping = aes(x = stem_length)) + \n  # number of bins from Rice Rule\n  geom_histogram(bins = 6) + \n  # creating two panels to show watersheds separately\n  facet_wrap(~watershed) \n```\n\n::: {.cell-output-display}\n![](workshop-03_2026-04-17_files/figure-html/histogram-1.png){width=672}\n:::\n:::\n\n\n##### QQ plot\n\nInsert a code chunk to create a QQ plot. Name the code chunk `qq-plot`.  \n\nUse `facet_wrap()` to create separate panels for each watershed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot call\nggplot(data = maples_2003,\n       # y-axis for QQ plot (no x-axis for QQ plot)\n       mapping = aes(sample = stem_length)) + \n  # first layer: QQ reference line in blue\n  geom_qq_line(color = \"blue\") +\n  # second layer: QQ plot\n  geom_qq() + \n  # creating \"facets\"\n  facet_wrap(~ watershed) # show watersheds separately\n```\n\n::: {.cell-output-display}\n![](workshop-03_2026-04-17_files/figure-html/qq-plot-1.png){width=672}\n:::\n:::\n\n\n**Check in:** using histograms and QQ plots, does stem length seem to be normally distributed?  \n\n**Yes, because the histogram looks symmetrical, and the QQ plot points follow a straight line.**  \n\n#### b. Equal variances\n\nNext, we'll check our variances. \n\n##### Variance ratio by hand\n\nWe can make sure we know where the F test results are coming from by calculating the variance ratios ourselves. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create new object from maples_2003\nstem_length_var <- maples_2003 |>\n  # group by watershed\n  group_by(watershed) |> \n  # calculate variances\n  summarize(variance = var(stem_length)) |> \n  # ungroup data frame\n  ungroup()\n\n# calculate variance ratio\n# double check against results of var.test()\n205.7026/194.3021\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.058674\n```\n\n\n:::\n:::\n\n\n##### F-test of equal variances\n\nInsert a code chunk to check the variances using `var.test()`. Name the code chunk `F-test`.  \n\nIn the function `var.test()`, enter the arguments for:  \n\n1. the formula  \n2. the data  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# doing F test of equal variances\nvar.test(\n  # formula: response variable ~ grouping variable\n  stem_length ~ watershed, \n  # data: maples_2003 data frame\n  data = maples_2003 \n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  stem_length by watershed\nF = 1.0587, num df = 119, denom df = 119, p-value = 0.7563\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.7378244 1.5190473\nsample estimates:\nratio of variances \n          1.058674 \n```\n\n\n:::\n:::\n\n\nRemember that this variance test is an F test of equal variances. You are comparing the variance of one group with another.  \n\nTo communicate about this, you could write something like:  \n\nUsing an F-test of equal variances, we determined that variances were (equal or not equal) (F(num df, denom df) = F ratio, p-value).  \n\nWe determined that group variances were (equal or not equal) (F-test of equal variances, F(num df, denom df) = F statistic, p-value).  \n\nFill in the blank here:  \n\n**We determined that group variances were equal (F-test of equal variances, F(119, 119) = 1.06, p = 0.76, $\\alpha = 0.05$).**    \n\n### 5. Doing a t-test\n\nInsert a code chunk to do a t-test. Name the code chunk `t-test`.  \n\nIn the function `t.test()`, enter the arguments for:  \n\n1. the formula  \n2. the variances in `var.equal = `  \n3. and the dataframe in `data = `  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(\n  # formula: response variable ~ grouping variable\n  stem_length ~ watershed, \n  # data: maples_2003 data frame\n  data = maples_2003, \n  # variances are equal (checked using F-test)\n  var.equal = TRUE \n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  stem_length by watershed\nt = 3.7797, df = 238, p-value = 0.0001985\nalternative hypothesis: true difference in means between group Calcium-treated and group Reference is not equal to 0\n95 percent confidence interval:\n  3.304134 10.497532\nsample estimates:\nmean in group Calcium-treated       mean in group Reference \n                     87.88583                      80.98500 \n```\n\n\n:::\n:::\n\n\n### 6. Communicating\n\n#### a. visual communication\n\nWhen doing a t-test, remember that you are comparing _means_. To visualize the data in a way that reflects the values you are comparing (again, you are comparing _means_), you can visualize the _means_ of each watershed with the standard deviation (spread), standard error (variation), or confidence interval (confidence).  \n\nIn this example, we will show 95% confidence intervals.  \n\nIn this code chunk, we are calculating the means and 95% confidence intervals. Name the code chunk `ci-calculation`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# creating new object from maples_2003\nmaples_ci <- maples_2003 |> \n  # group by watershed\n  group_by(watershed) |> \n  # calculations\n  summarize(mean = mean(stem_length), # mean\n            n = length(stem_length), # number of observations\n            df = n - 1, # degrees of freedom\n            sd = sd(stem_length), # standard deviation\n            se = sd/sqrt(n), # standard error\n            tval = qt(p = 0.05/2, df = df, lower.tail = FALSE), # t-value\n            margin = tval*se, # margin of error\n            ci_lower = mean - margin, # lower bound of the confidence interval\n            ci_upper = mean + margin # upper bound of the confidence interval\n          ) |> \n  # ungrouping the data frame\n  ungroup()\n```\n:::\n\n\nBefore moving on, look at the `maples_ci` object to make sure you know what it contains.  \n\nNote that this visualization uses two data frames. We use `maples_2003` to show the underlying data using `geom_jitter()`, and `maples_ci` to show the mean and 95% CI.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot with the x- and y-axes\nggplot(data = maples_2003, # using the maples_2003 data frame\n       mapping = aes(x = watershed, # x-axis\n                     y = stem_length, # y-axis\n                     color = watershed)) + # coloring points by watershed\n  # first layer: showing the underlying data\n  geom_jitter(height = 0, # no jitter in the vertical direction\n              width = 0.1, # smaller jitter in the horizontal direction\n              alpha = 0.4, # make the points more transparent\n              shape = 21) + # make the points open circles\n  # second layer: showing the summary (mean and 95% CI)\n  # using maples_ci data frame\n  geom_pointrange(data = maples_ci, \n                  aes(x = watershed, \n                      y = mean, \n                      ymax = ci_lower, \n                      ymin = ci_upper)) + \n  # relabelling x- and y-axes\n  labs(x = \"Watershed\", \n       y = \"Stem length (cm)\") +\n  # figure customization to change point colors\n  # Note: this is optional (but nice to do!)\n  scale_color_manual(values = c(\"Calcium-treated\" = \"darkorchid3\",\n                                \"Reference\" = \"tomato3\")) + \n  # using a theme\n  theme_bw() + \n  # getting rid of the legend\n  theme(legend.position = \"none\") \n```\n\n::: {.cell-output-display}\n![](workshop-03_2026-04-17_files/figure-html/ci-visualization-1.png){width=672}\n:::\n:::\n\n\n#### b. Writing\n\nSummarize the results of the t-test in one sentence. Before you do, make sure you know the:  \n\n##### type of test  \n\nStudent's t (note: this is because variances are equal)\n\n##### Sample size  \n\nn = 120 for calcium-treated, n = 120 for reference (240 total)  \n\n##### Sample means\n\n87.9 cm for calcium-treated, 81.0 cm for reference\n\n##### significance level ($\\alpha$)  \n\n$\\alpha$ = 0.05 \n\n##### degrees of freedom  \n\n238 (note: 240 - 2 = 238)  \n\n##### t-value (aka t-statistic)  \n\n3.8\n\n##### p-value  \n\np < 0.001 (don't need to give exact number for anything below 0.001)  \n\n##### Results summary\n\nWe found a significant difference in sugar maple stem lengths between calcium-treated (n = 120, mean = 87.9 cm) and reference (n = 120, mean = 81.0 cm) watersheds (Student's t-test, t(238) = 3.8, p < 0.001, $\\alpha$ = 0.05).      \n\n**END OF WORKSHOP 3**\n\n## 3. Extra stuff\n\n### Setting global options for code execution\n\nIf you want _any_ messages to be hidden in your rendered Quarto document, then you can adjust the **YAML** at the top of the document. This is the section that has 3 dashes at the beginning and end (where you enter your name, the date, and your execution option).  \n\nThe **YAML** controls the aesthetics of the rendered doc (or PDF, or HTML) that is created from your Quarto document. See more details [here](https://rpubs.com/drgregmartin/1266674) and [here from the Quarto user manual](https://quarto-tdg.org/yaml).  \n\nTo adjust the YAML for a .qmd file for which you want all messages to be hidden, you can add the following lines to the YAML:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexecute:\n  message: false\n```\n:::\n\n\nSo the complete YAML for workshop 3, for example, would look something like this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n---\ntitle: \"Week 3 workshop: sugar maples\"\nauthor: \"An Bui\"\nformat: docx\nexecute:\n  message: false\n---\n```\n:::\n\n\n:::{.callout-note title=\"Indentations matter!\" collapse=\"true\"}\nWhen adjusting settings in the YAML, you need to be very careful about the indentations. The YAML code as written above will work, but YAML code written without the tab before `message` (example below) will not.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n---\ntitle: \"Week 3 workshop: sugar maples\"\nauthor: \"An Bui\"\nformat: docx\nexecute:\nmessage: false\n---\n```\n:::\n\n\n:::\n",
    "supporting": [
      "workshop-03_2026-04-17_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}