---
title: "Guidelines and policies on using AI"
description: "Openness about using AI is good, actually!"
categories: [general use]
---

## Why use AI?

Generative AI tools like ChatGPT, Claude, Copilot, etc. can help solve a lot of coding problems: if you're stuck and don't know where to start, if you have code that keeps giving you an error, etc. - most of these issues can be solved using AI.  

Additionally, we (the teaching team) are not delusional! We know you are using AI! The key to effective use of generative AI tools in environmental studies is to be honest about its use.

## Why _wouldn't_ you use AI in this class?

If you're just starting out learning how to code, we recommend _not_ using generative AI tools. You will likely retain a lot more information by googling, asking for help from classmates, meeting with An or Amanda, or literally doing anything other than using a generative AI tool. In our experience, the conversations and discussions around materials _and_ the struggle of sifting through a lot of information to try different things out is really effective for retaining information.  

Additionally, while gen AI can quickly come up with code, it's not always what you would expect, or what we expect to see in your assignments. It's straightforward to see if it works - if the output is what you want, then the code works - but there are specifics in each assignment that you as a student enrolled in the class will know that an AI tool will not.

## If I want to use AI, what am I allowed to do?

If you want to use an AI tool, you may use it to:  

- To brainstorm or clarify your understanding of the assignment (e.g. "I have this idea but I'm not sure if it's right. Can you help me figure out if it applies to this assignment?")  
- To outline your approach or plan your workflow (e.g. "Can you help me figure out how to start this problem?")  
- To clarify or deepen understanding of technical concepts (e.g. "What does this function do in my use case?")  
- To generate or refine code snippets (e.g. "I wrote this code but I think it's too long. How can I condense it?")  
- To debug or troubleshoot code (e.g. "I wrote this code but it's not working. What's wrong with it?")  
- To edit or improve the clarity, structure, or tone of my written responses (e.g. "I wrote this text to summarize a test but it's too long. Can you help me shorten it to 1-2 sentences?")  
- To check my reasoning, results, or interpretation of findings (e.g. "I interpreted a statistical test in this way. Is my interpretation correct?")  

## What am I _not_ allowed to do?

You are _not_ allowed to use generative AI to produce new code for you to copy-paste into your assignments. Additionally, you _may not_ use AI to generate new writing for you. For example, these prompts would not be allowed:  

- "Write me code to visualize a boxplot."  
- "Write the description of the results of this ANOVA."  

All code and writing in your assignments should be generated by you alone to start out with. 

## I'm ready to use AI on my assignments. What should I do when I submit?

All assignments need to include a generative AI statement of use, linked on Canvas on the Resources page and in the assignment portal.  

Keep in mind that unreported or disallowed use of AI tools will result in an incomplete mark on an assignment and the assignment will not be eligible for revision or resubmission.  

## I'm not sure if what I'm using AI for is allowed. What do I do?

Talk to An or Allison!

## I'm troubled about AI use, because of the environmental impacts, disadvantages, brain deterioration, etc. What do I do?

Again, talk to An or Allison! We are here to help navigate this new landscape, and figure out a plan that works for you, whether that's sparingly using AI, not using it at all and relying on other resources, etc.



