---
title: How to resubmit an assignment
description: "Made some mistakes? Fix them!"
categories: [general use]
---

## Assignments eligible for resubmission

You can submit one (1) request for resubmission for either of the following assignments:

1. your midterm
2. your choose your own assignment (a Quarto website or an advanced data visualization)  

## Format for resubmission request

Email An with the subject line "ENVS 193DS resubmission" along with the title of the assignment you are resubmitting.

Write your request for resubmission in a separate PDF.

**For each component that you want to redo** for the _possibility_ of getting points back, you will need to articulate (in 1-2 sentences, the shorter, the better):

1. what you got wrong
2. what you need to do to fix it
3. why that fix would improve the quality of your work (_independently of the grade you received_)

For example, if you got points off for x-axis labels on a plot that were overlapping, a reasonable request would be:

**Problem 2a**

1. My x-axis labels for Problem 2a were overlapping.
2. I need to either spread out the x-axis or fix the way I read in the data to make sure the columns are correct (so that the date column is read in as a date rather than a character).
3. Making sure the x-axis labels don't overlap improves the figure because it would be more readable.

## After you submit your request to resubmit

An will review your request for resubmission and either confirm or deny the request (if denied, you will be told how to improve your request prior to receiving approval).

Once you get the ok from An, you will have a week to resubmit your assignment.

Note that An will regrade your _whole_ assignment. There is no guarantee of a better grade.
