---
title: "Week 5 figures - Lectures 9 and 10"
editor: source
freeze: auto
execute:
  message: false
  warning: false
format:
  html: 
    code-fold: true
author:
  - name: An Bui
    url: https://an-bui.com/
    affiliation: UC Santa Barbara, Ecology, Evolution, and Marine Biology
    affiliation-url: https://www.eemb.ucsb.edu/
published-title: "Lecture date"
date: 2024-04-29
date-modified: last-modified
categories: []
citation:
  url: https://spring-2024.envs-193ds.com/lecture/lecture_week-05.html
---


```{r message = FALSE}
# cleaning
library(tidyverse)

# visualization
theme_set(theme_classic() +
            theme(panel.grid = element_blank(),
                  axis.text = element_text(size = 18),
                  axis.title = element_text(size = 18),
                  text = element_text(family = "Lato")))
library(patchwork)

# data
library(palmerpenguins)

# analysis
library(car)
```

## Chi-square

### test statistic:

$$
\chi^2 = \Sigma\frac{(O-E)^2}{E}
$$
### degrees of freedom
$$
df = (number\;of\;rows - 1) * (number\;of\;columns - 1)
$$

### expected counts:
$$
expected = \frac{row\;total * column\;total}{table\;total}
$$

### expected counts example from lecture
$$
\frac{126 * 118}{315} = 47.2
$$

### test statistic calculation example from lecture
$$
\begin{align}
\chi^2 &= \Sigma\frac{(O-E)^2}{E} \\
\chi^2 &= \frac{55-47.2}{47.2}+...+\frac{45-31.9}{31.9} \\
&= 15.276
\end{align}
$$






U statistic:
$$
\begin{align}
U_1 &= \Sigma R_1 - n_1(n_1 + 1)/2 = 17 - 5(5+1)/2 = 2 \\
U_2 &= \Sigma R_2 - n_2(n_2 + 1)/2 = 38 - 5(5+1)/2 = 23
\end{align}
$$

```{r}
Sample1 <- c(1.1, 2.4, 1.8, 0.4, 1.6)
Sample2 <- c(5.4, 3.1, 2.3, 1.9, 4.2)
wilcox.test(Sample1, Sample2)
```

```{r eval = FALSE}
# for a comparison of one group against a theoretical median
wilcox.test(SampleA, mu = theoretical)

# for a comparison of two groups
wilcox.test(SampleA, SampleB, paired = TRUE)
```





