---
title: "Week 4 figures - Lectures 7 and 8"
editor: source
freeze: auto
execute:
  message: false
  warning: false
format:
  html: 
    code-fold: true
author:
  - name: An Bui
    url: https://an-bui.com/
    affiliation: UC Santa Barbara, Ecology, Evolution, and Marine Biology
    affiliation-url: https://www.eemb.ucsb.edu/
published-title: "Lecture date"
date: 2024-04-24
date-modified: last-modified
categories: []
citation:
  url: https://spring-2024.envs-193ds.com/lecture/lecture_week-04.html
---


## 0. set up

```{r}
#| message: false

# cleaning
library(tidyverse)

# visualization
theme_set(theme_classic() +
            theme(panel.grid = element_blank(),
                  axis.text = element_text(size = 18),
                  axis.title = element_text(size = 18),
                  text = element_text(family = "Lato")))
library(patchwork)

# cohen's d
library(effectsize)
```

## 1. Math


### a. Cohen's d

$$
Cohen's \; d = \frac{\bar{y_A} - \bar{y_B}}{\sqrt{(s^2_A + s^2_B)/2}}
$$

### b. Cohen's d with separated SD

$$
Cohen's \; d = \frac{\bar{y_A} - \bar{y_B}}{\sqrt{\frac{(n_A - 1)\times s^2_A + (n_B - 1)\times s^2_B}{n_A + n_B + 2}}}
$$



### b. confidence interval for two-sample t-test

$$
CI = (\bar{y_A} - \bar{y_B}) \pm t \times \sqrt{\frac{(n_A - 1)s_A^2 + (n_B - 1)s_B^2}{n_A+n_B-2}} \times \sqrt{\frac{1}{n_A}+\frac{1}{n_B}}
$$

### c. test statistic for paired t-test

$$
t_s = \frac{\bar{y}_d - \mu_0}{s_d - \sqrt{n}}
$$

## 2. Effect size examples

### a. large sample size, small difference

```{r small-vs-large-sample-size}
set.seed(1)
small <- cbind(a = rnorm(n = 10, mean = 10, sd = 2), 
               b = rnorm(n = 10, mean = 11, sd = 2)) %>% 
  as_tibble() %>% 
  pivot_longer(cols = 1:2, names_to = "group", values_to = "value")
t.test(value ~ group,
       data = small,
       var.equal = TRUE)

set.seed(1)
large <- cbind(a = rnorm(n = 100, mean = 10, sd = 2), 
               b = rnorm(n = 100, mean = 11, sd = 2)) %>% 
  as_tibble() %>% 
  pivot_longer(cols = 1:2, names_to = "group", values_to = "value")
t.test(value ~ group,
       data = large,
       var.equal = TRUE)
```


### b. needlegrass example

```{r needlegrass}
set.seed(1)
needlegrass <- cbind(ungrazed = rnorm(n = 25, mean = 80, sd = 10), 
                     grazed = rnorm(n = 25, mean = 78, sd = 5)) %>% 
  as_tibble() %>% 
  pivot_longer(cols = 1:2, names_to = "plot_type", values_to = "height_cm")

ggplot(data = needlegrass,
       aes(x = plot_type,
           y = height_cm)) +
  geom_point(position = position_jitter(width = 0.2, seed = 1),
             alpha = 0.2) +
  stat_summary(geom = "pointrange",
               fun.data = mean_cl_normal) +
  labs(x = "Plot type",
       y = "Height (cm)")
```

Doing a t-test:

```{r}
var.test(height_cm ~ plot_type,
       data = needlegrass)
t.test(height_cm ~ plot_type,
       data = needlegrass,
       var.equal = FALSE)
```

Cohen's d:

```{r}
# pooled SD
cohens_d(height_cm ~ plot_type,
       data = needlegrass)

# unpooled SD
cohens_d(height_cm ~ plot_type,
       data = needlegrass, 
       pooled_sd = FALSE)

# by hand
needlegrass_sum <- needlegrass %>% 
  group_by(plot_type) %>% 
  reframe(
    mean = mean(height_cm),
    var = var(height_cm),
    n = length(height_cm)
  )

ya <- pluck(needlegrass_sum, 2, 1)
yb <- pluck(needlegrass_sum, 2, 2)
vara <- pluck(needlegrass_sum, 3, 1)
varb <- pluck(needlegrass_sum, 3, 2)
na <- pluck(needlegrass_sum, 4, 1)
nb <- pluck(needlegrass_sum, 4, 2)

# by hand

(ya - yb)/sqrt((vara + varb)/2)

(ya - yb)/sqrt(
  ((na - 1)*vara + (nb - 1)*varb)/(na + nb - 2)
)

```



## 2. Power analysis
demonstration of power analysis:

```{r}
library(pwr)

pwr.t.test(n = NULL, d = 0.5, sig.level = 0.05, power = 0.95)

pwr.t.test(n = NULL, d = 0.7, sig.level = 0.05, power = 0.80)
```


U statistic:
$$
\begin{align}
U_1 &= \Sigma R_1 - n_1(n_1 + 1)/2 = 17 - 5(5+1)/2 = 2 \\
U_2 &= \Sigma R_2 - n_2(n_2 + 1)/2 = 38 - 5(5+1)/2 = 23
\end{align}
$$

```{r}
Sample1 <- c(1.1, 2.4, 1.8, 0.4, 1.6)
Sample2 <- c(5.4, 3.1, 2.3, 1.9, 4.2)
wilcox.test(Sample1, Sample2)
```

```{r eval = FALSE}
# for a comparison of one group against a theoretical median
wilcox.test(SampleA, mu = theoretical)

# for a comparison of two groups
wilcox.test(SampleA, SampleB, paired = TRUE)
```


balanced design using Student's t:

$$
\begin{align}
SE_{\bar{x}_A-\bar{x}_B} &= s_p\sqrt{\frac{1}{n_A} + \frac{1}{n_B}} \\
Scenario 1 &: s_p\sqrt{\frac{1}{5} + \frac{1}{25}} = s_p*0.49 \\
Scenario 2 &: s_p\sqrt{\frac{1}{15} + \frac{1}{15}} = s_p*0.37
\end{align}
$$




