{
  "hash": "62f6639e30560e38aa6c9df577b3e981",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Coding workshop: Week 5\"\nsubtitle: \"Analysis of variance\"\ndate: 2026-05-01\ncategories: [tidyverse, lterdatasampler, rstatix, aov, summary, TukeyHSD, eta_squared, read_csv, pipe operators, '|>', select, rename, ggplot, geom_histogram, geom_qq, geom_qq_line, facet_wrap, group_by, summarize, as_factor, mutate]\nformat:\n  html:\n    toc: true\n    toc-depth: 8\n---\n\n\n[Workshop date: Friday 1 May]{style=\"color: #79ACBD; font-size: 24px;\"}\n\n## 1. Summary\n\n### Packages\n\n- `tidyverse`\n- `lterdatasampler`\n- `rstatix`\n\n### Operations\n\n#### New functions\n\n- make sure a variable is a factor using `as_factor()`\n- do an ANOVA using `aov()`\n- look for more information from model results using `summary()`\n- do post-hoc Tukey test using `TukeyHSD()`\n- calculate effect size for ANOVA using `rstatix::eta_squared()`\n\n#### Review\n\n- read in data using `read_csv()`\n- chain functions together using ` |> `\n- modify columns using `mutate()`\n- select columns using `select()`\n- rename columns using `rename()`\n- visualize data using `ggplot()`\n- create histograms using `geom_histogram()`\n- visualize QQ plots using `geom_qq()` and `geom_qq_line()`\n- create multi-panel plots using `facet_wrap()`\n- group data using `group_by()`\n- undo grouping using `ungroup()`\n- summarize data using `summarize()`\n\n### Data sources\n\nThe Plum Island Ecosystem fiddler crab data is from `lterdatasampler` (data info [here](https://lter.github.io/lterdatasampler/articles/pie_crab_vignette.html)). Crab carapace width is measured in mm.\n\n## 2. Code\n\n### 1. Set up\n\n#### Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lterdatasampler)\nlibrary(effectsize)\nlibrary(rstatix)\n```\n:::\n\n\n#### Data \n\n::: {.cell}\n\n```{.r .cell-code}\n# for parametric tests\ndata(pie_crab)\n\n# for non-parametric tests\nramen_ratings <- read_csv(\"ramen_ratings.csv\")\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n### 2. Parametric tests\n\n#### a. Cleaning and wrangling\n\nCreate a new object called `pie_crab_clean`. Filter to only include the following sites: Cape Cod, Virginial Coastal Reserve LTER, and Zeke's Island NERR. Select the columns of interest: `site`, `name`, and `code`. Rename the column `name` to `site_name` and `code` to `site_code`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# start with the pie_crab dataset\npie_crab_clean <- pie_crab |> \n  # filter for Cape Cod, Zeke's Island, Virginia Coastal\n  filter(site %in% c(\"CC\", \"ZI\", \"VCR\")) |> \n  # select columns of interest\n  select(site, name, size) |> \n  # rename columns\n  rename(site_code = site, \n         site_name = name) \n```\n:::\n\n\n#### b. Quick summary\n\nCreate a new object called `pie_crab_summary`. Calculate the mean, variance, and sample size. Display the object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# creating a new object called pie_crab_summary\npie_crab_summary <- pie_crab_clean |> \n  # group by site\n  group_by(site_name) |> \n  # calculate mean, variance, sample size\n  summarize(mean = mean(size), \n            var = var(size), \n            n = length(size)) |> \n  # ungroup data frame\n  ungroup()\n\n# display pie_crab_summary\npie_crab_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  site_name                      mean   var     n\n  <chr>                         <dbl> <dbl> <int>\n1 Cape Cod                       16.8  4.22    27\n2 Virginia Coastal Reserve LTER  16.3  8.63    30\n3 Zeke's Island NERR             12.1  4.04    35\n```\n\n\n:::\n:::\n\n\n#### c. Exploring the data\n\nCreate a jitter plot with the mean crab size for each site.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = pie_crab_clean, \n       # x-axis: full site name\n       # y-axis: crab size\n       mapping = aes(x = site_name, \n                     y = size)) + \n  # first layer: jitter (each point is an individual crab)\n  geom_jitter(height = 0, # don't jitter points vertically\n              width = 0.1) + \n  # second layer: point representing mean\n  stat_summary(geom = \"point\", # geometry being plotted\n               fun = mean, # function (calculating the mean)\n               color = \"red\", # color to make it easier to see\n               size = 5) + # larger point size\n  # cleaner plot theme\n  theme_minimal() \n```\n\n::: {.cell-output-display}\n![](workshop-05_2026-05-01_files/figure-html/exploratory visualization-1.png){width=672}\n:::\n:::\n\n\nIs there a difference in mean crab carapace width (mm) between the three sites? What visual components of the plot are you using to make that guess? \n\n**insert response here**\n\n#### d. Check 1: normally distributed variable\n\nCreate a histogram of crab size. Facet your histogram so that you have 3 panels, with one panel for each site.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = pie_crab_clean, \n       aes(x = size)) + # x-axis\n  # first layer: histogram\n  geom_histogram(bins = 9) + # number of bins from Rice Rule\n  # faceting by site_name: creating 3 different panels\n  facet_wrap(~ site_name) \n```\n\n::: {.cell-output-display}\n![](workshop-05_2026-05-01_files/figure-html/crab-histogram-1.png){width=672}\n:::\n:::\n\n\nCreate a QQ plot of crab size. Facet your QQ plot so that you have 3 panels, with one panel for each site.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = pie_crab_clean, \n       aes(sample = size)) + # y-axis\n  # first layer: QQ plot reference line\n  geom_qq_line(color = \"orange\") + \n  # second layer: QQ plot points (actual observations)\n  geom_qq() + \n  # faceting by site_name\n  facet_wrap(~ site_name, \n             scales = \"free\") # let axes vary between panels\n```\n\n::: {.cell-output-display}\n![](workshop-05_2026-05-01_files/figure-html/crab-qq-1.png){width=672}\n:::\n:::\n\n\nWhat are the outcomes of your visual checks?  \n\n**summarize outcomes here**  \n\n#### e. Check 2: equal variances\n\nDo a gut check: is the ratio of the largest variance to the smallest variance less than 3?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n8.63/4.04\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.136139\n```\n\n\n:::\n:::\n\n\n#### f. ANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# creating an object called crab_anova\ncrab_anova <- aov(\n  # size as a function of site\n  size ~ site_name, \n  # using clean data frame\n  data = pie_crab_clean\n) \n\n# object\ncrab_anova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\n   aov(formula = size ~ site_name, data = pie_crab_clean)\n\nTerms:\n                site_name Residuals\nSum of Squares   442.2073  497.4372\nDeg. of Freedom         2        89\n\nResidual standard error: 2.364145\nEstimated effects may be unbalanced\n```\n\n\n:::\n\n```{.r .cell-code}\n# gives more information\nsummary(crab_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)    \nsite_name    2  442.2  221.10   39.56 5.1e-13 ***\nResiduals   89  497.4    5.59                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nSummarize results: is there a difference in mean crab size (measured as carapace width in mm) between the three sites?  \n\n**There is a difference in mean crab carapace width between Cape Cod, Virginia Coastal Reserve LTER, and Zeke's Island NERR (one-way ANOVA, F(2, 89) = 39.6, p < 0.001, $\\alpha$ = 0.05).**\n\n#### g. Post-hoc: Tukey HSD\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(crab_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = size ~ site_name, data = pie_crab_clean)\n\n$site_name\n                                                       diff       lwr       upr\nVirginia Coastal Reserve LTER-Cape Cod           -0.4795185 -1.974354  1.015317\nZeke's Island NERR-Cape Cod                      -4.7514709 -6.194843 -3.308099\nZeke's Island NERR-Virginia Coastal Reserve LTER -4.2719524 -5.673993 -2.869912\n                                                     p adj\nVirginia Coastal Reserve LTER-Cape Cod           0.7255994\nZeke's Island NERR-Cape Cod                      0.0000000\nZeke's Island NERR-Virginia Coastal Reserve LTER 0.0000000\n```\n\n\n:::\n:::\n\n\nWhich pairwise comparisons are actually different? Which ones are not different?  \n\n**Zeke's Island NERR and Cape Cod crabs are different, and Zeke's Island NERR and Virginia Coastal Reserve LTER crabs are different. Virginia Coastal Reserve LTER and Cape Cod crabs are not different.**\n\n#### h. effect size\n\nUsing `eta_squared()` from `rstatix`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrstatix::eta_squared(crab_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsite_name \n0.4706113 \n```\n\n\n:::\n:::\n\n\nWhat is the magnitude of the differences between sites in crab size?  \n\n**There is a large difference in crab size between sites.**  \n\nAnother way of saying this: there is a **large** effect of site on crab size. There is a **large** difference between sites in crab size.\n\n#### i. Putting everything together\n\n**means**\n\nZeke's Island NERR: 12.1 mm\nCape Cod: 16.8 mm\nVirginia Coastal Reserve LTER: 16.3 mm\n\n**test type**\n\none-way ANOVA\n\n**test distribution**\n\nF\n\n**distribution parameters**\n\nnumerator and denominator degrees of freedom: 2, 89\n\n**test statistic**\n\nF-statistic: 39.6\n\n**p-value**\n\n5.1e-13, expressed as p < 0.001\n\n**significance level**\n\n$\\alpha$ = 0.05\n\n**post-hoc tests**\n\nused Tukey HSD (Honestly Significant Difference)\nZeke's Island different from Cape Cod and VCR, Cape Cod and VCR are not different\n\n**effect size**\n\n$\\eta^2$ = 0.47\n\n**Writing:**\n\nWe found a large ($\\eta^2$ = 0.47) difference between sites in mean crab carapace width (one-way ANOVA, F(2, 89) = 39.6, p < 0.001, $\\alpha$ = 0.05). The smallest crabs were from Zeke's Island NERR, which had an average width of 12.1 mm. Zeke's Island crabs were 4.8 mm (95% CI: [3.3, 6.2] mm) smaller than crabs from Cape Cod (Tukey's HSD: p < 0.001) and 4.3 mm (95% CI: [2.9, 5.7] mm) smaller than crabs from Virginia Coastal Reserve LTER (Tukey's HSD: p < 0.001).  \n\n### 3. Non-parametric tests\n\n#### a. Clean and wrangle the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create new object from ramen ratings\nramen_ratings_clean <- ramen_ratings |> \n  # filter to only include Maruchan ramen\n  filter(brand == \"Maruchan\") |> \n  # reorder style factor\n  mutate(style = fct_relevel(style, \"Bowl\", \"Pack\", \"Tray\", \"Cup\")) \n\n# look at the structure\nstr(ramen_ratings_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [106 × 6] (S3: tbl_df/tbl/data.frame)\n $ review_number: num [1:106] 3176 3152 3141 3124 3111 ...\n $ brand        : chr [1:106] \"Maruchan\" \"Maruchan\" \"Maruchan\" \"Maruchan\" ...\n $ variety      : chr [1:106] \"Gotsumori Shio Yakisoba\" \"QTTA Curry Ramen\" \"Thai Red Curry Udon\" \"Kitsune Udon 40th Anniversary\" ...\n $ style        : Factor w/ 4 levels \"Bowl\",\"Pack\",..: 3 4 1 1 1 4 1 1 4 3 ...\n $ country      : chr [1:106] \"Japan\" \"Japan\" \"Japan\" \"Japan\" ...\n $ stars        : num [1:106] 5 5 5 4.5 4 4 3.75 2 2.5 2.5 ...\n```\n\n\n:::\n:::\n\n\n#### b. Quick summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a new object from clean data frame\nramen_ratings_summary <- ramen_ratings_clean |> \n  # group by style\n  group_by(style) |> \n  # calculate the median\n  summarize(median = median(stars)) |> \n  # ungroup data frame\n  ungroup()\n\n# display the object\nramen_ratings_summary \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  style median\n  <fct>  <dbl>\n1 Bowl    4.25\n2 Pack    3.75\n3 Tray    3.75\n4 Cup     3.5 \n```\n\n\n:::\n:::\n\n\n\n#### c. Make a boxplot to compare star ratings across ramen styles\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = ramen_ratings_clean, \n       # x-axis: ramen style\n       # y-axis: star rating\n       # color by style\n       mapping = aes(x = style, \n                     y = stars, \n                     color = style)) + \n  # first layer: boxplot\n  geom_boxplot(color = \"darkgrey\", \n               # removing outliers because they're shown in jitter\n               outliers = FALSE) + \n  # second layer: jitter to represent individual ramen styles\n  geom_jitter(height = 0,\n              width = 0.1,\n              size = 2,\n              alpha = 0.6) +\n  # set custom colors\n  scale_color_manual(values = c(\"firebrick4\", \"orange\", \"gold\", \"darkgreen\")) + \n  # minimal theme\n  theme_minimal() + \n  # take out the legend\n  theme(legend.position = \"none\") \n```\n\n::: {.cell-output-display}\n![](workshop-05_2026-05-01_files/figure-html/ramen-exploratory-visualization-1.png){width=672}\n:::\n:::\n\n\n#### d. Do the Kruskal-Wallis test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(\n  # formula: star ratings as a function of ramen style\n  stars ~ style, \n  # data frame\n  data = ramen_ratings_clean \n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  stars by style\nKruskal-Wallis chi-squared = 15.679, df = 3, p-value = 0.00132\n```\n\n\n:::\n:::\n\n\nIs there a difference in ratings between ramen styles?  \n\n**Ramen styles differ in ratings (Kruskal-Wallis rank sum test, $\\chi^2$(3) = 15.7, p = 0.0013).**\n\n#### e. Do a Dunn's post-hoc test\n\nUsing `dunn_test()` from `rstatix`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndunn_test(\n  # formula: star ratings as a function of ramen style\n  stars ~ style, \n  # data frame\n  data = ramen_ratings_clean \n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  .y.   group1 group2    n1    n2 statistic        p   p.adj p.adj.signif\n* <chr> <chr>  <chr>  <int> <int>     <dbl>    <dbl>   <dbl> <chr>       \n1 stars Bowl   Pack      33    30    -2.61  0.00898  0.0449  *           \n2 stars Bowl   Tray      33    17    -2.54  0.0112   0.0449  *           \n3 stars Bowl   Cup       33    26    -3.70  0.000213 0.00128 **          \n4 stars Pack   Tray      30    17    -0.323 0.747    0.985   ns          \n5 stars Pack   Cup       30    26    -1.16  0.244    0.733   ns          \n6 stars Tray   Cup       17    26    -0.686 0.492    0.985   ns          \n```\n\n\n:::\n:::\n\n\nWhich pairwise comparisons of ramen styles are different from each other?  \n\n**Bowls and packs are different, bowls and trays are different, bowls and cups are different. Packs are not different from trays or cups, and trays are not different from cups.**\n\n#### f. Calculate an effect size\n\nUsing `kruskal_effsize()` from `rstatix`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal_effsize(\n  # formula: star ratings as a function of ramen style\n  stars ~ style, \n  # data frame\n  data = ramen_ratings_clean \n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  .y.       n effsize method  magnitude\n* <chr> <int>   <dbl> <chr>   <ord>    \n1 stars   106   0.124 eta2[H] moderate \n```\n\n\n:::\n:::\n\n\nWhat is the magnitude of the effect of ramen style on ratings?  \n\n**There is a moderate ($\\eta^2$ = 0.12) effect of ramen style on ratings.**\n\n#### g. Putting everything together\n\n**medians**\n\nBowl: 4.25 stars\nPack: 3.75 stars\nTray: 3.75 stars\nCup: 3.5 stars\n\n**test**\n\nKruskal-Wallis rank sum\n\n**test \"distribution\"**\n\n$\\chi^2$\n\n**distribution parameters**\n\ndegrees of freedom (3)\n\n**test statistic**\n\n15.7\n\n**p-value**\n\n0.0013\n\n**significance level**\n\n$\\alpha$ = 0.05\n\n**post-hoc test**\n\nDunn's post-hoc test with Holm p-value adjustment\nBowls are different from packs, trays, and cups\n\nWe found a moderate ($\\eta^2$ = 0.12) difference in ratings between ramen styles (Kruskal-Wallis rank sum test, $\\chi^2$(3) = 15.7, p = 0.0013, $\\alpha$ = 0.05). Bowl-style ramen had a median rating of 4.25 stars, which tended to be more highly rated than pack (Dunn's post-hoc test: Holm adjusted p = 0.04, median rating = 3.75 stars), tray (Dunn's post-hoc test: Holm adjusted p = 0.04, median rating = 3.75 stars), or cup style ramen (Dunn's post-hoc test: Holm adjusted p = 0.0013, median rating = 3.5 stars).\n\n\n\n### 4. Captions\n\n#### Figure 1.\n\n**Figure 1. Crab carapace width differs across sites.** Small black points represent measurements of crab carapace widths at three sites: Zeke's Island National Estuarine Research Reserve (NERR), Virginia Coastal Reserve Long-Term Ecological Research (LTER) site, and Cape Cod. Large red points represent mean crab carapace width. Data originally from: Johnson, D. 2019. Fiddler crab body size in salt marshes from Florida to Massachusetts, USA at PIE and VCR LTER and NOAA NERR sites during summer 2016. ver 1. Environmental Data Initiative. https://doi.org/10.6073/pasta/4c27d2e778d3325d3830a5142e3839bb. Accessed via `lterdatasampler` package.\n\n#### Figure 2. \n\n**Figure 2. Histograms of crab carapace width.** Columns represent counts of individual crabs. Distributions of crab carapace width are represented in three panels: Zeke's Island NERR (left), Virginia Coastal Reserve LTER (center), and Cape Cod (right). Data originally from: Johnson, D. 2019. Fiddler crab body size in salt marshes from Florida to Massachusetts, USA at PIE and VCR LTER and NOAA NERR sites during summer 2016. ver 1. Environmental Data Initiative. https://doi.org/10.6073/pasta/4c27d2e778d3325d3830a5142e3839bb. Accessed via `lterdatasampler` package.  \n\nAlternative option if you have a figure made using the same dataset as a previous figure:  \n\n**Figure 2. Histograms of crab carapace widths.** Bars represent counts of crab sizes. Distributions are shown for three sites: Zeke's Island NERR (left), Virginia Coastal Reserve (center), and Cape Cod (right). Data source and access as in Figure 1. \n\n#### Figure 3.\n\n**Figure 3. Quantile-Quantile (QQ) plots of crab carapace width.** Points represent individual observations of crab carapace width. Lines represent reference line relating theoretical quantiles (x-axis) and sample quantiles (y-axis). Panels represent different sites: Zeke's Island NERR (left), Virginia Coastal Reserve LTER (center), and Cape Cod (right). Data originally from: Johnson, D. 2019. Fiddler crab body size in salt marshes from Florida to Massachusetts, USA at PIE and VCR LTER and NOAA NERR sites during summer 2016. ver 1. Environmental Data Initiative. https://doi.org/10.6073/pasta/4c27d2e778d3325d3830a5142e3839bb. Accessed via `lterdatasampler` package.  \n\nAlternative option if you have a figure made using the same dataset as a previous figure: \n\n**Figure 3. Quantile-quantile (QQ) plots of crab carapace widths.** Points represent individual crab carapace width measurements. Lines represent reference quantiles of sample (y-axis) and standard normal theoretical (x-axis) distributions. Panels, data source, and access as in Figure 2.\n\n#### Figure 4. \n\n**Figure 4. Median star ratings for Maruchan Ramen styles.** Points represent individual ratings for ramen types in each style (red: bowl, orange: pack, yellow: tray, green: cup). Boxplots represent median star ratings in each style.\n\n**END OF WORKSHOP 5**\n\n## Extra stuff\n\n### More applications of `stat_summary()`\n\n`stat_summary()` in the `ggplot2` package is a useful function to do quick summary visualizations within a plot.  \n\nIn class, we used `stat_summary()` to plot mean carapace widths at each site in red (see the \"Exploring the data\" section above).  \n\nYou can also use `stat_summary()` to visualize means and bars (representing standard deviation, standard error, confidence intervals, etc.).  \n\nFor example, here is a plot using `stat_summary()` to visualize means and standard errors:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = pie_crab_clean, # use the clean data set\n       mapping = aes(x = site_name, # x-axis\n                     y = size)) + # y-axis\n  # first layer: jitter (each point is an individual crab)\n  geom_jitter(height = 0, # don't jitter points vertically\n              width = 0.15) + # narrower jitter (easier to see)\n  # second layer: point representing mean\n  stat_summary(geom = \"pointrange\", # geometry being plotted\n               fun.data = mean_sdl, # function to calculate mean and sd (note new argument name)\n               color = \"red\", # color to make it easier to see\n               size = 1) + # larger point size\n  theme_minimal() + # cleaner plot theme\n  labs(x = \"Site name\",\n       y = \"Carapace width (mm)\",\n       caption = \"Mean \\U00B1 standard deviation\")\n```\n\n::: {.cell-output-display}\n![](workshop-05_2026-05-01_files/figure-html/mean and SD-1.png){width=672}\n:::\n:::\n\n\nAnd standard error:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = pie_crab_clean, # use the clean data set\n       mapping = aes(x = site_name, # x-axis\n                     y = size)) + # y-axis\n  # first layer: jitter (each point is an individual crab)\n  geom_jitter(height = 0, # don't jitter points vertically\n              width = 0.15) + # narrower jitter (easier to see)\n  # second layer: point representing mean\n  stat_summary(geom = \"pointrange\", # geometry being plotted\n               fun.data = mean_se, # function to calculate mean and SE (note new argument name)\n               color = \"red\", # color to make it easier to see\n               size = 1) + # larger point size\n  theme_minimal() + # cleaner plot theme\n  labs(x = \"Site name\",\n       y = \"Carapace width (mm)\",\n       caption = \"Mean \\U00B1 standard error\")\n```\n\n::: {.cell-output-display}\n![](workshop-05_2026-05-01_files/figure-html/mean and SE-1.png){width=672}\n:::\n:::\n\n\nAnd a 95% confidence interval:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = pie_crab_clean, # use the clean data set\n       mapping = aes(x = site_name, # x-axis\n                     y = size)) + # y-axis\n  # first layer: jitter (each point is an individual crab)\n  geom_jitter(height = 0, # don't jitter points vertically\n              width = 0.15) + # narrower jitter (easier to see)\n  # second layer: point representing mean\n  stat_summary(geom = \"pointrange\", # geometry being plotted\n               fun.data = mean_cl_normal, # function to calculate range for confidence interval (note new argument name)\n               color = \"red\", # color to make it easier to see\n               size = 1) + # larger point size\n  theme_minimal() + # cleaner plot theme\n  labs(x = \"Site name\",\n       y = \"Carapace width (mm)\",\n       caption = \"Means with 95% confidence interval\")\n```\n\n::: {.cell-output-display}\n![](workshop-05_2026-05-01_files/figure-html/mean and confidence interval-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "workshop-05_2026-05-01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}