---
title: "Choose your own assignment check-in (optional)"
date: 2025-05-21
categories: [choose your own assignment, optional]
---

# Description 

This is the first of two check ins for the choose your own assignment. This first check in is **optional**, and is an opportunity for you to start thinking about your assignment and get early feedback.  

:::{.callout-tip title="The more specific, the better!"}
You'll get more useful feedback if you provide specific responses to these questions (again, this is optional - do this if you're going to put in the time to be specific so that you can get good feedback!).  
:::

# Components

For this check-in, answer the following questions:

## If you are making a Quarto website

1. For your blog, what will your post with code and output be about? What will your post with a project description be about?   
2. What will you put on your "free" page? What visuals and sections will you have?  
3. What interactive widget(s) do you want to include in your website, and where will it go? What package will you use to make your widget?    

## If you are making an infographic

1. What is the main question you are asking of your data? What are the two sub-questions you will answer with your figures?  
1. What figures are you going to make? Describe the x- and y-axes and any `geom`s you would use.  

:::{.callout-tip title="Stuck on what kinds of figures to make?" collapse="true"}
Check out [From Data to Viz](https://www.data-to-viz.com/), a showcase of lots of kinds of figures (that you can make in R!).
:::

2. What visual components (e.g. color, shape) will you use to visually communicate those messages using your data?  
