---
title: "Homework 3"
editor: source
published-title: "Due date"
date: 2026-03-05
date-modified: last-modified
---

[Due on Thursday 5 March at 11:59 PM]{style="color: #79ACBD; font-size: 24px;"}

Read the instructions carefully and make sure you have all the components on the checklist.

## Part 1. Set up tasks

### GitHub steps  

1. Create a repository called `ENVS-193DS_homework-03` on GitHub. Make sure you provide a brief description, make it public, and initialize with a README.
2. Enable GitHub pages.

### RStudio/code/computer organization steps

3. Clone your repository to your computer.
4. Commit and push the `gitignore` and `.Rproj` files with the commit message: `initial commit`.
5. Create two new folders in your `ENVS-193DS_homework-03` folder: one for `code` and another for `data`.
6. Create a new Quarto or RMarkdown document for your homework submission in the `code` folder.
7. At the top of your document, include a link to _your GitHub repository_.
8. Download the soil salinity data to your `data` folder.
9. Do all of your set up (reading in packages/data) at the top of your .qmd file.
  At minimum, you should have the following packages read in: `tidyverse`, `here`, and either `gt` or `flextable`. Other packages you may find useful would be `janitor` or `readxl`.  
  Store the salinity data as an object called `salinity`.  
  Store your personal data as an object with whatever name you think makes sense.  

Throughout the course of doing your homework, make at least 10 commits and pushes to the remote.  

## Part 2. Problems

### Problem 1. Slough soil salinity

You are working at a restoration site where you are managing planting of California pickleweed (_Salicornia virginica_) along a brackish slough (i.e. there is a mixture of fresh water and salt water).   

You decide to measure plant growth for individual pickleweed plants by plucking an individual out of the ground and measuring the biomass (in g). You also measure salinity (as [electrical conductivity](https://www.fondriest.com/environmental-measurements/parameters/water-quality/conductivity-salinity-tds/) in units of millisiemens per centimeter, or mS/cm) at the location in which the individual was growing. Admittedly, this isn't a perfect study, but it's what you can do with the time and resources you have!

#### a. An appropriate test

In 1-3 sentences, name the appropriate test(s) to determine the **strength of the relationship between salinity and California pickleweed biomass** (hint: there are two). Describe the differences between the two tests.  

Be specific in your response to demonstrate your understanding of the variables in this question.  

:::{.callout-note title="Check your understanding!" collapse="true"}
Double check your understanding of the appropriate test. You are trying to understand the _strength of the relationship_ between California pickleweed biomass and soil salinity.
:::

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### b. Create a visualization

Create a visualization that would be appropriate for showing the relationship between soil salinity (in mS/cm) and California pickleweed biomass (in g).  

In addition to using the correct geometries, be sure to:  
- relabel the x- and y-axes and include units  
- use different colors from the `ggplot()` defaults  
- use a different theme from the `ggplot()` default  

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### c. Check your assumptions and run your test.  

In the order that is appropriate, create separate sections to:  
- check your assumptions  
- run your test  

In each section, write the code to check your assumptions and run your test as you see fit.  

In the section in which you check your assumptions, write 1-3 sentences describing:  

- which assumptions you checked    
- how you checked your assumptions  
- your assessment of your assumption checks  

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### d. Write about your methods and results.

In 1-3 sentences each, write about:  

- which test you used, and why  
- your interpretation of your test (along with the appropriate summary of the test in parentheses)  

:::{.callout-tip title="Double check your writing!" collapse="true"}

"We fail to reject the null hypothesis" or "We reject the null hypothesis" is not interpretation. This is a decision you made.  

Interpretation should include the _pattern_, _trend_, or _relationship_ that your test reveals to you about the biological system.  

Stuck? See lecture slides for examples.

:::

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### e. Write about the implications of your test.

You're working on a team of people at this restoration site who are also concerned about pickleweed planting. In 1-3 sentences, write what you would communicate to them about the results of this test and what it means for pickleweed planting success at your site.   

Be cognizant of your audience as you are writing: what would they need to know to take action?    

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### f. Double check your own work.  

In part a, you outlined _two_ potential tests to answer this question about the strength of the relationship between soil salinity and pickleweed biomass. In part c, you chose a test, checked your assumptions, and ran one.  

Try running the _other_ test you listed in part a. Include the annotated code and output.  

In 1-3 sentences, describe whether or not the two tests would have led you to make the same decision (about the null hypothesis) and interpret the results the same way (about the relationship between soil salinity and pickleweed biomass).  

In your description, be specific about the tests, their components, and their relation to the variables.

### Problem 2. Personal data

:::{.callout-note}
Before doing this problem, update your spreadsheet with your new observations. Save your data as a .csv or .xlsx in your `data` folder.
:::

#### a. Data summarizing

In 1-2 sentences, describe how you could summarize your data to compare your response variable between categories or groups of your choosing. For example, are you counting observations and comparing counts between groups? Are you taking the mean and comparing means between groups? Are you finding the maximum, minimum, range? Are you adding numbers together?  

Be sure to describe _why_ comparing between the groups you chose is informative. For example, you might calculate the mean number of steps you take to compare between week days, but what about those weekdays is _different_ (e.g. "I could calculate the mean number of steps I took to compare average step count between weekdays because I have more classes on Monday than on any other day of the week, so I think I walk more on Monday.")

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### b. Visualization

Using the summary you described in part a, **create a visualization of your data comparing your summarized response variable between groups**. If you are calculating a mean or median, show the underlying data in addition to your summary.  

Use colors in your figure (that are not the default ggplot settings).  

Make sure your axis labels are full, readable text (not just your column names).  

:::{.callout-note}
See [From Data to Viz](https://www.data-to-viz.com/) for new ideas for visualization.  
:::

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### c. Caption

Write a _caption_ for your figure.

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### d. Table presentation

Using `gt` or `flextable`, create a table with the same data summary that you describe in part a and visualized in part b. For example, if you described and visualized means, make a table with means. If you need to, round any numbers to one decimal point.  

Display the output.  

:::{.callout-tip}
Try _rendering_ your document here! Commit and push your changes, then find the url to your rendered output (if you get stuck, see the video on Canvas and/or the Git/GitHub basics page under the "Resources" tab).

Double check that your rendered document looks the way you would expect (e.g. tables all correct, text is formatted correctly). If not, go back and fix any issues or ask for help.
:::

### Problem 3. Affective visualization

In this problem, you will create an **affective visualization** using your personal data in preparation for workshops during weeks 9 and 10.  

In lecture, we talked about the three vertices of data visualization: 1) exploratory, 2) affective, and 3) communicative. We've done a lot of exploratory and communicative visualization, but have yet to think about affective visualization.  

When thinking of affective visualization, you can expand your ideas of what data visualization _could_ be. Some examples of affective visualizations include:  

- [Jill Pelto's paintings](https://www.jillpelto.com/gallery-1)
- [Lorraine Woodruff-Long's warming strips quilt ](https://www.instagram.com/p/C689Kybxget/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==)
- [Stefanie Posavec and Giorgia Lupi's Dear Data project](https://www.dear-data.com/all)
- [Environmental Graphiti](https://www.environmentalgraphiti.org/series-folder)  

See slides from the data visualization lecture for more ideas.

#### a. Describe in words what an affective visualization could look like for your personal data (3-5 sentences).

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### b. Create a sketch (on paper) of your idea. 

Include a photo of this sketch in your document.  

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.

Double check your rendered URL to make sure the photo of your sketch shows up.
:::

#### c. Make a draft of your visualization. 

Feel free to be creative with this! The one rule is that _you may not use any code to create your visualization_.    

Include a photo of your draft visualization in your submission.  

:::{.callout-note title="Make sure this is a _draft_!" collapse="true"}
You need to build in enough space or flexibility to edit your work after receiving feedback.  

For example, if you are making a sculpture, you could draw your form and create a mock up out of clay, paper, etc. but not start on the final piece.  

If you are making a digital drawing, you could draw an outline and start some color/tonal work without finishing your entire piece.
:::

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.

If you are including a photo, double check your rendered URL to make sure the photo of your draft shows up.
:::

#### d. Write an artist statement.

An artist statement gives the audience context to understand your work. For each of the following points, write 1-3 sentences to address:  

- the content of your piece (what are you showing?)
- the influences (what did techniques/artists/etc. did you find influential in creating your work?)
- the form of your work (watercolor, oil painting, etc.)
- your process (how did you create your work?)

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

:::{.callout-note title="This is prep for workshop during week 9!"}
During week 9, we will spend time providing peer review for your affective visualization. If you turn in your homework next Thursday, you will have a draft of your affective visualization and artist statement that is ready for peer review.  

_You will only earn a token for workshop attendance week 9 if you have a draft of your visualization and artist statement to share for peer review. No exceptions._
:::

### Problem 4. Statistical critique

At this point, you have seen and created a lot of figures for this class. Revisit the paper you chose for your critique and your homework 2, where you described figures or tables in the text. Address the following in full sentences (3-4 sentences each).  

**For this section of your homework, you will be evaluated on the logic, conciseness, and nuance of your critique.**  

#### a. Revisit and summarize

What are the statistical tests the authors are using to address their main research question? (Note: you have already written about this in homework 2! Find that text and provide it again here!)   

Insert the figure or table you described in Homework 2 here.  

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### b. Visual clarity

In 1-3 sentences, answer the question that best fits your paper.  

If you inserted a figure in Part a: How clearly did the authors _visually_ represent their statistics in figures? For example, are the x- and y-axes in a logical position? Do they show summary statistics (means and SE, for example) and/or model predictions, and if so, do they show the underlying data?  

If you inserted a table in Part b: How clearly does the table represent the data underlying tests?  

If you have neither: Critique another figure or table in the text for visual clarity (and insert a screenshot of that figure/table in your submission).

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### c. Aesthetic clarity

In 2-4 sentences, answer the question that best fits your paper.  

If you inserted a figure in Part a: How well did the authors handle "visual clutter"? How would you describe the the data:ink ratio?  

Remember that data:ink ratio is _not_ an actual ratio, but a way of thinking about the amount of visual clutter relative to the information being presented.  

If you inserted a table in Part b: How well did the authors handle "visual clutter"? Is there any bolding/italic text to draw your eye to specific numbers?   

If you have neither: Critique another figure or table in the text for aesthetic clarity (and insert a screenshot of that figure/table in your submission).

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### d. Recommendations (can be longer than 4 sentences)

What recommendations would you make to make the figure or table better? What would you take out, add, or change? Provide explanations/justifications for each of your recommendations.  

**Alternatively**, if they did not represent their statistics in a figure, what kind of figure would you recommend to them? Describe the x- and y-axes, with any geometries and aesthetics (colors, etc.). Provide enough explanation such that someone would be able to create the figure you describe in code. Provide explanations/justifications for the figure you would recommend.    

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::
  
## Assignment checklist

On Canvas, you will submit two links:  

1. the link to your GitHub repository  
2. the link to your rendered html  

Your GitHub repository should:  

- [ ] have an informative README with the following sections filled out: General information, Data and file information, and Rendered output. See the repos from workshop 7 and 8 for reference.  
- [ ] have separate folders for `code` and `data`. See workshops 7 and 8 for how to organize these folders.  
- [ ] show at least 10 commits/pushes with a descriptive, concise commit message (a few words describing what changes you are committing)  

Your rendered html should:  

- [ ] be organized and readable (for example: no messages, warnings, etc., text is formatted correctly with subscripts or mathematical notation where necessary, text and headers are clearly different)  
- [ ] include a floating table of contents (see code from workshop 7 and 8 for a reference in Quarto and RMarkdown)  

Additionally, your rendered html should include only the components listed below:  

- [ ] a set up chunk at the top of the document, where you have read in your packages and your data (and you should not have read in any packages or data anywhere else)  
- [ ] your name, the title, and the date  
- [ ] all code with annotations  

for Problem 1:  

- [ ] written responses for a
- [ ] code with annotations and output for b
- [ ] code with annotations and output with writing for c
- [ ] written responses for d
- [ ] written responses for e

for Problem 2:  

- [ ] written responses for a
- [ ] code with annotations and output for b
- [ ] written responses for c
- [ ] code with annotations and output for d

for Problem 3:  

- [ ] written responses for a
- [ ] image for b
- [ ] image and/or code with annotations and output for c
- [ ] written responses for d

for Problem 4:  

- [ ] written response and image for a
- [ ] written response for b
- [ ] written response for c
- [ ] written response for d

Lastly, check out the **rubric on Canvas**.  

## General formatting components

You will only receive full marks for annotations if you have meaningful comments for:  

- each line of visualization code and/or ggplot geom/theme call (not needed for each argument, though good to have)  
- each function in any piping operations  
- set up code to denote where packages and/or data are read in  
- each argument of a test call    

You will only receive full marks for readability if:  

- all messages/warnings are hidden  
- all code is contained in code chunks (double check line breaks in comments once you render your document)  
- all text is where it’s supposed to be (all components like headers, main text, superscripts/subscripts, etc. show up correctly)  
- code includes carriage returns, spaces, etc. to make pipe operations and arguments clear  
- code includes consistent spacing and indents

