---
title: "Choose your own assignment - Generative art"
editor: source
freeze: auto
published-title: "Due date"
date: 2024-06-10
date-modified: last-modified
---

[Due on Wednesday June 5 (week 10) at 11:59 PM]{style="color: #79ACBD; font-size: 24px;"}

## Description

We use R within RStudio for statistical analysis, but it has the capability of creating some very cool art pieces from what is essentially a random number generator. From Danielle Navarro, a self-described “data scientist, generative artist, and recovering academic”:

> This is what I think generative art really is. An automated process that takes garbage as input 
> and creates unpredictably delightful outputs – sometimes with a little helpful human oversight and 
> curation – is a generative art system. It is fundamentally a process of making something from 
> nothing. Art from the void. Treasure from trash. Signal from noise. You get the idea.

**By the end of this assignment, you’ll use numbers as a tool for creating art, and have created a few pieces of art on your own.** Additionally, you’ll be expected to annotate your code so that you know what each line is doing to understand how the randomness all fits together to create a final art piece.  

There are two routes for this assignment: **structured** and **unstructured**. In the structured route, you will work through a tutorial by Danielle Navarro, and create 3 art pieces using her materials. In the unstructured route, you will read and complete smaller tutorials by Meghan Harris, George Savva, and Jiwan Heo and create 3 art pieces synthesizing things you learned from each tutorial. You can decide which route to take based on your own comfort level and interest.

## Components

### Part 1. Context (structured and unstructured)

#### a. Read the last entry of the Art from Code workshop, “Wrap Up” 

Danielle's ["Wrap Up"](https://art-from-code.netlify.app/day-2/session-4/) gives good context for why this kind of exercise is useful. Have fun with it!

#### b. Read Nicola Rennie's "Best (artistic) practices in R"

Nicola's [guide](https://nrennie.rbind.io/blog/best-artistic-practices-in-r/) to artistic practices in R is useful for understanding how to structure, annotate, and share your code in the field of generative art.

#### c. Read Mine Cetinkaya-Rundel's Generative Art slides

[Mine's workshop](https://vizdata-f21.github.io/slides/22-generative-art/22-generative-art#1) gives a good background for some of the mechanics of creating art. There are no notes to go along with these slides, but you'll get a sense of what the code tends to look like.

### Part 2a. Workshop (structured only)

#### a. Get set up.

Fork the repo from the [original GitHub repository](https://github.com/rstudio-conf-2022/art-from-code) into your own account and download it into your computer.

#### b. Do the introductory exercises.

Read and complete exercises from “Get Started” ([link](https://art-from-code.netlify.app/day-1/session-1/)). Annotate your code to demonstrate that you know how it works.

#### c. Art of your choice: tricks

Choose one: spatial noise tricks, polygon tricks, shading tricks  
Complete all exercises. Again, annotate your code.  

#### d. Art of your choice: iteration, tiles, pixels  

Choose one: iterated function systems, tiles and tessellations, pixel filters.  
Complete all exercises. Again, annotate your code.

:::{.callout-note}
Note: these three lessons have less structured exercises - your job is to play around with the code provided and create something of your own, and not to follow written directions. Change stuff around and see what happens!
:::

#### e. Put it all together

Create 3 art pieces that combines elements of what you learned from parts b-d. For each piece, write an accompanying caption that includes:  

- The title of your piece  
- The date you created it  
- A 2-3 sentence description of your inspiration  
- A 2-3 sentence description of what _specific components_ from each part (b-d) you drew from to create the piece

### Part 2b. Tutorials (unstructured only)

#### a. Work through tutorials

Read and code along (i.e. copy/paste the code into your own document, annotate it, and run it) with the following tutorials:  

- Meghan Harris's [Thinking Outside the Grid](https://thetidytrekker.com/post/thinking-outside-the-grid/thinking-outside-the-grid)  
- one of George Savva's tutorials on [Mathematical Art and Creative Coding](https://georgemsavva.github.io/creativecoding/) (you choose the one you want to do)  
- one of Jiwan Heo's tutorials (again, you choose the one you want to do: [flow fields](https://jiwanheo.rbind.io/how-to-work-with-flow-fields-in-r/), [hypnotic squares](https://jiwanheo.rbind.io/hypnotic-squares-in-ggplot/), [Truchet tiles](https://jiwanheo.rbind.io/how-to-draw-truchet-tiles-with-ggplot2/), or [rotating lines](https://jiwanheo.rbind.io/how-to-rotate-lines-in-ggplot-to-make-art/))

#### b. Look at other people's generative art for inspiration

Some generative artists who work in R include:  

- [everyone featured in this gallery](https://ijeamaka-a.shinyapps.io/rtistry_gallery/) (look under the "Collections" tab for examples)  
- [Jacquie Tran](https://github.com/jacquietran/genuary_2022)  
- [Meghan Harris](https://thetidytrekker.com/rtistry)  
- [George Savva](https://github.com/georgemsavva/art-using-r)  
- [Jiwan Heo](https://github.com/jiwanheo/RecreationThursday)  
- [Danielle Navarro](https://art.djnavarro.net/gallery/)  
- [Thomas Lin Pedersen](https://thomaslinpedersen.art/)  
- [Antonio Sánchez Chinchón](https://fronkonstin.com/)

#### c. Put it all together

Create 3 art pieces that combine different components of Meghan, George, and Jiwan's tutorials. For each piece, write an accompanying caption that includes:  

- The title of your piece  
- The date you created it  
- A 2-3 sentence description of your inspiration  
- A 2-3 sentence description of what _specific components_ from each tutorial you drew from to create the piece

## Checklist

Your submission should include 

- A link to the GitHub repository where your materials for this specific assignment are (make sure it is public!)  
- A link to a rendered HTML document with navigation bar showing where each of the exercises/tutorials are  

Your rendered HTML document should include  

- your name, the title, and the date  
- annotated code and output for all tutorial activities
- annotated code and output for your three art pieces  
- written caption for all three art pieces  
- a 8-10 sentence summary at the end about your process: What was new for you? What was familiar? What did you learn? How did following the exercises/tutorials go for you?  

:::{.callout-note}
Note: you can do this by making your GitHub repository connect to GitHub pages. Ask if you are unsure about how to do this.
:::


