---
title: "Final part 2: personal data and statistical critique"
editor: source
freeze: auto
published-title: "Due date"
date: 2024-06-11
date-modified: last-modified
format:
  html:
    message: false
    warning: false
    toc: true
    toc-depth: 5
---

[Due on Tuesday June 11 at 11:59 PM]{style="color: #79ACBD; font-size: 24px;"}

:::{.callout-note}
This part was posted on Wednesday May 29th but **this is not a complete description of this part!**
:::

## Description

This is part 2 of your final. You must complete all components individually (i.e. not in a group). 

**If you worked in a group for part 1:** create a _new_ Quarto document titled `lastname-firstname_final-part-02` in the same GitHub repo that you used for part 1. Do problems 5-7.  

**If you worked alone for part 1:** continue in your Quarto document from part 1. Do problems 5-7.

This part of the final is open communication, open note, open internet, etc.  

## Problem 5. Affective and exploratory visualizations

### Skills you will demonstrate

In this problem, you will demonstrate your ability to **communicate about your visualization and give feedback to others.** You will also demonstrate your ability to **design and execute an appropriate statistical analysis for your data**.

### Problem

#### a. Sharing your affective visualization

This is a component you will complete in workshop on Thursday 6 June. **We will be taking attendance that day.**  

You will present your affective visualization and give feedback to 2-3 other classmates in class.

#### b. Comparing visualizations

In 5-10 sentences, compare and contrast your affective visualization from Homework 3/workshop, the exploratory visualization you made for Homework 2, and the communicative/exploratory visualization you made for the midterm.  

How are the visualizations different from each other? What similarities do you see between all your visualizations?  

## Problem 6. Data analysis

In this part of the final, you will analyze your data using the response and predictor variable(s) you have measured.  

### a. Response and predictor variables

List your response and predictor variable(s) and describe what kind of data (for example: continuous, categorical, ordinal, binary, etc.) each variable is.  

### b. Articulate a question

Write your "research question". For example, "what is the effect of ____ on ____?" or "what are the differences in ____ on ____?"

### c. Describe what kind of test or model you would use

Describe why that test or model would be appropriate given your response and predictor variables.

:::{.callout-note}
You have to use one of the tests/models we learned about in this class. Make sure your response variables are appropriate for those tests!
:::

### d. Follow-ups

Describe what kind of effect size, post-hoc, correlation coefficient, prediction calculation, or any other follow-up you would do and why.

### e. Analyze your data

Include the code and output for all parts: assumption checks/diagnostics, the code itself, follow-up tests.  

### f. Visualize your results 

Making sure that your visualization matches up with the test you ran in part e, visualize your results with the underlying data and 95% confidence intervals and/or standard error.  

Finalize your figure, get rid of visual clutter, and use colors/shapes/other aesthetics as appropriate. You will be graded on the aesthetic presentation of your analysis and how well it matches up with the statistical test you ran in part e.

### g. Write a caption for your visualization. 

### h. Write a methods section.

Describe  
- what variables you collected  
- how you collected your data  

### i. Write a results section.

Describe  
- what you found (with the appropriate summary of the statistical tests)  
- your interpretation of your results  

Turn in your raw data as a .csv along with your final.

## Problem 7. Statistical critique

### a. Find the methods

Revisit the methods of the paper you chose. If there are multiple methods, _choose one_ that is in the list of methods we cover in this class:  

- t-test  
- Analysis of variance (ANOVA)  
- Mann-Whitney U  
- Kruskal-Wallis  
- Wilcoxon rank sum  
- Linear model or linear regression  
- Spearman correlation  
- Pearson correlation  
- logistic regression  
- Generalized linear mixed effect model  

Paste the text of the methods into your document.  

### b. Method description

What is the response variable and what is the predictor? If a mixed effect model, what are the random effects?     

### c. Assumption  

What assumptions have to be met for using this method? If a generalized linear mixed effect model, what type of error distribution is appropriate for the response variable?  

### d. Critique

Was this an appropriate method for the authors to use? Why or why not? If not, what would be a more appropriate method to use and why?  

