---
title: "Homework 3"
editor: source
published-title: "Due date"
date: 2026-03-05
date-modified: last-modified
format: 
  html:
    toc-depth: 5
---

[Due on Thursday 5 March at 11:59 PM]{style="color: #79ACBD; font-size: 24px;"}

Read the instructions carefully and make sure you have all the components on the checklist.

## Part 1. Set up tasks

### GitHub steps  

1. Create a repository called `ENVS-193DS_homework-03` on GitHub. Make sure you provide a brief description, make it public, and initialize with a README.
2. Enable GitHub pages.

### RStudio/code/computer organization steps

3. Clone your repository to your computer.
4. Commit and push the `gitignore` and `.Rproj` files with the commit message: `initial commit`.
5. Create two new folders in your `ENVS-193DS_homework-03` folder: one for `code` and another for `data`.
6. Create a new Quarto or RMarkdown document for your homework submission in the `code` folder.
7. At the top of your document, include a link to _your GitHub repository_ as a hyperlink.
8. Download the soil salinity data to your `data` folder.
9. Do all of your set up (reading in packages/data) at the top of your .qmd file.  
  - At minimum, you should have the following packages read in: `tidyverse` and `here`.  
  - Other packages you may find useful would be `janitor` or `readxl`.  
  - Store the salinity data as an object called `salinity`.  
  - Store your personal data as an object with whatever name you think makes sense.  

Throughout the course of doing your homework, make at least 10 commits and pushes to the remote.  

## Part 2. Problems

### Problem 1. Slough soil salinity

You are working at a restoration site where you are managing planting of California pickleweed (_Salicornia virginica_) along a brackish slough (i.e. there is a mixture of fresh water and salt water).   

You decide to measure plant growth for individual pickleweed plants by plucking an individual out of the ground and measuring the biomass (in g). You also measure salinity (as [electrical conductivity](https://www.fondriest.com/environmental-measurements/parameters/water-quality/conductivity-salinity-tds/) in units of millisiemens per centimeter, or mS/cm) at the location in which the individual was growing. Admittedly, this isn't a perfect study, but it's what you can do with the time and resources you have!

#### a. An appropriate test

In 1-3 sentences, name the appropriate test(s) to determine the **strength of the relationship between salinity and California pickleweed biomass** (hint: there are two). Describe the differences between the two tests.  

Be specific in your response to demonstrate your understanding of the variables in this question.  

:::{.callout-note title="Check your understanding!" collapse="true"}
Double check your understanding of the appropriate test. You are trying to understand the _strength of the relationship_ between California pickleweed biomass and soil salinity.
:::

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### b. Create a visualization

Create a visualization that would be appropriate for showing the relationship between soil salinity (in mS/cm) and California pickleweed biomass (in g).  

In addition to using the correct geometries, be sure to:  

- relabel the x- and y-axes and include units  
- use different colors from the `ggplot()` defaults  
- use a different theme from the `ggplot()` default  

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### c. Check your assumptions and run your test

In the order that is appropriate, create separate sections using subheaders to:  

- check your assumptions  
- run your test  

In the section in which you check your assumptions, include any code and outputs you think are relevant. (Note: you may have already written code and shown its outputs to check your assumptions in part 1b, depending on the test you decide to go with!). Additionally, write 1-3 sentences describing:  

- which assumptions you checked    
- how you checked your assumptions  
- your assessment of your assumption checks  

In the section in which you run your test, be sure your code is annotated and the outputs are visible.  

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### d. Write about your results

In 1-3 sentences each, write about:  

- which test you used, and why  
- your interpretation of your test (along with the appropriate summary of the test in parentheses)  

:::{.callout-note title="Double check your writing!" collapse="true"}

"We fail to reject the null hypothesis" or "We reject the null hypothesis" is not interpretation. This is a decision you made.  

Interpretation should include the _pattern_, _trend_, or _relationship_ that your test reveals to you about the biological system.  

Stuck? See lecture slides for examples.

:::

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### e. Write about the implications of your test.

You're working on a team of people at this restoration site who are also concerned about pickleweed planting. In 2-3 sentences, write what you would communicate to them about the results of this test and what it means for pickleweed planting success at your site.   

Be cognizant of your audience as you are writing: what would they need to know to take action?    

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### f. Double check your own work.  

In part a, you outlined _two_ potential tests to answer this question about the strength of the relationship between soil salinity and pickleweed biomass. In part c, you chose a test, checked your assumptions, and ran one.  

Try running the _other_ test you listed in part a. Include the annotated code and output.  

In 1-3 sentences, describe whether or not the two tests would have led you to make the same decision (about the null hypothesis) and interpret the results the same way (about the relationship between soil salinity and pickleweed biomass).  

In your description, be specific about the tests, their components, and their relation to the variables.

### Problem 2. Personal data

:::{.callout-note title="Before doing this problem..." collapse="true"}
Before doing this problem, update your spreadsheet with your new observations. Save your data as a .csv or .xlsx in your `data` folder.
:::

#### a. Updating your visualizations

Revisit the visualizations you created in homework 2.  

Provide the code and output for _updated_ plots with your most recent observations.  

**Note:** if you think that a _different_ plot type or _different_ variables would be more interesting to visualize, then change your plots!  

You should have the annotated code and output for _two_ plots.  

For each plot, be sure to:  

- label the x- and y- axes and provide units
- include the date of the most recent observation as a _subtitle_
- clean up the visual clutter (e.g. grids, backgrounds)
- use colors that are different from the `ggplot()` defaults

:::{.callout-note title="Reuse your code!" collapse="true"}
If you are happy with the plots you made for homework 2 (and you received full marks on those plots, or your revised plots), then reuse your code! You don't have to write completely new code for plots that you've already made.
:::

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### b. Captions

In text (not in code), write captions for _both_ your figures.

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

:::{.callout-tip}
Try _rendering_ your document here! Commit and push your changes, then find the url to your rendered output (if you get stuck, see the video on Canvas and/or the Git/GitHub basics page under the "Resources" tab).

Double check that your rendered document looks the way you would expect (e.g. figures all correct, text is formatted correctly). If not, go back and fix any issues or ask for help.
:::

### Problem 3. Affective visualization

In this problem, you will create an **affective visualization** using your personal data in preparation for workshops during weeks 9 and 10.  

In lecture, we talked about the three vertices of data visualization: 1) exploratory, 2) affective, and 3) communicative. We've done a lot of exploratory and communicative visualization, but have yet to think about affective visualization.  

When thinking of affective visualization, you can expand your ideas of what data visualization _could_ be. Some examples of affective visualizations include:  

- [Jill Pelto's paintings](https://www.jillpelto.com/gallery-1)
- [Lorraine Woodruff-Long's warming strips quilt ](https://www.instagram.com/p/C689Kybxget/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==)
- [Stefanie Posavec and Giorgia Lupi's Dear Data project](https://www.dear-data.com/all)
- [Environmental Graphiti](https://www.environmentalgraphiti.org/all-series)  

See slides from the data visualization lecture for more ideas.

#### a. Describe in words what an affective visualization could look like for your personal data (3-5 sentences).

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### b. Create a sketch (on paper) of your idea. 

Include a photo of this sketch in your document.  

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.

Double check your rendered URL to make sure the photo of your sketch shows up.
:::

#### c. Make a draft of your visualization. 

Feel free to be creative with this! The one rule is that _you may not use any code to create your visualization_.    

Include a photo of your draft visualization in your submission.  

:::{.callout-note title="Make sure this is a _draft_!" collapse="true"}
You need to build in enough space or flexibility to edit your work after receiving feedback.  

For example, if you are making a sculpture, you could draw your form and create a mock up out of clay, paper, etc. but not start on the final piece.  

If you are making a digital drawing, you could draw an outline and start some color/tonal work without finishing your entire piece.
:::

:::{.callout-note title="You will need to have a _final_ version by workshop week 10. Plan accordingly!" collapse="true"}

The timeline for your affective visualization is as follows:  

- week 8-9: brainstorm, draft  
- week 9: peer feedback in workshop  
- week 10: present final version in workshop  

That means you will have _one_ week between getting feedback and incorporating it into your final version. Plan accordingly.
:::

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.

If you are including a photo, double check your rendered URL to make sure the photo of your draft shows up.
:::

#### d. Write an artist statement.

An artist statement gives the audience context to understand your work. For each of the following points, write 1-3 sentences to address:  

- the content of your piece (what are you showing?)
- the influences (what did techniques/artists/etc. did you find influential in creating your work?)
- the form of your work (watercolor, oil painting, crocheted object, etc.)
- your process (how did you create your work?)

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### e. Prep your materials to share in class.

In workshop week 9, you will present your draft and providing feedback on your learning partners' drafts.  

To prepare for this, create a presentation on Google slides with:  

- one slide on:  
  - your project's central question and why you wanted to ask that question  
  - the main variables (one response and one predictor) that you are measuring and how you think your predictor variable influences your response variable    
- one slide on:  
  - the other variables you measured and how each of them relate to your main variable  
- one slide depicting one of the two visualizations you made for homework 2, updated to include your new observations  
- one slide on:  
  - your idea for your affective visualization  
  - what inspiration you took from which sources  
  - the medium in which you will create your affective visualization
- one slide on:
  - your draft
  - your anticipated artist statement
  - the feedback that would be most helpful to you at this particular point (e.g. "I need help figuring out what other variables to depict and how", "I think these colors work but I'm not sure - are there better ones?")  
  
**In your homework submission, include a "View" link to your slides as a _hyperlink_.**
  
:::{.callout-note title="Go look at your previous homework assignments to get this information!"}

You already have thoughts down on most of the points you should be hitting in your slides from your homework assignments. Go back and find that information so that you don't have to write completely new text!
:::

:::{.callout-note title="This is prep for workshop during week 9!"}
During week 9, we will spend time providing peer review for your affective visualization. If you turn in your homework next Thursday, you will have created your slides.  

_You will only earn a token for workshop attendance week 9 if you have slides ready to share. No exceptions._
:::

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

### Problem 4. Statistical critique

At this point, you have seen and created a lot of figures for this class. Revisit the paper you chose for your critique and your homework 2, where you described figures or tables in the text. Address the following in full sentences (3-4 sentences each).  

**For this section of your homework, you will be evaluated on the logic, conciseness, and nuance of your critique.**  

#### a. Revisit and summarize

What are the statistical tests the authors are using to address their main research question? (Note: you have already written about this in homework 2! Find that text and provide it again here!)   

Insert the figure or table you described in Homework 2 here.  

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### b. Visual clarity

In 2-4 sentences, answer the question that best fits your paper.  

If you inserted a figure in Part a: How clearly did the authors _visually_ represent their statistics in figures? For example, are the x- and y-axes in a logical position? Do they show summary statistics (means and SE, for example) and/or model predictions, and if so, do they show the underlying data?  

If you inserted a table in Part b: How clearly does the table represent the data underlying tests?  

If you have neither: Critique another figure or table in the text for visual clarity (and insert a screenshot of that figure/table in your submission).

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### c. Aesthetic clarity

In 2-4 sentences, answer the question that best fits your paper.  

If you inserted a figure in Part a: How well did the authors handle "visual clutter"? How would you describe the the data:ink ratio?  

If you inserted a table in Part b: How well did the authors handle "visual clutter"? Is there any bolding/italic text to draw your eye to specific numbers?   

If you have neither: Critique another figure or table in the text for aesthetic clarity (and insert a screenshot of that figure/table in your submission).  

Remember that data:ink ratio is _not_ an actual ratio, but a way of thinking about the amount of visual clutter relative to the information being presented.  

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::

#### d. Recommendations

In 2-4 sentences, outline what recommendations would you make to make the figure or table better. What would you take out, add, or change? Provide explanations/justifications for each of your recommendations.  

**Alternatively**, if the authors did not represent their statistics in a figure, what kind of figure would you recommend to them? Describe the x- and y-axes, with any geometries and aesthetics (colors, etc.). Provide enough explanation such that someone would be able to create the figure you describe in code. Provide explanations/justifications for the figure you would recommend.    

:::{.callout-tip}
Try committing and pushing your changes here! Write an _informative_ commit message.
:::
  
## Assignment checklist

On Canvas, you will submit two links:  

1. the link to your GitHub repository  
2. the link to your rendered html  

Your GitHub repository should:  

- [ ] have an informative README with the following sections filled out: General information, Data and file information, and Rendered output. See the repos from workshop 7 and 8 for reference.  
- [ ] have separate folders for `code` and `data`. See workshops 7 and 8 for how to organize these folders.  
- [ ] show at least 10 commits/pushes with a descriptive, concise commit message (a few words describing what changes you are committing)  

Your rendered html should:  

- [ ] be organized and readable (for example: no messages, warnings, etc., text is formatted correctly with subscripts or mathematical notation where necessary, text and headers are clearly different)  
- [ ] include a floating table of contents (see code from workshop 7 and 8 for a reference in the YAML at the top of the `.qmd` file)  

Additionally, your rendered html should include only the components listed below:  

- [ ] a set up chunk at the top of the document, where you have read in your packages and your data (and you should not have read in any packages or data anywhere else)  
- [ ] your name, the title, and the date  
- [ ] all code with annotations  

for Problem 1:  

- [ ] written responses for a
- [ ] annotated code and output for b
- [ ] annotated code, its output, and written responses for c
- [ ] written responses for d
- [ ] annotated code, its output, and written responses for e

for Problem 2:  

- [ ] written responses for a
- [ ] annotated code and output for b
- [ ] written responses for c
- [ ] annotated code and output for d

for Problem 3:  

- [ ] written responses for a
- [ ] image for b
- [ ] image for c
- [ ] written responses for d
- [ ] link to your slides for e (make sure you share the link as a "View" link)

for Problem 4:  

- [ ] written response and image for a
- [ ] written response for b
- [ ] written response for c
- [ ] written response for d

Lastly, check out the **rubric on Canvas**.  

## General formatting components

You will only receive full marks for annotations if you have meaningful comments for:  

- each line of visualization code and/or ggplot geom/theme call (not needed for each argument, though good to have)  
- each function in any piping operations  
- set up code to denote where packages and/or data are read in  
- each argument of a test call    

You will only receive full marks for readability if:  

- all messages/warnings are hidden  
- all code is contained in code chunks (double check line breaks in comments once you render your document)  
- all text is where it’s supposed to be (all components like headers, main text, superscripts/subscripts, etc. show up correctly)  
- code includes carriage returns, spaces, etc. to make pipe operations and arguments clear  
- code includes consistent spacing and indents

