---
title: "Problem set 3"
editor: source
published-title: "Due date"
date: 2026-05-07
date-modified: last-modified
categories: [problem set]
---

## Set up

You may turn in your problem set in .pdf or .docx format. This can be generated using code in a .qmd or .Rmd file, or a regular Word or Google Docs document.    

A **complete** problem set will include:  

- your name and the date
- the title ("Problem set 3")
- answers to each problem component in the listed order (e.g. 1a, 1b, 1c, and so on)
- all answers _visible_ with no missing components

Additionally, a **complete** problem set _must_ be accompanied by a Generative AI statement of use (linked in the portal on Canvas).  

Any problem set missing these components will be marked **incomplete**. See the syllabus for information on how missing problem sets) factor into your course grade.

# Problems

## Problem 1. Specific leaf area

Specific leaf area (SLA) is a measurement of leaf surface area (in mm^2^) divided by dry mass (in g) that indicates how a plant individual retains and uses resources. A high value for SLA represents a "fast" resource use strategy, while a low value for SLA represents a "slow" resource use strategy.

Specific leaf area can differ amongst species. You ask how SLA (measured as mm^2^/g) differs between coast live oaks (_Quercus agrifolia_, n = 13) and valley oaks (_Quercus lobata_, n = 11).

If you wanted to compare the SLA between these species based on the samples you collected,

a. Would you want to compare means or medians? Why?
b. Which test(s) could you use for either means or medians? 
c. What assumptions would you have to check for either test?
d. How would you check them (i.e. using what tools)? 
e. What other values could you calculate? Be specific with a name and what it would tell you.

## Problem 2. Root:shoot ratio

Root to shoot ratio, calculated as the dry mass of aboveground biomass (in g) divided by the dry mass of belowground biomass (in g) is another morphological characteristic that reveals a plant's life history strategy. Plants from nutrient-poor areas tend to have lower root:shoot ratios because they tend to invest more resources in growing roots (to find more nutrients).

If you wanted to compare the root:shoot ratio of valley oak seedlings growing in nutrient-poor (n = 15), intermediate (n = 12), and nutrient-rich soils (n = 16), 

a. Would you want to compare means or medians? Why?
b. Which test(s) could you use for either means or medians?
c. What assumptions would you have to check for either test?
d. How would you check them (i.e. using what tools)?
e. What other values could you calculate? Be specific with a name and what it would tell you.
f. What other test(s) could you run after the test(s) you listed in part b? Be specific with a name and what it would tell you.








