---
title: "Reflection 3"
editor: source
freeze: auto
published-title: "Due date"
date: 2026-03-17
date-modified: last-modified
---

[Due on Tuesday 17 March (finals week) at 11:59 PM]{style="color: #79ACBD; font-size: 24px;"}

In this assignment, you’ll reflect on your own progress in the course now that the quarter is over.  

Reread your responses to reflections 1 and 2. Then, address the following questions in 2-4 sentences each.

## Components

1. Assessing your progress throughout the quarter, did you reach your learning goals for the class or any modified goals from Reflection 2? If you did accomplish your goals, how do you think you did it (i.e. by practicing, making notes for yourself, etc.)?  

2. What tools (e.g, ChatGPT, Claude, Google) outside of course materials did you use to find help? How well did these tools work for you? Did these tools improve in helpfulness through time, or did they stay the same?  

3. What study aids (e.g. cheat sheets, notes) did you make for yourself, if any? Why do you think they were helpful? If you did not make study aids, what course materials (e.g. slides, workshop summaries, keys, videos) were useful to you?  

4. The grading scheme in this class was a trial run of a scoring system that was freed from point values. What about this scheme worked for your own personal learning? What didn't work?  

5. What are some [“transferable skills”](https://www.coursera.org/articles/transferable-skills) that you developed in this course, and how might you apply them to other courses at UCSB or jobs in the future?  

6. Now that you’ve finished up course material, what are you proudest of regarding what you’ve learned or accomplished in the course overall? Why?  

## Checklist

Your reflection should:  

- address at least the 6 topics above (but please feel free to expand on these if you would like)  
- be uploaded to Canvas by 11:59 PM on Tuesday 17 March in PDF format






