---
title: "Reflection 1"
editor: source
freeze: auto
published-title: "Due date"
date: 2024-04-10
date-modified: last-modified
---

[Due on Wednesday April 10 (Week 2) at 11:59 PM]{style="color: #79ACBD; font-size: 24px;"}

In this assignment, you’ll introduce yourself and come up with a plan for what you’d like to get out of the class and roughly outline what you’d like to accomplish over the course of the quarter. You’ll continue visiting the goals you set for yourself in this assignment throughout the quarter, so it’s worth it to be as clear and specific as you can.  

## Components

### A brief introduction
- your name  
- your major
- your year  
- pronouns (only if you feel comfortable sharing)  

### Some questions about school and life
- Why are you taking this class?  
- What do you hope to get out of this class?  
- If you have a career in mind, how does this course apply to your future career, if at all?  
- What do you wish your instructors knew about you, but don’t?

### Some questions about the way you like to learn
- What kinds of assignments, skills, or behaviors have you felt most comfortable with/enjoy from past classes? Why do you enjoy them?  
- How confident do you feel in your statistics skills (however you want to interpret that)? Why?  
- How confident do you feel in your coding skills (again, however you want to interpret that)? Why?  
- What have you struggled with in the past in math or statistics courses? Why?  
- Of the courses you’re taking this quarter, which do you expect to be the most challenging? Most demanding?  
- Which learning goals from the syllabus are you most excited about?  
- What other learning goals do you have for the course?  
- Most importantly, how do you plan on accomplishing your learning goals for this course?

:::{.callout-note}
Be specific here! Instead of writing, “I will complete homework assignments” or “I will study”,  you can make these more specific strategies: “I will use the homework assignments as opportunities for practice. I will communicate with classmates for help after trying...”
:::

### Checklist
Your reflection should include  

- your name, major, and year (if you feel comfortable, please also include the pronouns you want to be used)  
- 1-2 sentences in response to each point (Note: you can copy/paste the questions into a document and fill them out like a form!)



