---
title: "Reflection 2"
editor: source
freeze: auto
published-title: "Due date"
date: 2026-02-19
date-modified: last-modified
---

[Due on Thursday 19 February (week 7) at 11:59 PM]{style="color: #79ACBD; font-size: 24px;"}

In this assignment, you’ll reflect on your own progress in the course up until this point.  

Reread your responses to reflection 1 and the feedback on Canvas. Then, address the following questions in 2-3 sentences each.

## Components

1. How have you progressed towards your learning goals for this course? Specifically, how do you know that you've made progress?  

2. What skills are you proud of developing and/or building on in the last 7 weeks?  

3. How confident do you feel about your coding skills now, compared to how you felt at the beginning of the quarter? What has changed (or not)?  

4. How confident do you feel about your statistics skills now, compared to the beginning of the quarter? What has changed (or not)?  

5. How have your learning goals changed? Have they stayed the same?  

6. Have you learned anything into which you want to dive more deeply? Have you done so? If yes, what did you learn?  

## Checklist

Your reflection should:  

- address at least the 6 topics above (but feel free to expand on these if you would like)  
- be uploaded to Canvas by 11:59 PM on Thursday 19 February in PDF format


