---
title: "Coding workshop: Week 7"
subtitle: "using Git and GitHub"
categories: [git, github, tidyverse, here, ggeffects, flextable, here, str, glimpse, class, lm, ggpredict, ggsave, cor.test, plot, geom_ribbon, geom_line, read_csv, ggplot, geom_point, github, forking]
---

## 1. Summary

### Packages

- `tidyverse`  
- `here`  
- `ggeffects`  
- `flextable`  

### Operations

#### New functions

- organize file paths using `here()`  
- look at data using `str()`, `glimpse()`, and `class()`  
- construct a linear model using `lm()`  
- visualize model predictions using `ggpredict()`  
- saving image using `ggsave()`  
- calculating correlation using `cor.test()`  
- plot model diagnostics using `plot()`  
- plot model 95% CI using `geom_ribbon()`  
- plot model predictions using `geom_line()`

#### Review

- read in data using `read_csv()`  
- visualize data using `ggplot()`  
- create scatterplot using `geom_point()`  

### Data sources

The data from this workshop comes from two sources:  

1. Hamilton et al. 2022. "Integrated multi-trophic aquaculture mitigates the effects of ocean acidification: Seaweeds raise system pH and improve growth of juvenile abalone." https://doi.org/10.1016/j.aquaculture.2022.738571  

2. Ramirez, A. 2024. Sonadora elevational plots: long-term monitoring of air temperature ver 877108. Environmental Data Initiative. https://doi.org/10.6073/pasta/6b66eecae3092d8f2340b5132dec38ab (Accessed 2025-05-14).

## 2. Code

All code is in [this repository](https://github.com/fjoyce/ENVS-193DS_workshop-07).  

All GitHub/Git steps are in [this guide](https://spring-2025.envs-193ds.com/resources/using-github). Videos to accompany this guide are on Canvas.  

