{
  "hash": "60a44dc7de7ac01b2f4ba703a52ae3de",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Coding workshop: Week 2\"\nsubtitle: \"using Quarto, data wrangling, visualizing uncertainty\"\ndate: 2026-04-10\ncategories: [tidyverse, janitor, read_csv, pipe operators, '|>', clean_names, mutate, select, pivot_longer, group_by, summarize, sd, qt, ggplot, geom_histogram, geom_point, geom_errorbar, geom_pointrange, geom_line]\n---\n\n\n[Workshop date: Friday 10 April]{style=\"color: #79ACBD; font-size: 24px;\"}\n\n## 1. Summary\n\n### Packages\n\n- `tidyverse`\n- `janitor`  \n\n### Operations\n\n- read in data using `read_csv()`\n- chain functions together using ` |> `\n- clean column names using `clean_names()`\n- create new columns using `mutate()`\n- select columns using `select()`\n- make data frame longer using `pivot_longer()`\n- group data using `group_by()`\n- undo grouping using `ungroup()`\n- summarize data using `summarize()`\n- calculate standard deviation using `sd()`\n- calculate t-values using `qt()`\n- visualize data using `ggplot()`\n- create histograms using `geom_histogram()`\n- visualize means and raw data using `geom_point()`\n- visualize standard deviation, standard error, and confidence intervals using `geom_errorbar()` and `geom_pointrange()`\n- visualize trends through time using `geom_point()` and `geom_line()`\n\n### Data source\n\nThis week, we'll work with data on seafood production types (aquaculture or capture). This workshop's data comes from [Tidy Tuesday 2021-10-12](https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-10-12/readme.md), which was from [OurWorldinData.org](https://ourworldindata.org/fish-and-overfishing).\n\n## 2. Code\n\n### 1. Set up\n\nThis section of code includes reading in the packages you'll need: `tidyverse` and `janitor`.  \n\nYou'll also read in the data using `read_csv()` and store the data in an object called `production`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load in packages\nlibrary(tidyverse)\nlibrary(janitor)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in data\nproduction <- read_csv(\"captured_vs_farmed.csv\")\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n:::{.callout-note}\nRemember to _look_ at the data before working with it! You can use `View(production)` in the console, or click on the `production` object in the Environment tab in the top right.\n:::\n\n**Before you start:** think about what the differences might be between aquaculture and capture production in the context of fisheries. Which production type do you think would produce _more_ seafood?  \n\n**insert your best guess here**\n\n### 2. Cleaning up\n\nThe data comes in what's called \"wide format\", meaning that each row represents multiple observations. For example, the first row contains the production from Afghanistan (country code AFG) in 1969 for aquaculture and capture production.  \n\nWe want to convert the data into \"long format\" so that it's easier to work with. A dataset is in long format if each row represents an observation.  \n\nIn this chunk of code, we'll:  \n\n1. clean the column names using `clean_names()`  \n2. filter to only include the \"entity\" we want using `filter()`  \n3. select the columns of interest using `select()`  \n4. make the data frame longer using `pivot_longer()`  \n5. manipulate the `type` column to change the long names (e.g. `aquaculture_production_metric_tons`) to short names (e.g. `aquaculture`) using `mutate()` and `case_when()`  \n6. use `mutate()` to create a new column called `metric_tons_mil`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# creating new object from production \nproduction_clean <- production |> \n  # clean column names\n  clean_names() |> \n  # filter to only include observations from the US\n  filter(entity == \"United States\") |>\n  # select columns of interest \n  select(year, \n         aquaculture_production_metric_tons, \n         capture_fisheries_production_metric_tons) |>\n  # choose columns to pivot\n  pivot_longer(cols = aquaculture_production_metric_tons:\n                 capture_fisheries_production_metric_tons, \n               # column with fishery type should be named \"type\"\n               names_to = \"type\", \n               # column with catch amount should be named \"catch_metric_tons\"\n               values_to = \"catch_metric_tons\") |> \n  # mutate the existing type column\n  mutate(type = case_when( \n    # fill in aquaculture to replace aquaculture_production_metric_tons\n    type == \"aquaculture_production_metric_tons\" ~ \"aquaculture\", \n    # fill in capture to replace capture_fisheries_production_metric_tons\n    type == \"capture_fisheries_production_metric_tons\" ~ \"capture\" \n  )) |> \n  # convert catch in metric tons to millions\n  mutate(metric_tons_mil = catch_metric_tons/1000000) \n```\n:::\n\n\n### 3. Making a boxplot/jitter plot\n\nLast week in workshop, we made a boxplot. The boxplot shows useful summary statistics (displays the central tendency and spread), while the jitter plot shows the actual observations (in this case, each point is the catch for a fishery in a given year). One way to display the underlying data is to combine a boxplot with a jitter plot. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# start with the production_clean data frame\nggplot(data = production_clean, \n       # x-axis should be type of production\n       # y-axis should be metric tons of production (in millions)\n       # coloring by production type\n       mapping = aes(x = type, \n                     y = metric_tons_mil, \n                     color = type)) + \n  # first layer: boxplot\n  geom_boxplot() + \n  # second layer: jitter\n  geom_jitter(width = 0.2, # making the points jitter horizontally\n              height = 0) + # making sure points don't jitter vertically\n  # relabelling x- and y-axes\n  labs(x = \"Type\", \n       y = \"Metric tons of production (in millions)\") \n```\n\n::: {.cell-output-display}\n![](workshop-02_2026-04-10_files/figure-html/boxplot-and-jitter-1.png){width=672}\n:::\n:::\n\n\nOn average, a) which type of production produces more fish, and b) what components of the plot are you using to come up with your answer?  \n\n**a) Capture production, because b) the median of the boxplot is way higher than the median for aquaculture**\n\n### 4. Making a histogram\n\nThis chunk of code creates a histogram. Note that for a histogram, you only need to fill in the `aes()` argument for the x-axis (`x`), not the y-axis. This is because `ggplot()` counts the number of observations in each bin for you.  \n\nWithin the `geom_histogram()` call, you'll need to tell R what number of bins you want using the `bins` argument. In this case (using the Rice Rule to determine the appropriate number of bins), we'll use 10 bins.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = production_clean,\n       # x-axis should be metric_tons_mil\n       # fill by production type (aquaculture or capture)\n       mapping = aes(x = metric_tons_mil,\n                     fill = type)) + \n  # first layer: histogram\n  geom_histogram(bins = 10, # set the number of bins based on Rice Rule\n                 color = \"black\") # make the border of the columns black\n```\n\n::: {.cell-output-display}\n![](workshop-02_2026-04-10_files/figure-html/creating-histogram-1.png){width=672}\n:::\n:::\n\n\nCan you tell from looking at the histogram which production type tends to produce more fish? Why or why not?\n\n**Yes. There are no observations for aquaculture at high catch (in millions); most of the observations for aquaculture are lower than 1 million tons, while capture production ranges up to 6 million tons.**\n\n### 5. Visualizing spread, uncertainty, and confidence\n\n#### a. Calculations\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a new object from clean data frame\nproduction_summary <- production_clean |> \n  # group by production type\n  group_by(type) |> \n  # calculate values for each production type\n  summarize(\n    mean = mean(metric_tons_mil), # mean\n    n = length(metric_tons_mil), # number of observations (n)\n    df = n - 1, # degrees of freedom\n    sd = sd(metric_tons_mil), # standard deviation\n    se = sd/sqrt(n), # standard error\n    tval = qt(p = 0.05/2, df = df, lower.tail = FALSE), # t value\n    margin = tval*se, # margin of error\n    ci_lower = mean - margin, # lower bound of the confidence interval\n    ci_higher = mean + margin # upper bound of the confidence interval\n  ) \n\n# display object\nproduction_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 10\n  type         mean     n    df    sd     se  tval margin ci_lower ci_higher\n  <chr>       <dbl> <int> <dbl> <dbl>  <dbl> <dbl>  <dbl>    <dbl>     <dbl>\n1 aquaculture 0.324    59    58 0.149 0.0194  2.00 0.0389    0.285     0.363\n2 capture     4.38     59    58 1.20  0.156   2.00 0.313     4.07      4.69 \n```\n\n\n:::\n:::\n\n\nHow could you write about these confidence intervals?  \n\n**Mean production in US aquaculture is 0.32 million metric tons [95% CI: 0.29, 0.36], while mean capture production is 4.38 million metric tons [95% CI: 4.07, 4.69].**\n\n#### b. Visualizations\n\nWhen visualizing the central tendency (in this case, mean) and spread (standard deviation) or uncertainty (standard error) or confidence (confidence intervals), you can stack geoms on top of each other.  \n\nTo visualize the mean, we'll use `geom_point()`. Remember that `geom_point()` can be used for any plot you want to make that involves a point.    \n\nTo visualize the spread/uncertainty/confidence, we'll use `geom_errorbar()`. This is the geom that creates two lines that can extend away from a point.  \n\n##### Standard deviation\n\nFirst, we'll visualize standard deviation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = production_summary, \n       # x-axis should be production type\n       # y-axis is mean production\n       # color by production type\n       mapping = aes(x = type, \n                     y = mean, \n                     color = type)) + \n  # first layer: points to represent mean\n  geom_point(size = 2) + \n  # second layer: bars to represent standard deviation\n  geom_errorbar(mapping = aes(ymin = mean - sd, \n                              ymax = mean + sd),\n                width = 0.1) + # make the bars narrower\n  # relabelling x- and y-axes, adding title\n  labs(title = \"Standard deviation\",\n       x = \"Type\",\n       y = \"Mean and SD million metric tons production\")\n```\n\n::: {.cell-output-display}\n![](workshop-02_2026-04-10_files/figure-html/sd-plot-1.png){width=672}\n:::\n:::\n\n\n##### Standard error\n\nThen, we want to visualize standard error.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = production_summary, \n       # x-axis should be production type\n       # y-axis is mean production\n       # color by production type\n       mapping = aes(x = type, \n                     y = mean, \n                     color = type)) + \n  # first layer: points to represent mean\n  geom_point(size = 2) + \n  # second layer: bars to represent standard error\n  geom_errorbar(mapping = aes(ymin = mean - se, \n                              ymax = mean + se),\n                width = 0.1) + # make the bars narrower\n  # relabelling x- and y-axes, adding title\n  labs(title = \"Standard error\",\n       x = \"Type\",\n       y = \"Mean and SE million metric tons production\")\n```\n\n::: {.cell-output-display}\n![](workshop-02_2026-04-10_files/figure-html/se-plot-1.png){width=672}\n:::\n:::\n\n\n##### 95% confidence interval\n\nThen, we want to visualize the 95% confidence interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = production_summary, \n       # x-axis should be production type\n       # y-axis is mean production\n       # color by production type\n       mapping = aes(x = type, \n                     y = mean, \n                     color = type)) + \n  # first layer: points to represent mean\n  geom_point(size = 2) + \n  # second layer: bars to represent 95% CI\n  geom_errorbar(mapping = aes(ymin = ci_lower, \n                              ymax = ci_higher),\n                # make the bars narrower\n                width = 0.1) + \n  # relabelling x- and y-axes, adding title\n  labs(title = \"Confidence interval using geom_point and geom_errorbar\",\n       x = \"Type\",\n       y = \"Mean and 95% CI million metric tons production\")\n```\n\n::: {.cell-output-display}\n![](workshop-02_2026-04-10_files/figure-html/ci-95-plot-1.png){width=672}\n:::\n:::\n\n\n#### c. `geom_pointrange()`\n\nWe can also visualize means and spread/uncertainty/confidence intervals using the `geom_pointrange()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = production_summary, \n       # x-axis should be production type\n       # y-axis is mean production\n       # color by production type\n       mapping = aes(x = type, \n                     y = mean, \n                     color = type)) +\n  # first layer: points representing mean,\n  geom_pointrange(mapping = aes(ymin = ci_lower, \n                                ymax = ci_higher)) +\n  # relabelling x- and y-axes, adding title\n  labs(title = \"Confidence interval (using geom_pointrange)\",\n       x = \"Type\",\n       y = \"Mean and 95% CI million metric tons production\")\n```\n\n::: {.cell-output-display}\n![](workshop-02_2026-04-10_files/figure-html/ci-95-plot-with-pointrange-1.png){width=672}\n:::\n:::\n\n\n#### d. Visualizing with the underlying data\n\nLastly, we want to visualize the 95% confidence interval with the underlying data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = production_clean,\n       mapping = aes(x = type, \n                     y = metric_tons_mil, \n                     color = type)) +\n  # first layer: adding data (each point shows an observation)\n  geom_jitter(width = 0.1,\n              height = 0,\n              alpha = 0.4,\n              shape = 21) +\n  # second layer: means and 95% CI\n  geom_pointrange(data = production_summary,\n                  mapping = aes(x = type, \n                                y = mean, \n                                ymin = ci_lower, \n                                ymax = ci_higher)) +\n  # custom colors\n  scale_color_manual(values = c(\"aquaculture\" = \"deepskyblue\",\n                                \"capture\" = \"orangered\")) +\n  # relabelling x- and y-axes, adding title\n  labs(x = \"Production type\",\n       y = \"Million metric tons of production\",\n       title = \"Capture produces more than aquaculture\") +\n  # custom theme\n  theme_light() +\n  # taking out legend\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](workshop-02_2026-04-10_files/figure-html/final-plot-1.png){width=672}\n:::\n:::\n\n\n:::{.callout-note title=\"ggplot themes\" collapse=\"true\"}\nThere are lots of themes in ggplot to play around with. These are nice to use to get rid of the grey background that is the default, and generally make your plot look cleaner.  \n\nA list of built-in themes and their `theme_()` function calls is [here](https://ggplot2-book.org/themes#sec-themes).\n:::\n\n\n#### e. Visualizing through time\n\nThen, if we want to visualize production through time:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = production_clean,\n       # x-axis should be year, y-axis should be metric tons in millions\n       # color and shape by production type\n       mapping = aes(x = year,\n                     y = metric_tons_mil,\n                     color = type,\n                     shape = type)) +\n  # first layer: points\n  geom_point() +\n  # second layer: lines\n  geom_line() +\n  # manually set colors\n  scale_color_manual(values = c(\"aquaculture\" = \"deepskyblue\",\n                                \"capture\" = \"orangered\")) +\n  # relabel x- and y-axes, legend title\n  labs(x = \"Year\",\n       y = \"Million metric tons of production\",\n       color = \"Production type\",\n       shape = \"Production type\") +\n  # custom theme\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](workshop-02_2026-04-10_files/figure-html/time-plot-1.png){width=672}\n:::\n:::\n\n\n**END OF WORKSHOP 2**\n\n## 3. Extra stuff\n\n### Shapes in figures\n\nIn class, we used `shape = 21` in the `geom_point()` call to make the points show up as open circles. By default, `ggplot()` uses `shape = 16` for all geometries that include points.    \n\nThis figure below shows the 26 options for shapes you can use in any plot with a point geometry.  \n\nShapes 0-14 are only outlines (with a transparent fill). Shapes 15 - 20 are filled (no outline). This means you control them with `color` in the `aes()` function, and `scale_color_()` functions. These show up in [pink]{style=\"color: #db0f48; font-weight: bold\"} in the plot below.  \n\nShapes 21 - 25 include outlines and fills. You can manipulate both: you can change the outline using `color` and `scale_color_()` functions, and change the fill with `fill` and `scale_fill_()` functions. In the plot, outlines show up in [pink]{style=\"color: #db0f48; font-weight: bold\"} and fills show up in [yellow]{style=\"color: #f4b301; font-weight: bold\"}.   \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](workshop-02_2026-04-10_files/figure-html/shapes-1.png){width=672}\n:::\n:::\n\n\nCredit to [Albert Kuo's blog post](https://blog.albertkuo.me/post/point-shape-options-in-ggplot/) for inspiring me to make my own reference figure, and Alex Phillips's [colorblind friendly schemes](https://www.nceas.ucsb.edu/sites/default/files/2022-06/Colorblind%20Safe%20Color%20Schemes.pdf) for the colors in the figure.  \n\n### Overlapping histograms\n\nIn class, we created a histogram that combined the distributions of metric tons of production for two groups: capture and aquaculture production.  \n\nI got a question about what a histogram would look like if there was overlap in the distributions of groups, and wanted to demonstrate visually what that would look like.\n\nHere, I'm generating a data frame with fake values from distributions that have different means but overlapping spread:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\n# creating a data frame\ntest_df <- tibble(\n  # generating fake values\n  a = rnorm(n = 50, mean = 30, sd = 10),\n  b = rnorm(n = 50, mean = 40, sd = 10)\n) |> \n  # making data frame longer\n  pivot_longer(\n    cols = a:b,\n    names_to = \"group\",\n    values_to = \"value\"\n  )\n```\n:::\n\n::: {.cell}\n<style type=\"text/css\">\n.multiple .leftcolumn {\n  width: 40%;\n  margin-top: 0px;\n  margin-right: 50px;\n  margin-bottom: 0px;\n  margin-left: 250px\n}\n\n.multiple .rightcolumn {\n  width:40%;\n  margin-top: 0px;\n  margin-right: 250px;\n  margin-bottom: 0px;\n  margin-left: 50px\n}\n\n.multiple .columns {\n  display: flex;\n}\n\n@media (max-width: 767px) {\n  .multiple .column {\n    width: auto;\n  }\n\n .multiple .columns {\n   display: flex;\n   flex-direction: column;\n  }\n}\n</style>\n:::\n\n\n\nThen, we can compare the histograms if they are stacked (on the left) and separate (on the right):\n\n::::: { .multiple}\n\n:::: {.columns .column-screen-inset}\n\n::: leftcolumn\nStacked histograms:\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = test_df,\n       # only supplying x-axis value\n       # filling by group\n       mapping = aes(x = value,\n                     fill = group)) +\n  # first layer: histogram\n  geom_histogram(bins = 9,\n                 color = \"black\") +\n  # creating different panels for each group\n  facet_wrap(~ group) +\n  # edits to y-axis to get rid of space between bottom of columns and x-axis\n  # changing y-axis limits\n  # making y-axis breaks smaller to make it easier to see frequencies\n  scale_y_continuous(expand = c(0, 0),\n                     limits = c(0, 36),\n                     breaks = seq(from = 0, to = 36, by = 3)) \n```\n\n::: {.cell-output-display}\n![](workshop-02_2026-04-10_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n:::\n\n::: rightcolumn\nSeparate histograms:\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = test_df,\n       # only supplying x-axis value\n       # filling by group\n       mapping = aes(x = value,\n                     fill = group)) +\n  # first layer: histogram\n  geom_histogram(bins = 9,\n                 color = \"black\") +\n  # creating different panels for each group\n  # facet_wrap(~ group) +\n  # edits to y-axis to get rid of space between bottom of columns and x-axis\n  # changing y-axis limits\n  # making y-axis breaks smaller to make it easier to see frequencies\n  scale_y_continuous(expand = c(0, 0),\n                     limits = c(0, 36),\n                     breaks = seq(from = 0, to = 36, by = 3)) \n```\n\n::: {.cell-output-display}\n![](workshop-02_2026-04-10_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n:::\n\n::::\n:::::\n\nIf the distributions overlap, then the counts stack on top of each other.\n",
    "supporting": [
      "workshop-02_2026-04-10_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}