{
  "hash": "21f20f398c17d96fbf0a88358c803d05",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 4 figures - Lectures 7 and 8\"\neditor: source\nfreeze: auto\nexecute:\n  message: false\n  warning: false\nformat:\n  html: \n    code-fold: true\nauthor:\n  - name: An Bui\n    url: https://an-bui.com/\n    affiliation: UC Santa Barbara, Ecology, Evolution, and Marine Biology\n    affiliation-url: https://www.eemb.ucsb.edu/\npublished-title: \"Lecture date\"\ndate: 2025-04-21\ndate-modified: last-modified\ncategories: [effect size, power analysis, confidence intervals]\ncitation:\n  url: https://spring-2024.envs-193ds.com/lecture/lecture_week-04.html\n---\n\n\n\n## 0. set up\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# cleaning\nlibrary(tidyverse)\n\n# visualization\ntheme_set(theme_classic() +\n            theme(panel.grid = element_blank(),\n                  axis.text = element_text(size = 18),\n                  axis.title = element_text(size = 18),\n                  text = element_text(family = \"Lato\")))\nlibrary(patchwork)\n\n# cohen's d\nlibrary(effectsize)\n\n# power\nlibrary(pwr)\n```\n:::\n\n\n## 1. Math\n\n\n### a. Cohen's d\n\n$$\nCohen's \\; d = \\frac{\\bar{y_A} - \\bar{y_B}}{\\sqrt{(s^2_A + s^2_B)/2}}\n$$\n\n### b. Cohen's d with separated SD\n\n$$\nCohen's \\; d = \\frac{\\bar{y_A} - \\bar{y_B}}{\\sqrt{\\frac{(n_A - 1)\\times s^2_A + (n_B - 1)\\times s^2_B}{n_A + n_B - 2}}}\n$$\n\n\n\n### b. confidence interval for two-sample t-test\n\n$$\nCI = (\\bar{y_A} - \\bar{y_B}) \\pm t \\times \\sqrt{\\frac{(n_A - 1)s_A^2 + (n_B - 1)s_B^2}{n_A+n_B-2}} \\times \\sqrt{\\frac{1}{n_A}+\\frac{1}{n_B}}\n$$\n\n### c. test statistic for paired t-test\n\n$$\nt_s = \\frac{\\bar{y}_d - \\mu_0}{s_d - \\sqrt{n}}\n$$\n\n### d. standard error for two-sample t-test\n\nIf variances are not equal:\n\n$$\nSE_{\\bar{y_A} - \\bar{y_B}} = \\sqrt{\\frac{s_A^2}{n_A}+\\frac{s_B^2}{n_B}}\n$$\n\n## 2. Interpret this output\n\nYou have two raised beds in which you're growing tomatoes. One bed is in the sun, but the other is in shade. You want to know if the weight of the tomatoes is different between beds. You measure 33 tomatoes from each bed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntomatoes <- cbind(sunny = rnorm(n = 33, mean = 150, sd = 20),\n                  shaded = rnorm(n = 33, mean = 130, sd = 10)) %>% \n  as_tibble() %>% \n  pivot_longer(cols = 1:2, names_to = \"sun_level\", values_to = \"weight_g\")\n\nggplot(data = tomatoes,\n       aes(x = sun_level,\n           y = weight_g)) +\n  geom_jitter(width = 0.1)\n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/tomatoes-1.png){width=672}\n:::\n\n```{.r .cell-code}\nvar.test(weight_g ~ sun_level,\n         data = tomatoes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  weight_g by sun_level\nF = 0.13091, num df = 32, denom df = 32, p-value = 1.114e-07\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.06465552 0.26506225\nsample estimates:\nratio of variances \n         0.1309112 \n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(weight_g ~ sun_level,\n       data = tomatoes,\n       var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  weight_g by sun_level\nt = -4.0118, df = 40.237, p-value = 0.0002548\nalternative hypothesis: true difference in means between group shaded and group sunny is not equal to 0\n95 percent confidence interval:\n -22.909848  -7.561738\nsample estimates:\nmean in group shaded  mean in group sunny \n            128.5939             143.8297 \n```\n\n\n:::\n:::\n\n\n\n## 3. Power analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# higher power\npwr.t.test(n = NULL, d = 0.7, sig.level = 0.05, power = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 54.01938\n              d = 0.7\n      sig.level = 0.05\n          power = 0.95\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n\n```{.r .cell-code}\n# lower power\npwr.t.test(n = NULL, d = 0.7, sig.level = 0.05, power = 0.80)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 33.02457\n              d = 0.7\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\n## 4. Write about this result\n\nYou have two worm compost bins: one in which you throw citrus peels, and the other in which you don’t. You’re curious to see if the citrus worms are bigger than the non-citrus worms. You measure 34 worms from each bin and find this result:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworms <- cbind(citrus = rnorm(n = 34, mean = 140, sd = 20),\n               non_citrus = rnorm(n = 34, mean = 160, sd = 15)) %>% \n  as_tibble() %>% \n  pivot_longer(cols = 1:2, names_to = \"compost_bin\", values_to = \"weight_g\")\n\nggplot(data = worms,\n       aes(x = compost_bin,\n           y = weight_g)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/worm-compost-1.png){width=672}\n:::\n\n```{.r .cell-code}\nvar.test(weight_g ~ compost_bin,\n         data = worms)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  weight_g by compost_bin\nF = 1.8562, num df = 33, denom df = 33, p-value = 0.08019\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.9270505 3.7167451\nsample estimates:\nratio of variances \n          1.856236 \n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(weight_g ~ compost_bin,\n       data = worms,\n       var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  weight_g by compost_bin\nt = -4.3456, df = 60.558, p-value = 5.392e-05\nalternative hypothesis: true difference in means between group citrus and group non_citrus is not equal to 0\n95 percent confidence interval:\n -29.20360 -10.79545\nsample estimates:\n    mean in group citrus mean in group non_citrus \n                140.1466                 160.1461 \n```\n\n\n:::\n:::\n\n\n\n## 5. Effect size examples\n\n### a. large sample size, small difference\n\n$$\n\\bar{y_a} - \\bar{y_b}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\ndata <- cbind(a = rnorm(n = 100, mean = 10, sd = 2), \n               b = rnorm(n = 100, mean = 11, sd = 2)) %>% \n  as_tibble() %>% \n  pivot_longer(cols = 1:2, names_to = \"group\", values_to = \"value\") %>% \n  group_by(group)\n\nset.seed(1)\nlarge <- data %>% \n  slice_sample(n = 40)\n\nggplot(data = large,\n       aes(x = group,\n           y = value)) +\n  stat_summary(geom = \"pointrange\",\n               fun.data = mean_se) +\n  scale_y_continuous(limits = c(5, 16)) \n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/small-vs-large-sample-size-1.png){width=672}\n:::\n\n```{.r .cell-code}\nt.test(value ~ group,\n       data = large,\n       var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  value by group\nt = -2.9666, df = 78, p-value = 0.003996\nalternative hypothesis: true difference in means between group a and group b is not equal to 0\n95 percent confidence interval:\n -2.1892413 -0.4308888\nsample estimates:\nmean in group a mean in group b \n       9.819199       11.129264 \n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(1)\nsmall <- data %>% \n  slice_sample(n = 20)\n\nggplot(data = small,\n       aes(x = group,\n           y = value)) +\n  stat_summary(geom = \"pointrange\",\n               fun.data = mean_se) +\n  scale_y_continuous(limits = c(5, 16)) \n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/small-vs-large-sample-size-2.png){width=672}\n:::\n\n```{.r .cell-code}\nt.test(value ~ group,\n       data = small,\n       var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  value by group\nt = -1.5737, df = 38, p-value = 0.1238\nalternative hypothesis: true difference in means between group a and group b is not equal to 0\n95 percent confidence interval:\n -1.9408171  0.2431029\nsample estimates:\nmean in group a mean in group b \n       10.23925        11.08811 \n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(1)\n\nsmall <- cbind(a = MASS::mvrnorm(n = 10, mu = 16.5, Sigma = 2, empirical = TRUE),\n               b = MASS::mvrnorm(n = 10, mu = 17, Sigma = 2, empirical = TRUE)) %>% \n  as.data.frame() %>% \n  rename(\"a\" = \"V1\", \"b\" = \"V2\") %>% \n  pivot_longer(cols = 1:2, names_to = \"group\", values_to = \"value\")\n# small <- cbind(a = rnorm(n = 10, mean = 14, sd = 3), \n#                b = rnorm(n = 10, mean = 17, sd = 3)) %>% \n#   as_tibble() %>% \n#   pivot_longer(cols = 1:2, names_to = \"group\", values_to = \"value\")\nggplot(data = small,\n       aes(x = group,\n           y = value)) +\n  geom_point(size = 3,\n             shape = 21,\n             aes(color = group),\n             position = position_jitter(\n               width = 0.15,\n               height = 0,\n               seed = 10\n             )) +\n  stat_summary(geom = \"point\",\n               fun = mean,\n               color = \"red\",\n               size = 4) +\n  # scale_y_continuous(limits = c(5, 16),\n  #                    breaks = c(6, 9, 12, 15)) +\n  scale_color_manual(values = c(\"darkblue\", \"darkgreen\")) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/small-vs-large-sample-size-3.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = small,\n       aes(x = value)) +\n  geom_density(aes(fill = group),\n               alpha = 0.4)\n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/small-vs-large-sample-size-4.png){width=672}\n:::\n\n```{.r .cell-code}\nt.test(value ~ group,\n       data = small,\n       var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  value by group\nt = -0.79057, df = 18, p-value = 0.4395\nalternative hypothesis: true difference in means between group a and group b is not equal to 0\n95 percent confidence interval:\n -1.8287398  0.8287398\nsample estimates:\nmean in group a mean in group b \n           16.5            17.0 \n```\n\n\n:::\n\n```{.r .cell-code}\ncohens_d(value ~ group,\n         data = small,\n         pooled_sd = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |        95% CI\n-------------------------\n-0.35     | [-1.23, 0.54]\n\n- Estimated using un-pooled SD.\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(1)\nlarge <- cbind(a = MASS::mvrnorm(n = 100, mu = 16.5, Sigma = 2, empirical = TRUE),\n               b = MASS::mvrnorm(n = 100, mu = 17, Sigma = 2, empirical = TRUE)) %>% \n  as.data.frame() %>% \n  rename(\"a\" = \"V1\", \"b\" = \"V2\") %>% \n  pivot_longer(cols = 1:2, names_to = \"group\", values_to = \"value\")\nggplot(data = large,\n       aes(x = group,\n           y = value)) +\n  geom_point(size = 3,\n             shape = 21,\n             aes(color = group),\n             position = position_jitter(\n               width = 0.15,\n               height = 0,\n               seed = 10\n             )) +\n  stat_summary(geom = \"point\",\n               fun = mean,\n               color = \"red\",\n               size = 4) +\n\n  # scale_y_continuous(limits = c(5, 16),\n  #                    breaks = c(6, 9, 12, 15)) +\n  scale_color_manual(values = c(\"darkblue\", \"darkgreen\")) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/small-vs-large-sample-size-5.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = large,\n       aes(x = value)) +\n  geom_histogram(aes(fill = group),\n               alpha = 0.4)\n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/small-vs-large-sample-size-6.png){width=672}\n:::\n\n```{.r .cell-code}\nt.test(value ~ group,\n       data = large,\n       var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  value by group\nt = -2.5, df = 198, p-value = 0.01323\nalternative hypothesis: true difference in means between group a and group b is not equal to 0\n95 percent confidence interval:\n -0.8944035 -0.1055965\nsample estimates:\nmean in group a mean in group b \n           16.5            17.0 \n```\n\n\n:::\n\n```{.r .cell-code}\ncohens_d(value ~ group,\n         data = large,\n         pooled_sd = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |         95% CI\n--------------------------\n-0.35     | [-0.63, -0.07]\n\n- Estimated using un-pooled SD.\n```\n\n\n:::\n:::\n\n\n\n### b. needlegrass example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nneedlegrass <- cbind(ungrazed = rnorm(n = 35, mean = 82, sd = 6), \n                     grazed = rnorm(n = 35, mean = 74, sd = 5)) %>% \n  as_tibble() %>% \n  pivot_longer(cols = 1:2, names_to = \"plot_type\", values_to = \"height_cm\")\n\n# boxplot\nggplot(data = needlegrass,\n       aes(x = plot_type,\n           y = height_cm,\n           color = plot_type)) +\n  geom_boxplot(outliers = FALSE,\n               linewidth = 1) +\n  geom_point(position = position_jitter(\n    width = 0.1, \n    height = 0.1,\n    seed = 10\n  ),\n  alpha = 0.4,\n  size = 1) +\n    scale_color_manual(values = c(\"darkgreen\", \"cornflowerblue\")) \n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/needlegrass-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# plot without all the adjustments\nggplot(data = needlegrass,\n       aes(x = plot_type,\n           y = height_cm,\n           color = plot_type)) +\n  geom_point(position = position_jitter(width = 0.1, height = 0, seed = 10),\n             alpha = 0.2) +\n  stat_summary(geom = \"pointrange\",\n               fun.data = mean_cl_normal) \n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/needlegrass-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# \"finalized\" plot\nggplot(data = needlegrass,\n       aes(x = plot_type,\n           y = height_cm,\n           color = plot_type)) +\n  geom_point(position = position_jitter(width = 0.1, height = 0, seed = 10),\n             alpha = 0.2) +\n  scale_color_manual(values = c(\"darkgreen\", \"cornflowerblue\")) +\n  stat_summary(geom = \"pointrange\",\n               fun.data = mean_cl_normal,\n               size = 1,\n               linewidth = 1) +\n  labs(x = \"Plot type\",\n       y = \"Height (cm)\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/needlegrass-3.png){width=672}\n:::\n:::\n\n\nDoing a t-test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar.test(height_cm ~ plot_type,\n       data = needlegrass)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  height_cm by plot_type\nF = 0.72641, num df = 34, denom df = 34, p-value = 0.3559\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.366669 1.439115\nsample estimates:\nratio of variances \n         0.7264149 \n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(height_cm ~ plot_type,\n       data = needlegrass)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  height_cm by plot_type\nt = -5.9471, df = 66.334, p-value = 1.127e-07\nalternative hypothesis: true difference in means between group grazed and group ungrazed is not equal to 0\n95 percent confidence interval:\n -9.720197 -4.834401\nsample estimates:\n  mean in group grazed mean in group ungrazed \n              75.18323               82.46053 \n```\n\n\n:::\n\n```{.r .cell-code}\nvect <- dt(x = seq(from = -10, to = 10, by = 0.5), df = 66.334) %>% \n  enframe()\n\nggplot(data = vect,\n       aes(x = name,\n           y = value)) +\n  geom_line() +\n  geom_vline(xintercept = -5.9471)\n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/t-test-1.png){width=672}\n:::\n:::\n\n\nCohen's d:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# pooled SD\ncohens_d(height_cm ~ plot_type,\n       data = needlegrass)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |         95% CI\n--------------------------\n-1.42     | [-1.94, -0.89]\n\n- Estimated using pooled SD.\n```\n\n\n:::\n\n```{.r .cell-code}\n# unpooled SD\ncohens_d(height_cm ~ plot_type,\n       data = needlegrass, \n       pooled_sd = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |         95% CI\n--------------------------\n-1.42     | [-1.94, -0.89]\n\n- Estimated using un-pooled SD.\n```\n\n\n:::\n\n```{.r .cell-code}\n# by hand\nneedlegrass_sum <- needlegrass %>% \n  group_by(plot_type) %>% \n  reframe(\n    mean = mean(height_cm),\n    var = var(height_cm),\n    n = length(height_cm)\n  )\n\nya <- pluck(needlegrass_sum, 2, 1)\nyb <- pluck(needlegrass_sum, 2, 2)\nvara <- pluck(needlegrass_sum, 3, 1)\nvarb <- pluck(needlegrass_sum, 3, 2)\nna <- pluck(needlegrass_sum, 4, 1)\nnb <- pluck(needlegrass_sum, 4, 2)\n\n# by hand\n\n(ya - yb)/sqrt((vara + varb)/2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.421636\n```\n\n\n:::\n\n```{.r .cell-code}\n(ya - yb)/sqrt(\n  ((na - 1)*vara + (nb - 1)*varb)/(na + nb - 2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.421636\n```\n\n\n:::\n:::\n\n\n## 6. good and bad results statements\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmanaged <- rnorm(n = 33, mean = 5, sd = 1) %>% \n  enframe() %>% \n  mutate(treatment = \"managed\")\nnonintervention <- rnorm(n = 30, mean = 7, sd = 1) %>% \n  enframe() %>% \n  mutate(treatment = \"non-intervention\") \npools <- rbind(managed, nonintervention) %>% \n  select(treatment, value) %>% \n  rename(temp = value)\nvar.test(temp ~ treatment,\n         data = pools)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  temp by treatment\nF = 1.287, num df = 32, denom df = 29, p-value = 0.4953\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.6197933 2.6377877\nsample estimates:\nratio of variances \n          1.286962 \n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(temp ~ treatment,\n       data = pools)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  temp by treatment\nt = -11.206, df = 60.948, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group managed and group non-intervention is not equal to 0\n95 percent confidence interval:\n -2.558536 -1.783706\nsample estimates:\n         mean in group managed mean in group non-intervention \n                      4.952439                       7.123560 \n```\n\n\n:::\n\n```{.r .cell-code}\ncohens_d(temp ~ treatment,\n       data = pools)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |         95% CI\n--------------------------\n-2.81     | [-3.51, -2.10]\n\n- Estimated using pooled SD.\n```\n\n\n:::\n:::\n\n\nStatement: Our data suggest a difference in water temperature between managed (n = 33) and non-intervention (i.e. control, n = 30) vernal pools, with a strong (Cohen’s d = 2.19) effect of management.  \nTemperatures in managed pools were different from those in non-intervention pools (two-tailed two-sample t-test, t(60.9) = -8.7, p < 0.001, ⍺ = 0.05); on average, managed pools were 5.3 °C, while control pools were 7.1 °C.\n\n## 7. QQ/histograms\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(666)\ndata1 <- rnorm(n = 30, mean = 15, sd = 2) |> \n  enframe()\n\nggplot(data = data1,\n       aes(x = value)) +\n  geom_histogram(bins = 6,\n                 fill = \"cornflowerblue\",\n                 color = \"black\") +\n  scale_y_continuous(expand = c(0, 0))\n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/qq-hist-comparisons-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = data1,\n       aes(sample = value)) +\n  geom_qq_line(color = \"black\") +\n  geom_qq(color = \"cornflowerblue\",\n          size = 4)\n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/qq-hist-comparisons-2.png){width=672}\n:::\n\n```{.r .cell-code}\nset.seed(666)\ndata2 <- rgamma(n = 30, shape = 0.5) |> \n  enframe()\n\nggplot(data = data2,\n       aes(x = value)) +\n  geom_histogram(bins = 6,\n                 fill = \"orange\",\n                 color = \"black\") +\n  scale_y_continuous(expand = c(0, 0))\n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/qq-hist-comparisons-3.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = data2,\n       aes(sample = value)) +\n  geom_qq_line(color = \"black\") +\n  geom_qq(color = \"orange\",\n          size = 4)\n```\n\n::: {.cell-output-display}\n![](lecture_week-04_files/figure-html/qq-hist-comparisons-4.png){width=672}\n:::\n:::\n",
    "supporting": [
      "lecture_week-04_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}