{
  "hash": "6c2768a97484dbbda3c2b01c77a0a450",
  "result": {
    "markdown": "---\ntitle: \"Clear communication = interpretable stats\"\ndescription: \"Communicating about statistical results, a few ways\"\nauthor:\n  - name: An Bui\n    url: https://an-bui.com/\n    affiliation: UC Santa Barbara, Ecology, Evolution, and Marine Biology\n    affiliation-url: https://www.eemb.ucsb.edu/\nfreeze: auto\ncategories: [communication]\nexecute:\n  message: false\n  warning: false\ncode-fold: true\ncitation:\n  url: https://an-bui.github.io/ES-193DS-W23/resources/communicating-results.html\n---\n\n\n# Writing, stats, and data science\n\nObviously, this is a stats class - however, stats exists within the data science world, and data science includes communication about stats. It's important for us, in this class, to understand the mechanics of the tests we use (assumptions, underlying math, etc.) but the *real* challenge is being able to communicate about those tests and ground what those tests reveal in the biology of the system we're studying - that's *environmental science*.\n\nCommunication about what statistical methods you use to address a question/answer a hypothesis should include writing along with some visualization (figures and/or tables). The following are examples from lecture. You've also done a lot of reading in this class, and have seen a lot of examples of how to communicate about statistics from other researchers.  \n\nEach code chunk with what is potentially new information is annotated - however, I haven't annotated things like tests, creating plots, etc. because we've gone over that in class.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# general use\nlibrary(tidyverse)\n\n# data\nlibrary(palmerpenguins)\n\n# visualization\nlibrary(patchwork)\nlibrary(flextable)\n\n# model summary table tools\nlibrary(broom)\nlibrary(car)\nlibrary(ggeffects)\nlibrary(equatiomatic)\n\n# using the Lato font from Google fonts\nlibrary(showtext)\nfont_add_google(\"Lato\", \"Lato\")\nshowtext_auto()\n```\n:::\n\n\n# Comparing groups\n\n## One sample t-test\n\nThis example from lecture was about comparing a sample of acorn masses to a theoretical mean (2 g).  \n\nJust generating some fake data for this example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\nacorns <- rnorm(n = 41, mean = 2, sd = 1)\n```\n:::\n\n\n### Checking assumptions\n\nFor a t-test, one of the assumptions you can check is that your variable is normally distributed. Doing this with a histogram and a QQ plot makes sense: \n\n\n::: {.cell layout-align=\"center\"}\n\n````{.cell-code}\n```{{r hist-and-qq}}\n#| fig.width: 12\n#| fig.height: 6\n#| out.width: 90%\n#| fig.align: center\n\nhist <- enframe(acorns) %>% \n  ggplot(aes(x = value)) +\n  geom_histogram(bins = 7, fill = \"cornflowerblue\", color = \"#000000\") +\n  scale_y_continuous(expand = c(0, 0), limits = c(0, 11.5), breaks = c(0, 3, 6, 9, 12)) +\n  geom_vline(xintercept = 2, color = \"maroon\", lty = 2, linewidth = 1) +\n  theme_classic() +\n  labs(x = \"Acorn mass (g)\", y = \"Count\", \n       title = \"A)\") +\n  theme(plot.title.position = \"plot\")\n\nqq <- enframe(acorns) %>% \n  ggplot(aes(sample = value)) +\n  stat_qq_line(aes(sample = value)) +\n  stat_qq(aes(sample = value), color = \"cornflowerblue\", size = 3) +\n  theme_classic() +\n  labs(x = \"Theoretical quantiles\", y = \"Sample quantiles\",\n       title = \"B)\") +\n  theme(plot.title.position = \"plot\")\n\nhist + qq\n```\n````\n\n::: {.cell-output-display}\n![](communicating-results_files/figure-html/hist-and-qq-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n**Example caption:**  \n\n::: {style=\"font-size: 90%; color: #787878;\"}\n\n**Figure 1. Visual checks for normally distributed variable.** A) Histogram of acorn masses (g). Bars in histogram represent counts of acorns in each bin. Dashed red line represents theoretical mean ($\\mu$ = 0). B) Quantile-quantile (QQ) plot. Points in QQ plot represent sample quantiles compared against theoretical quantiles from a normal distribution. Solid black line represents a 1:1 relationship between sample and theoretical quantiles.\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Making sure your figures render properly\n\nYou put a lot of effort into making figures, so it's worth making sure they appear the way you think they would in your final document! You can control these in your chunk options (i.e. within the curly brackets). There are many ways to do this, but I like adjusting the a) aspect ratio using `fig.width` and `fig.height` and b) proportion using `out.width`.  \n\nIn Quarto, you can set those options within the chunk (see above) _or_ in the curly brackets. In RMarkdown, you can only use the curly brackets, which would look like:  \n\n`{r fig.width = 12, fig.height = 6, out.width = \"90%\", fig.align = \"center\"}`\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Formatting captions\n\nYou can write a caption in text (the easiest way) or you can try using code chunk options if you're using Quarto. There are tips for how to do that [here](https://quarto.org/docs/get-started/computations/rstudio.html#figures), though the formatting might not be the standard (i.e. bold text for figure number and title). I also changed the caption color - not required, but nice to add another visual cue that the caption is attached to the figure.  \n\nGenerally, the font size in captions tends to be smaller than the main text. You can insert these options in Quarto by wrapping your text in a \"fenced div\" (see the [source code](https://github.com/an-bui/ES-193DS-W23/blob/main/resources/communicating-results.qmd) for how to do that). In RMarkdown, you can use an HTML wrapper (here's an [example](https://html-shark.com/HTML/TextSizeType.htm)).\n:::\n\n**Example text:**  \n\nWe visually assessed normality using a histogram and a QQ plot (Figure 1), and determined that acorn mass in our sample was normally distributed.\n\n### Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacorn_test <- t.test(acorns, mu = 2)\n```\n:::\n\n\n**Example text:**  \n\nWe assessed whether acorn masses in our sample differed from the claim of 2g using a one-sample two-tailed t-test. Our null hypothesis was that the mean acorn mass in our sample was the same as the claim.\n\n### Test results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacorn_test\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  acorns\nt = 1.8035, df = 40, p-value = 0.07885\nalternative hypothesis: true mean is not equal to 2\n95 percent confidence interval:\n 1.964535 2.623323\nsample estimates:\nmean of x \n 2.293929 \n```\n:::\n:::\n\n\n**Example text:**  \n\nWe collected 41 acorns and found no significant difference between our sample mean mass and the claim (One-sample two-tailed t-test, t(40) = 1.8, $\\alpha$ = 0.05, p = 0.079). Our data suggest that acorn masses in our sampling area are on average the same mass as the claimed mass (Figure 1A).\n\n## Chi-square\n\nThis example from lecture was about surveying people to understand their priorities for restoration.  \n\nAgain, generating fake data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# making a matrix (not a data frame) called `survey` ----\nsurvey <- tribble(\n  ~distance, ~trails, ~dog_access, ~wildlife_habitat,\n  \"walking_distance\", 55, 38, 33,\n  \"driving_distance\", 41, 25, 29,\n  \"out_of_town\", 22, 27, 45\n) %>% \n  \n  # turning the column `distance` into the matrix rownames ----\n  column_to_rownames(\"distance\")\n```\n:::\n\n\n### Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_test <- chisq.test(survey)\n```\n:::\n\n\n**Example text**:  \n\nTo determine whether there was a relationship between living distance from wetland and restoration priority, we used a chi-square test using survey data from visitors (Table 1). Our null hypothesis was that there was no relationship between living distance from the wetland and restoration priority.\n\n### Table\n\n**Example caption**:  \n\n[**Note:** Table captions usually go above the table.]{.aside}\n\n::: {style=\"font-size: 90%; color: #787878;\"}\n\n**Table 1. Wetland restoration priority by living distance.** Numbers in parentheses indicate proportion of responses (i.e. the 55 respondents living within walking distance of the wetland who prioritize trail development represent 44% of the total number of respondents living within walking distance (n = 126)).\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate proportions\nsurvey_summary <- survey %>% \n  # turning `survey` into a data frame ----\n  as_tibble(rownames = \"distance\") %>% \n  # making it long format\n  pivot_longer(cols = trails:wildlife_habitat, names_to = \"responses\", values_to = \"counts\") %>% \n  \n  # calculating proportions ----\n  # grouping by living distance\n  group_by(distance) %>% \n  # counting the total number of respondents per living distance\n  mutate(sum = sum(counts)) %>% \n  # ungrouping to make sure that distance groups don't mess up downstream functions\n  ungroup() %>% \n  # calculating proportion of responses per living distance\n  mutate(prop = counts/sum) %>% \n  \n  # making the table look nicer ----\n  # making a new column where counts and proportions are displayed together\n  mutate(text = paste0(counts, \" (\", round(prop, digits = 2), \")\")) %>% \n  # selecting columns of interest\n  select(distance, responses, text) %>% \n  # making the data frame wider so that the columns are responses and rows are distance\n  pivot_wider(names_from = \"responses\", values_from = \"text\") %>% \n  # making the row labels nicer\n  mutate(distance = case_match(\n    distance,\n    \"walking_distance\" ~ \"Walking distance\",\n    \"driving_distance\" ~ \"Driving distance\",\n    \"out_of_town\" ~ \"Out of town\"\n  )) %>% \n  \n  # turning everything into a table ----\n  flextable() %>% \n  # changing the column names to look nicer\n  set_header_labels(distance = \"Living distance\",\n                    trails = \"Trails\",\n                    dog_access = \"Dog access\",\n                    wildlife_habitat = \"Wildlife habitat\") %>% \n  # making the table fit the viewer window\n  autofit()\n  \nsurvey_summary\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-a2dce7d2{}.cl-a2d26118{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-a2db2046{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a2db294c{width:1.44in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a2db294d{width:0.897in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a2db294e{width:1.083in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a2db294f{width:1.279in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a2db2956{width:1.44in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a2db2957{width:0.897in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a2db2958{width:1.083in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a2db2960{width:1.279in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a2db2961{width:1.44in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a2db2962{width:0.897in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a2db2963{width:1.083in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a2db2964{width:1.279in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-a2dce7d2'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-a2db294c\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">Living distance</span></p></th><th class=\"cl-a2db294d\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">Trails</span></p></th><th class=\"cl-a2db294e\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">Dog access</span></p></th><th class=\"cl-a2db294f\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">Wildlife habitat</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a2db2956\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">Walking distance</span></p></td><td class=\"cl-a2db2957\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">55 (0.44)</span></p></td><td class=\"cl-a2db2958\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">38 (0.3)</span></p></td><td class=\"cl-a2db2960\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">33 (0.26)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a2db2956\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">Driving distance</span></p></td><td class=\"cl-a2db2957\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">41 (0.43)</span></p></td><td class=\"cl-a2db2958\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">25 (0.26)</span></p></td><td class=\"cl-a2db2960\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">29 (0.31)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a2db2961\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">Out of town</span></p></td><td class=\"cl-a2db2962\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">22 (0.23)</span></p></td><td class=\"cl-a2db2963\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">27 (0.29)</span></p></td><td class=\"cl-a2db2964\"><p class=\"cl-a2db2046\"><span class=\"cl-a2d26118\">45 (0.48)</span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::{.callout-warning}\nRemember not to name code chunks with tables in them! Rendering gets stuck on the chunk if you do.\n:::\n\n### Test results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_test\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  survey\nX-squared = 15.276, df = 4, p-value = 0.004162\n```\n:::\n:::\n\n\n**Example text:**  \n\nBased on responses from individuals living within walking distance (n = 126), within driving distance (n = 95), and out of town (n = 94), restoration priorities differ significantly by living distance category (Table 1, $\\chi^2$(4) = 15.3, _p_ = 0.004, $\\alpha$ = 0.05).  \n\nWhile the majority of residents within walking distance and driving distance prioritize trail use (44% and 43% respectively), residents outside the city prioritize wildlife habitat (48%).  \n\nThese results indicate that wetland users living outside the city may have different intentions for visiting the wetland than local residents, but that restorationists can consider both trails and wildlife habitat in designing a restoration plan to suit user needs.\n\n## Analysis of variance\n\nThis example from lecture used the `penguins` data set from `{palmerpenguins}`.\n\n### Checking assumptions\n\nFor ANOVA, you should be checking that your variable is normally distributed and that your groups have equal variances. You can check the first assumption visually using histograms and QQ plots:\n\n\n::: {.cell layout-align=\"center\"}\n\n````{.cell-code}\n```{{r penguin-hist-and-qq}}\n#| fig.height: 12\n#| fig.width: 10\n#| out.width: 60%\n#| fig.align: center\n\n# setting some color options\ncol1 <- \"cornflowerblue\"\ncol2 <- \"orange\"\ncol3 <- \"darkgreen\"\n\n# making separate data frames for each species\nadelie <- penguins %>% \n  filter(species == \"Adelie\")\n\nchinstrap <- penguins %>% \n  filter(species == \"Chinstrap\")\n\ngentoo <- penguins %>% \n  filter(species == \"Gentoo\")\n\n# making histograms for each species\n\nadelie_hist <- ggplot(data = adelie, aes(x = bill_length_mm)) +\n  geom_histogram(bins = 10, fill = col1, color = col1, alpha = 0.8) +\n  scale_y_continuous(expand = c(0, 0), limits = c(0, 32)) +\n  labs(x = \"Bill length (mm)\", y = \"Count\",\n       title = \"A)\") +\n  theme_bw() +\n  theme(panel.grid = element_blank(),\n        axis.text = element_text(size = 18),\n        axis.title = element_text(size = 18),\n        axis.ticks = element_blank(),\n        text = element_text(family = \"Lato\"),\n        plot.title.position = \"plot\") \n\nchinstrap_hist <- ggplot(data = chinstrap, aes(x = bill_length_mm)) +\n  geom_histogram(bins = 10, fill = col2, color = col2, alpha = 0.8) +\n  scale_y_continuous(expand = c(0, 0), limits = c(0, 23)) +\n  labs(x = \"Bill length (mm)\", y = \"Count\",\n       title = \"C)\") +\n  theme_bw() +\n  theme(panel.grid = element_blank(),\n        axis.text = element_text(size = 18),\n        axis.title = element_text(size = 18),\n        axis.ticks = element_blank(),\n        text = element_text(family = \"Lato\"),\n        plot.title.position = \"plot\") \n\ngentoo_hist <- ggplot(data = gentoo, aes(x = bill_length_mm)) +\n  geom_histogram(bins = 10, fill = col3, color = col3, alpha = 0.8) +\n  scale_y_continuous(expand = c(0, 0), limits = c(0, 37)) +\n  labs(x = \"Bill length (mm)\", y = \"Count\",\n       title = \"E)\") +\n  theme_bw() +\n  theme(panel.grid = element_blank(),\n        axis.text = element_text(size = 18),\n        axis.title = element_text(size = 18),\n        axis.ticks = element_blank(),\n        text = element_text(family = \"Lato\"),\n        plot.title.position = \"plot\") \n\n# making QQ plots for each species\nadelie_qq <- ggplot(data = adelie, aes(sample = bill_length_mm)) +\n  stat_qq_line(linewidth = 1) +\n  stat_qq(col = col1) +\n  labs(x = \"Theoretical\", y = \"Sample\",\n       title = \"B)\") +\n  theme_bw() +\n  theme(panel.grid = element_blank(),\n        axis.text = element_text(size = 18),\n        axis.title = element_text(size = 18),\n        axis.ticks = element_blank(),\n        text = element_text(family = \"Lato\"),\n        plot.title.position = \"plot\") \n\nchinstrap_qq <- ggplot(data = chinstrap, aes(sample = bill_length_mm)) +\n  stat_qq_line(linewidth = 1) +\n  stat_qq(col = col2) +\n  labs(x = \"Theoretical\", y = \"Sample\",\n       title = \"D)\") +\n  theme_bw() +\n  theme(panel.grid = element_blank(),\n        axis.text = element_text(size = 18),\n        axis.title = element_text(size = 18),\n        axis.ticks = element_blank(),\n        text = element_text(family = \"Lato\"),\n        plot.title.position = \"plot\") \n\ngentoo_qq <- ggplot(data = gentoo, aes(sample = bill_length_mm)) +\n  stat_qq_line(linewidth = 1) +\n  stat_qq(col = col3) +\n  labs(x = \"Theoretical\", y = \"Sample\",\n       title = \"F)\") +\n  theme_bw() +\n  theme(panel.grid = element_blank(),\n        axis.text = element_text(size = 18),\n        axis.title = element_text(size = 18),\n        axis.ticks = element_blank(),\n        text = element_text(family = \"Lato\"),\n        plot.title.position = \"plot\") \n\n# putting all the plots together using `patchwork`\n\n(adelie_hist + adelie_qq) / (chinstrap_hist + chinstrap_qq) / (gentoo_hist + gentoo_qq)\n```\n````\n\n::: {.cell-output-display}\n![](communicating-results_files/figure-html/penguin-hist-and-qq-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n**Example caption:**  \n\n::: {style=\"font-size: 90%; color: #787878;\"}\n\n**Figure 2. Visual checks for normally distributed variable.** Visual checks for normally distributed variable. A, C, E) Histograms of penguin bill length (mm) for Adelie (A), Chinstrap (C), and Gentoo (E) penguins. Bars represent counts of bill lengths in each bin. B, D, F) QQ plots of penguin bill length. Points in QQ plot represent sample quantiles compared against theoretical quantiles from a normal distribution. Solid black lines represent a 1:1 relationship between sample and theoretical quantiles.\n\n:::\n\nNow a series of Shapiro-Wilk tests to statistically test for normal distribution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(adelie$bill_length_mm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  adelie$bill_length_mm\nW = 0.99336, p-value = 0.7166\n```\n:::\n\n```{.r .cell-code}\nshapiro.test(chinstrap$bill_length_mm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  chinstrap$bill_length_mm\nW = 0.97525, p-value = 0.1941\n```\n:::\n\n```{.r .cell-code}\nshapiro.test(gentoo$bill_length_mm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  gentoo$bill_length_mm\nW = 0.97272, p-value = 0.01349\n```\n:::\n:::\n\n\n:::{.callout-note collapse=\"true\"}\n### Making decisions about normality\n\nIn lecture, we talked about making a decision: do you think this deviation from normality is a _big enough deal_ or not? ANOVA is fairly robust against violations of the normality assumption, and we have a lot of observations. We might decide to continue with the ANOVA (especially since the variances between groups are equal - see below). However, you could also try a transformation (e.g. a log transformation) on bill length, and see if that fixes your problem.\n:::\n\nChecking for equal variances:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleveneTest(bill_length_mm ~ species, data = penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   2  2.2425 0.1078\n      339               \n```\n:::\n:::\n\n\n**Example text:**  \n\n[Note that you only really need to state your $\\alpha$ once in a report. The assumption is that you're not changing your significance level for each test.]{.aside}\nPrior to our analysis, we checked assumptions for analysis of variance. We tested for equality of variances between groups using Levene's test and found no statistically significant differences in variances between groups (F(2, 339) = 2.24, _p_ = 0.11, $\\alpha$ = 0.05). We visually assessed normality using histograms and QQ plots (Figure 2) and statistically tested for normality of penguin bill length using Shapiro-Wilk tests for each species. Adelie and Chinstrap bill length did not indicate any deviations from normality (Adelie: W W = 0.99, _p_ = 0.72; Chinstrap: W = 0.98, _p_ = 0.19), but Gentoo bill length did (W = 0.97, _p_ = 0.01). Taking this together, we decided to continue using analysis of variance given our sample size (n = 342) and that analysis of variance tends to be robust to slight violations of the normality assumption.\n\n### Test\n\nANOVA: \n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_anova <- aov(bill_length_mm ~ species, data = penguins)\n```\n:::\n\n\nTukey HSD:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_HSD <- TukeyHSD(penguins_anova)\n```\n:::\n\n\n**Example text:**\n\nWe tested for differences between penguin species in bill length using analysis of variance. Our null hypothesis was that species did not differ in mean bill length. We used Tukey's Honestly Significant Difference (Tukey HSD) as a post-hoc test to determine pair-wise differences between groups.\n\n### Test results\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_anova\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\n   aov(formula = bill_length_mm ~ species, data = penguins)\n\nTerms:\n                 species Residuals\nSum of Squares  7194.317  2969.888\nDeg. of Freedom        2       339\n\nResidual standard error: 2.959853\nEstimated effects may be unbalanced\n2 observations deleted due to missingness\n```\n:::\n:::\n\n\nANOVA table:\n\n**Example caption:**  \n\n::: {style=\"font-size: 90%; color: #787878;\"}\n\n**Table 2. ANOVA table.** Bolded p-value indicates significance.\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# getting table from ANOVA object ----\ntidy(penguins_anova) %>% \n  # changing very small p-values to < 0.001\n  mutate(p.value = case_when(\n    p.value < 0.001 ~ \"< 0.001\"\n  )) %>%\n  # rounding values in numerical columns to 1 decimal point\n  mutate(across(sumsq:statistic, ~ round(.x, digits = 1))) %>% \n  # changing the row names to be nicer (capitalizing Species)\n  mutate(term = case_match(\n    term, \n    \"species\" ~ \"Species\",\n    .default = term\n  )) %>% \n  \n  # turning the data frame into a flextable ----\n  flextable() %>% \n  # changing the column names to be nicer\n  set_header_labels(term = \"Source of variation\",\n                    df = \"Degrees of freedom\",\n                    sumsq = \"Sum of squares\",\n                    meansq = \"Mean squares\",\n                    statistic = \"F-statistic\",\n                    p.value = \"p-value\") %>% \n  # making small p-values bold\n  bold(~ p.value == \"< 0.001\", 6) %>% \n  # fitting the table to the viewer\n  autofit()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-a417f042{}.cl-a414e956{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-a414e960{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-a4160430{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a416043a{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a4160ba6{width:1.559in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160ba7{width:1.635in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160ba8{width:1.355in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160ba9{width:1.253in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160bb0{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160bb1{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160bb2{width:1.559in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160bba{width:1.635in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160bbb{width:1.355in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160bbc{width:1.253in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160bc4{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160bc5{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160bc6{width:1.559in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160bc7{width:1.635in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160bce{width:1.355in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160bcf{width:1.253in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160bd0{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4160bd8{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-a417f042'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-a4160ba6\"><p class=\"cl-a4160430\"><span class=\"cl-a414e956\">Source of variation</span></p></th><th class=\"cl-a4160ba7\"><p class=\"cl-a416043a\"><span class=\"cl-a414e956\">Degrees of freedom</span></p></th><th class=\"cl-a4160ba8\"><p class=\"cl-a416043a\"><span class=\"cl-a414e956\">Sum of squares</span></p></th><th class=\"cl-a4160ba9\"><p class=\"cl-a416043a\"><span class=\"cl-a414e956\">Mean squares</span></p></th><th class=\"cl-a4160bb0\"><p class=\"cl-a416043a\"><span class=\"cl-a414e956\">F-statistic</span></p></th><th class=\"cl-a4160bb1\"><p class=\"cl-a4160430\"><span class=\"cl-a414e956\">p-value</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a4160bb2\"><p class=\"cl-a4160430\"><span class=\"cl-a414e956\">Species</span></p></td><td class=\"cl-a4160bba\"><p class=\"cl-a416043a\"><span class=\"cl-a414e956\">2</span></p></td><td class=\"cl-a4160bbb\"><p class=\"cl-a416043a\"><span class=\"cl-a414e956\">7,194.3</span></p></td><td class=\"cl-a4160bbc\"><p class=\"cl-a416043a\"><span class=\"cl-a414e956\">3,597.2</span></p></td><td class=\"cl-a4160bc4\"><p class=\"cl-a416043a\"><span class=\"cl-a414e956\">410.6</span></p></td><td class=\"cl-a4160bc5\"><p class=\"cl-a4160430\"><span class=\"cl-a414e960\">&lt; 0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a4160bc6\"><p class=\"cl-a4160430\"><span class=\"cl-a414e956\">Residuals</span></p></td><td class=\"cl-a4160bc7\"><p class=\"cl-a416043a\"><span class=\"cl-a414e956\">339</span></p></td><td class=\"cl-a4160bce\"><p class=\"cl-a416043a\"><span class=\"cl-a414e956\">2,969.9</span></p></td><td class=\"cl-a4160bcf\"><p class=\"cl-a416043a\"><span class=\"cl-a414e956\">8.8</span></p></td><td class=\"cl-a4160bd0\"><p class=\"cl-a416043a\"><span class=\"cl-a414e956\"></span></p></td><td class=\"cl-a4160bd8\"><p class=\"cl-a4160430\"><span class=\"cl-a414e956\"></span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nTukey HSD results:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_HSD\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = bill_length_mm ~ species, data = penguins)\n\n$species\n                      diff       lwr        upr     p adj\nChinstrap-Adelie 10.042433  9.024859 11.0600064 0.0000000\nGentoo-Adelie     8.713487  7.867194  9.5597807 0.0000000\nGentoo-Chinstrap -1.328945 -2.381868 -0.2760231 0.0088993\n```\n:::\n:::\n\n\n**Example text (if you decided not to make a table:**\n\n[If you decide not to go with a table, the F-statistic, degrees of freedom, and p-value should be in parentheses. This is the only difference between this example and the one below.]{.aside}\nWe found a significant difference in bill length across species (analysis of variance, F(2, 339) = 410.6, _p_ < 0.001). Adelie penguins tend to have the shortest bills: on average, Gentoo penguins have 8.7 mm (Tukey HSD 95% confidence interval: [7.9, 9.6] mm) longer bills than Adelie penguins, and Chinstrap penguins have 10.0 mm ([9.0, 11.1] mm) longer bills than Adelie penguins.\n\n**Example text (with a table):**  \n\nWe found a significant difference in bill length across species (Table 2). Adelie penguins tend to have the shortest bills: on average, Gentoo penguins have 8.7 mm (Tukey HSD 95% confidence interval: [7.9, 9.6] mm) longer bills than Adelie penguins, and Chinstrap penguins have 10.0 mm ([9.0, 11.1] mm) longer bills than Adelie penguins.\n\n# Relationships between variables\n\n## Linear models\n\nThis first example was from lecture. We only talked about the equation and significant predictors, but I'll break it down further here.  \n\nGenerating data:  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(666)\n# sample size\nn <- 64\nplant_df <- tibble(\n  # predictor variables\n  temperature = round(rnorm(n = n, mean = 28, sd = 1), digits = 1),\n  light = round(rnorm(n = n, mean = 1, sd = 0.2), digits = 1),\n  ph = rnorm(n = n, mean = 7, sd = 0.01),\n  \n  # response: growth in cm/week\n  growth = light*rnorm(n = n, mean = 0.3, sd = 0.1) + temperature/round(rnorm(n = n, mean = 5, sd = 0.1))\n) \n```\n:::\n\n\n### Building a model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplant_model <- lm(growth ~ light + temperature + ph, data = plant_df)\n```\n:::\n\n\nDiagnostics:  \n\n[I changed the chunk options for this to make sure it displayed correctly - see the code chunk! I also chose which plots to plot using the `which()` function, and added a title to each using `title()`. The syntax is a little different from a standard `ggplot()` figure because these are all done in base R, but labelling plots is an option.]{.aside}\n\n::: {.cell layout-align=\"center\"}\n\n````{.cell-code}\n```{{r plant-diagnostics}}\n#| fig-width: 10\n#| fig-height: 10\n#| out.width: 90%\n#| fig.align: center\n\npar(mfrow = c(2, 2))\nplot(plant_model, which = c(1))\ntitle(\"A)\", adj = 0)\nplot(plant_model, which = c(2))\ntitle(\"B)\", adj = 0)\nplot(plant_model, which = c(3))\ntitle(\"C)\", adj = 0)\nplot(plant_model, which = c(5))\ntitle(\"D)\", adj = 0)\n```\n````\n\n::: {.cell-output-display}\n![](communicating-results_files/figure-html/plant-diagnostics-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n**Example caption:**  \n\n::: {style=\"font-size: 90%; color: #787878;\"}\n\n**Figure 3. Model diagnostic plots.** In all plots, points represent residuals. Red lines (residuals vs fitted, scale-location, and residuals vs leverage) are lines depicting patterns in residuals. Grey dashed lines represent reference lines.\n\n:::\n\n**Example text:**  \n\nWe tested the predictive relationship between plant growth and light, temperature, and soil pH using a linear model. Our null hypothesis was that none of these variables would predict plant growth. We used diagnostic plots to visually assess residual normality (Figure 3B) and homoskedasticity (Figures 3A and 3C). Additionally, we determined there were no outliers influencing our model predictions using Cook's distance (Figure 3D).\n\n### Model predictions\n\nJust to see what the original summary object is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(plant_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = growth ~ light + temperature + ph, data = plant_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.23209 -0.06571  0.01010  0.06173  0.19950 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -6.67140    6.80194  -0.981    0.331    \nlight        0.35196    0.05939   5.926 1.63e-07 ***\ntemperature  0.19626    0.01058  18.558  < 2e-16 ***\nph           0.96241    0.96806   0.994    0.324    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0911 on 60 degrees of freedom\nMultiple R-squared:  0.8759,\tAdjusted R-squared:  0.8696 \nF-statistic: 141.1 on 3 and 60 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nTable option 1:  \n\n:::{style=\"font-size: 90%; color: #787878;\"}\n**Table 3. Model prediction table.** Bolded p-value indicates significant difference from 0.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplant_model %>%\n  # turning the model object into a flextable ----\n  as_flextable() %>% \n  \n  # changing the row labels using `compose()` ----\n  # i selects the row, j selects the column\n  compose(i = 2, j = 1, \n          # value is whatever you want to change the text to\n          value = as_paragraph(\n            # `as_sup()` makes something a superscript - good for units etc.\n            \"Light (watts/m\", as_sup(\"2\"), \")\"\n          )) %>% \n  compose(i = 3, j = 1, \n          value = as_paragraph(\n            \"Temperature (°C)\"\n          )) %>% \n  compose(i = 4, j = 1, \n          value = as_paragraph(\n            \"pH\"\n          )) %>% \n  \n  # formatting the numbers to display to 3 decimal points ----\n  set_formatter(estimate = function(x) sprintf(\"%.03f\", x),\n                std.error = function(x) sprintf(\"%.03f\", x),\n                statistic = function(x) sprintf(\"%.03f\", x),\n                p.value = function(x) sprintf(\"%.03f\", x)) %>% \n  \n  # changing the p.value to display as < 0.001 when very small ----\n  compose(j = \"p.value\", i = ~ p.value < 0.001,\n          value = as_paragraph(\n            \"< 0.001\"\n          )) %>% \n  \n  # adding model equation at the top ----\n  # inserting new header row (to make space for equation)\n  add_header_lines(\"\", top = TRUE) %>% \n  # putting in equation\n  compose(\n    # choosing row 1, column 1, indicating that is a header\n    j = 1, i = 1, part = \"header\",\n    # putting in the equation using as_equation and extract_eq from {equatiomatic}\n    value = as_paragraph(\n      as_equation(extract_eq(plant_model), \n                  # formatting equation\n                  width = 2, height = .5)\n    )) %>% \n  # making sure the equation is centered on the table\n  align(i = 1, part = \"header\", align = \"center\") %>% \n  \n  # formatting header labels ----\n  set_header_labels(statistic = \"t-statistic\",\n                    p.value = \"p-value\") %>% \n  \n  # making cells bold when p.value < 0.05 ----\n  bold(i = ~ p.value < .05, j = \"p.value\") %>% \n  \n  # making table fit viewer ----\n  autofit()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-a4550126{}.cl-a450ad1a{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-a450ad1b{font-family:'Helvetica';font-size:6.6pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;bottom:3.3pt;}.cl-a450ad24{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-a450ad25{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-a4534a7a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a4534a7b{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a4534a84{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a453525e{width:1.475in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a453525f{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4535260{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4535268{width:0.888in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4535269{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a453526a{width:0.464in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a453526b{width:1.475in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4535272{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4535290{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a453529a{width:0.888in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a453529b{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a453529c{width:0.464in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a453529d{width:1.475in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a453529e{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352a4{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352a5{width:0.888in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352a6{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352a7{width:0.464in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352ae{width:1.475in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352af{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352b0{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352b1{width:0.888in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352b8{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352b9{width:0.464in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352ba{width:1.475in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352bb{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352c2{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352c3{width:0.888in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352c4{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352c5{width:0.464in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352cc{width:1.475in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352cd{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352ce{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352d6{width:0.888in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352d7{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352d8{width:0.464in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352d9{width:1.475in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352e0{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352e1{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352ea{width:0.888in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352eb{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352ec{width:0.464in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352ed{width:1.475in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352f4{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352f5{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352f6{width:0.888in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352f7{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a45352fe{width:0.464in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-a4550126'><thead><tr style=\"overflow-wrap:break-word;\"><th  colspan=\"6\"class=\"cl-a453525e\"><p class=\"cl-a4534a7a\"><link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.css\" data-external=\"1\"><span class=\"cl-a450ad1a\"><link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/npm/katex@0.16.3/dist/katex.min.css\" data-external=\"1\">\n<span class=\"katex-display\"><span class=\"katex\"><span class=\"katex-mathml\"><math xmlns=\"http://www.w3.org/1998/Math/MathML\" display=\"block\"><semantics><mrow><mi mathvariant=\"normal\">growth</mi><mo>⁡</mo><mo>=</mo><mi>α</mi><mo>+</mo><msub><mi>β</mi><mn>1</mn></msub><mo stretchy=\"false\">(</mo><mi mathvariant=\"normal\">light</mi><mo>⁡</mo><mo stretchy=\"false\">)</mo><mo>+</mo><msub><mi>β</mi><mn>2</mn></msub><mo stretchy=\"false\">(</mo><mi mathvariant=\"normal\">temperature</mi><mo>⁡</mo><mo stretchy=\"false\">)</mo><mo>+</mo><msub><mi>β</mi><mn>3</mn></msub><mo stretchy=\"false\">(</mo><mi mathvariant=\"normal\">ph</mi><mo>⁡</mo><mo stretchy=\"false\">)</mo><mo>+</mo><mi>ϵ</mi></mrow><annotation encoding=\"application/x-tex\">\\operatorname{growth} = \\alpha + \\beta_{1}(\\operatorname{light}) + \\beta_{2}(\\operatorname{temperature}) + \\beta_{3}(\\operatorname{ph}) + \\epsilon</annotation></semantics></math></span><span class=\"katex-html\" aria-hidden=\"true\"><span class=\"base\"><span class=\"strut\" style=\"height:0.8889em;vertical-align:-0.1944em;\"></span><span class=\"mop\"><span class=\"mord mathrm\">growth</span></span><span class=\"mspace\" style=\"margin-right:0.2778em;\"></span><span class=\"mrel\">=</span><span class=\"mspace\" style=\"margin-right:0.2778em;\"></span></span><span class=\"base\"><span class=\"strut\" style=\"height:0.6667em;vertical-align:-0.0833em;\"></span><span class=\"mord mathnormal\" style=\"margin-right:0.0037em;\">α</span><span class=\"mspace\" style=\"margin-right:0.2222em;\"></span><span class=\"mbin\">+</span><span class=\"mspace\" style=\"margin-right:0.2222em;\"></span></span><span class=\"base\"><span class=\"strut\" style=\"height:1em;vertical-align:-0.25em;\"></span><span class=\"mord\"><span class=\"mord mathnormal\" style=\"margin-right:0.05278em;\">β</span><span class=\"msupsub\"><span class=\"vlist-t vlist-t2\"><span class=\"vlist-r\"><span class=\"vlist\" style=\"height:0.3011em;\"><span style=\"top:-2.55em;margin-left:-0.0528em;margin-right:0.05em;\"><span class=\"pstrut\" style=\"height:2.7em;\"></span><span class=\"sizing reset-size6 size3 mtight\"><span class=\"mord mtight\"><span class=\"mord mtight\">1</span></span></span></span></span><span class=\"vlist-s\">​</span></span><span class=\"vlist-r\"><span class=\"vlist\" style=\"height:0.15em;\"><span></span></span></span></span></span></span><span class=\"mopen\">(</span><span class=\"mop\"><span class=\"mord mathrm\">light</span></span><span class=\"mclose\">)</span><span class=\"mspace\" style=\"margin-right:0.2222em;\"></span><span class=\"mbin\">+</span><span class=\"mspace\" style=\"margin-right:0.2222em;\"></span></span><span class=\"base\"><span class=\"strut\" style=\"height:1em;vertical-align:-0.25em;\"></span><span class=\"mord\"><span class=\"mord mathnormal\" style=\"margin-right:0.05278em;\">β</span><span class=\"msupsub\"><span class=\"vlist-t vlist-t2\"><span class=\"vlist-r\"><span class=\"vlist\" style=\"height:0.3011em;\"><span style=\"top:-2.55em;margin-left:-0.0528em;margin-right:0.05em;\"><span class=\"pstrut\" style=\"height:2.7em;\"></span><span class=\"sizing reset-size6 size3 mtight\"><span class=\"mord mtight\"><span class=\"mord mtight\">2</span></span></span></span></span><span class=\"vlist-s\">​</span></span><span class=\"vlist-r\"><span class=\"vlist\" style=\"height:0.15em;\"><span></span></span></span></span></span></span><span class=\"mopen\">(</span><span class=\"mop\"><span class=\"mord mathrm\">temperature</span></span><span class=\"mclose\">)</span><span class=\"mspace\" style=\"margin-right:0.2222em;\"></span><span class=\"mbin\">+</span><span class=\"mspace\" style=\"margin-right:0.2222em;\"></span></span><span class=\"base\"><span class=\"strut\" style=\"height:1em;vertical-align:-0.25em;\"></span><span class=\"mord\"><span class=\"mord mathnormal\" style=\"margin-right:0.05278em;\">β</span><span class=\"msupsub\"><span class=\"vlist-t vlist-t2\"><span class=\"vlist-r\"><span class=\"vlist\" style=\"height:0.3011em;\"><span style=\"top:-2.55em;margin-left:-0.0528em;margin-right:0.05em;\"><span class=\"pstrut\" style=\"height:2.7em;\"></span><span class=\"sizing reset-size6 size3 mtight\"><span class=\"mord mtight\"><span class=\"mord mtight\">3</span></span></span></span></span><span class=\"vlist-s\">​</span></span><span class=\"vlist-r\"><span class=\"vlist\" style=\"height:0.15em;\"><span></span></span></span></span></span></span><span class=\"mopen\">(</span><span class=\"mop\"><span class=\"mord mathrm\">ph</span></span><span class=\"mclose\">)</span><span class=\"mspace\" style=\"margin-right:0.2222em;\"></span><span class=\"mbin\">+</span><span class=\"mspace\" style=\"margin-right:0.2222em;\"></span></span><span class=\"base\"><span class=\"strut\" style=\"height:0.4306em;\"></span><span class=\"mord mathnormal\">ϵ</span></span></span></span></span></span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-a453526b\"><p class=\"cl-a4534a7b\"><span class=\"cl-a450ad1a\"></span></p></th><th class=\"cl-a4535272\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">Estimate</span></p></th><th class=\"cl-a4535290\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">Standard Error</span></p></th><th class=\"cl-a453529a\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">t-statistic</span></p></th><th class=\"cl-a453529b\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">p-value</span></p></th><th class=\"cl-a453529c\"><p class=\"cl-a4534a7b\"><span class=\"cl-a450ad1a\"></span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a453529d\"><p class=\"cl-a4534a7b\"><span class=\"cl-a450ad1a\">(Intercept)</span></p></td><td class=\"cl-a453529e\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">-6.671</span></p></td><td class=\"cl-a45352a4\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">6.802</span></p></td><td class=\"cl-a45352a5\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">-0.981</span></p></td><td class=\"cl-a45352a6\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">0.331</span></p></td><td class=\"cl-a45352a7\"><p class=\"cl-a4534a7b\"><span class=\"cl-a450ad1a\">   </span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a45352ae\"><p class=\"cl-a4534a7b\"><span class=\"cl-a450ad1a\">Light (watts/m</span><span class=\"cl-a450ad1b\">2</span><span class=\"cl-a450ad1a\">)</span></p></td><td class=\"cl-a45352af\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">0.352</span></p></td><td class=\"cl-a45352b0\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">0.059</span></p></td><td class=\"cl-a45352b1\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">5.926</span></p></td><td class=\"cl-a45352b8\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad24\">&lt; 0.001</span></p></td><td class=\"cl-a45352b9\"><p class=\"cl-a4534a7b\"><span class=\"cl-a450ad1a\">***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a45352ba\"><p class=\"cl-a4534a7b\"><span class=\"cl-a450ad1a\">Temperature (°C)</span></p></td><td class=\"cl-a45352bb\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">0.196</span></p></td><td class=\"cl-a45352c2\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">0.011</span></p></td><td class=\"cl-a45352c3\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">18.558</span></p></td><td class=\"cl-a45352c4\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad24\">&lt; 0.001</span></p></td><td class=\"cl-a45352c5\"><p class=\"cl-a4534a7b\"><span class=\"cl-a450ad1a\">***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a45352cc\"><p class=\"cl-a4534a7b\"><span class=\"cl-a450ad1a\">pH</span></p></td><td class=\"cl-a45352cd\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">0.962</span></p></td><td class=\"cl-a45352ce\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">0.968</span></p></td><td class=\"cl-a45352d6\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">0.994</span></p></td><td class=\"cl-a45352d7\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad1a\">0.324</span></p></td><td class=\"cl-a45352d8\"><p class=\"cl-a4534a7b\"><span class=\"cl-a450ad1a\">   </span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"6\"class=\"cl-a45352d9\"><p class=\"cl-a4534a84\"><span class=\"cl-a450ad25\">Signif. codes: 0 &lt;= '***' &lt; 0.001 &lt; '**' &lt; 0.01 &lt; '*' &lt; 0.05</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"6\"class=\"cl-a45352ed\"><p class=\"cl-a4534a7b\"><span class=\"cl-a450ad1a\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"6\"class=\"cl-a45352ed\"><p class=\"cl-a4534a7b\"><span class=\"cl-a450ad1a\">Residual standard error: 0.0911 on 60 degrees of freedom</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"6\"class=\"cl-a45352ed\"><p class=\"cl-a4534a7b\"><span class=\"cl-a450ad1a\">Multiple R-squared: 0.8759, Adjusted R-squared: 0.8696</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"6\"class=\"cl-a45352ed\"><p class=\"cl-a4534a7b\"><span class=\"cl-a450ad1a\">F-statistic: 141.1 on 60 and 3 DF, p-value: 0.0000</span></p></td></tr></tfoot></table></div>\n```\n:::\n:::\n\n\n:::{.callout-note collapse=\"true\"}\n### Including tables and full tables with `{flextable}`\nWhen writing about models, you have to make decisions about whether or not you want to include a table of the model summary. In multiple linear regression (and for more complex models), it's a good idea to include a table of the model summary.  \n\nIf you wanted to make a table of the model estimates _and_ the relevant information at the bottom of that summary (for example, $R^2$, F-statistic, degrees of freedom, etc.), you could use `flextable::as_flextable()` which takes the model object - this is Table 3. This skips the step of creating an intermediate data frame and just turns everything into a flextable object. However, this can be a bit tricky: the formatting to make it look \"good\" takes some getting used to. You can go either way, but this is one option if you'd rather condense the information from the model prediction table and ANOVA table into one. It is also somewhat easier to interpret than the model prediction + ANOVA table combo (Tables 4 + 5).\n:::\n\nTable option 2:\n\n**Table 4. Model prediction table.** Bolded p-value indicates significance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplant_model %>% \n  tidy() %>% \n  mutate(across(estimate:p.value, ~round(.x, digits = 3))) %>% \n  mutate(p.value = case_when(\n    p.value < 0.001 ~ \"< 0.001\",\n    TRUE ~ as.character(p.value)\n  )) %>% \n  flextable() %>% \n  # changing the row labels using `compose()`\n  compose(i = 2, j = 1, \n          value = as_paragraph(\n            \"Light (watts/m\", as_sup(\"2\"), \")\"\n          )) %>% \n  compose(i = 3, j = 1, \n          value = as_paragraph(\n            \"Temperature (°C)\"\n          )) %>% \n  compose(i = 4, j = 1, \n          value = as_paragraph(\n            \"pH\"\n          )) %>% \n  # formatting header labels\n  set_header_labels(term = \"Term\",\n                    estimate = \"Estimate\",\n                    std.error = \"Standard error\",\n                    statistic = \"t-statistic\",\n                    p.value = \"p-value\") %>% \n  bold(j = 5, i = ~p.value == \"< 0.001\") %>% \n  autofit()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-a4640df6{}.cl-a4612ae6{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-a4612ae7{font-family:'Helvetica';font-size:6.6pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;bottom:3.3pt;}.cl-a4612af0{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-a4627720{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a4627721{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a4627edc{width:1.475in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627ee6{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627ee7{width:1.27in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627ee8{width:0.888in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627ee9{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627ef0{width:1.475in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627ef1{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627efa{width:1.27in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627efb{width:0.888in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627efc{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f04{width:1.475in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f05{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f06{width:1.27in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f07{width:0.888in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f08{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f0e{width:1.475in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f0f{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f10{width:1.27in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f18{width:0.888in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f19{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f1a{width:1.475in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f22{width:0.88in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f23{width:1.27in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f24{width:0.888in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4627f2c{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-a4640df6'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-a4627edc\"><p class=\"cl-a4627720\"><span class=\"cl-a4612ae6\">Term</span></p></th><th class=\"cl-a4627ee6\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">Estimate</span></p></th><th class=\"cl-a4627ee7\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">Standard error</span></p></th><th class=\"cl-a4627ee8\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">t-statistic</span></p></th><th class=\"cl-a4627ee9\"><p class=\"cl-a4627720\"><span class=\"cl-a4612ae6\">p-value</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a4627ef0\"><p class=\"cl-a4627720\"><span class=\"cl-a4612ae6\">(Intercept)</span></p></td><td class=\"cl-a4627ef1\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">-6.671</span></p></td><td class=\"cl-a4627efa\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">6.802</span></p></td><td class=\"cl-a4627efb\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">-0.981</span></p></td><td class=\"cl-a4627efc\"><p class=\"cl-a4627720\"><span class=\"cl-a4612ae6\">0.331</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a4627f04\"><p class=\"cl-a4627720\"><span class=\"cl-a4612ae6\">Light (watts/m</span><span class=\"cl-a4612ae7\">2</span><span class=\"cl-a4612ae6\">)</span></p></td><td class=\"cl-a4627f05\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">0.352</span></p></td><td class=\"cl-a4627f06\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">0.059</span></p></td><td class=\"cl-a4627f07\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">5.926</span></p></td><td class=\"cl-a4627f08\"><p class=\"cl-a4627720\"><span class=\"cl-a4612af0\">&lt; 0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a4627f0e\"><p class=\"cl-a4627720\"><span class=\"cl-a4612ae6\">Temperature (°C)</span></p></td><td class=\"cl-a4627f0f\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">0.196</span></p></td><td class=\"cl-a4627f10\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">0.011</span></p></td><td class=\"cl-a4627f18\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">18.558</span></p></td><td class=\"cl-a4627f19\"><p class=\"cl-a4627720\"><span class=\"cl-a4612af0\">&lt; 0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a4627f1a\"><p class=\"cl-a4627720\"><span class=\"cl-a4612ae6\">pH</span></p></td><td class=\"cl-a4627f22\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">0.962</span></p></td><td class=\"cl-a4627f23\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">0.968</span></p></td><td class=\"cl-a4627f24\"><p class=\"cl-a4627721\"><span class=\"cl-a4612ae6\">0.994</span></p></td><td class=\"cl-a4627f2c\"><p class=\"cl-a4627720\"><span class=\"cl-a4612ae6\">0.324</span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nANOVA table: \n\n**Table 5. Model ANOVA table.** Bolded p-value indicates significant difference from 0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAnova(plant_model) %>% \n  tidy() %>% \n  mutate(across(sumsq:p.value, ~round(.x, digits = 3))) %>% \n  mutate(p.value = case_when(\n    p.value < 0.001 ~ \"< 0.001\",\n    TRUE ~ as.character(p.value)\n  )) %>% \n  flextable() %>% \n  # changing the row labels using `compose()`\n  compose(i = 1, j = 1, \n          value = as_paragraph(\n            \"Light (watts/m\", as_sup(\"2\"), \")\"\n          )) %>% \n  compose(i = 2, j = 1, \n          value = as_paragraph(\n            \"Temperature (°C)\"\n          )) %>% \n  compose(i = 3, j = 1, \n          value = as_paragraph(\n            \"pH\"\n          )) %>% \n  # formatting header labels\n  set_header_labels(term = \"Source of variation\",\n                    sumsq = \"Sum of squares\",\n                    df = \"Degrees of freedom\",\n                    statistic = \"F-statistic\",\n                    p.value = \"p-value\") %>% \n  bold(j = 5, i = ~p.value == \"< 0.001\") %>% \n  autofit()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-a47b2fe0{}.cl-a477e434{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-a477e43e{font-family:'Helvetica';font-size:6.6pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;bottom:3.3pt;}.cl-a477e43f{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-a4791746{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a4791747{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a4791fd4{width:1.559in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4791fde{width:1.355in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4791fdf{width:1.635in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4791fe0{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4791fe8{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4791fe9{width:1.559in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4791fea{width:1.355in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4791ff2{width:1.635in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4791ff3{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4791ff4{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4791ffc{width:1.559in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4791ffd{width:1.355in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4791ffe{width:1.635in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4791fff{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4792006{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4792007{width:1.559in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4792008{width:1.355in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4792010{width:1.635in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4792011{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4792012{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a4792013{width:1.559in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a479201a{width:1.355in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a479201b{width:1.635in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a479201c{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a479201d{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-a47b2fe0'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-a4791fd4\"><p class=\"cl-a4791746\"><span class=\"cl-a477e434\">Source of variation</span></p></th><th class=\"cl-a4791fde\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\">Sum of squares</span></p></th><th class=\"cl-a4791fdf\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\">Degrees of freedom</span></p></th><th class=\"cl-a4791fe0\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\">F-statistic</span></p></th><th class=\"cl-a4791fe8\"><p class=\"cl-a4791746\"><span class=\"cl-a477e434\">p-value</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a4791fe9\"><p class=\"cl-a4791746\"><span class=\"cl-a477e434\">Light (watts/m</span><span class=\"cl-a477e43e\">2</span><span class=\"cl-a477e434\">)</span></p></td><td class=\"cl-a4791fea\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\">0.291</span></p></td><td class=\"cl-a4791ff2\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\">1</span></p></td><td class=\"cl-a4791ff3\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\">35.122</span></p></td><td class=\"cl-a4791ff4\"><p class=\"cl-a4791746\"><span class=\"cl-a477e43f\">&lt; 0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a4791ffc\"><p class=\"cl-a4791746\"><span class=\"cl-a477e434\">Temperature (°C)</span></p></td><td class=\"cl-a4791ffd\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\">2.858</span></p></td><td class=\"cl-a4791ffe\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\">1</span></p></td><td class=\"cl-a4791fff\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\">344.412</span></p></td><td class=\"cl-a4792006\"><p class=\"cl-a4791746\"><span class=\"cl-a477e43f\">&lt; 0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a4792007\"><p class=\"cl-a4791746\"><span class=\"cl-a477e434\">pH</span></p></td><td class=\"cl-a4792008\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\">0.008</span></p></td><td class=\"cl-a4792010\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\">1</span></p></td><td class=\"cl-a4792011\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\">0.988</span></p></td><td class=\"cl-a4792012\"><p class=\"cl-a4791746\"><span class=\"cl-a477e434\">0.324</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-a4792013\"><p class=\"cl-a4791746\"><span class=\"cl-a477e434\">Residuals</span></p></td><td class=\"cl-a479201a\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\">0.498</span></p></td><td class=\"cl-a479201b\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\">60</span></p></td><td class=\"cl-a479201c\"><p class=\"cl-a4791747\"><span class=\"cl-a477e434\"></span></p></td><td class=\"cl-a479201d\"><p class=\"cl-a4791746\"><span class=\"cl-a477e434\"></span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n### Visualization\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntemp_pred <- ggpredict(plant_model, terms = \"temperature\")\n\nlight_pred <- ggpredict(plant_model, terms = \"light\")\n\ntemp_plot <- ggplot(data = plant_df, aes(x = temperature, y = growth)) +\n  geom_point() +\n  geom_ribbon(data = temp_pred, aes(x = x, y = predicted, ymin = conf.low, ymax = conf.high), alpha = 0.2) +\n  geom_line(data = temp_pred, aes(x = x, y = predicted), color = \"blue\", linewidth = 1) +\n  theme_classic() +\n  labs(x = \"Temperature (°C)\", y = \"Growth (cm/week)\",\n       title = \"A)\") +\n  theme(plot.title.position = \"plot\",\n        text = element_text(size = 15))\n\nlight_plot <- ggplot(data = plant_df, aes(x = light, y = growth)) +\n  geom_point() +\n  geom_ribbon(data = light_pred, aes(x = x, y = predicted, ymin = conf.low, ymax = conf.high), alpha = 0.2) +\n  geom_line(data = light_pred, aes(x = x, y = predicted), color = \"darkorange\", linewidth = 1) +\n  theme_classic() +\n  labs(x = expression(paste(\"Light (watts/\"~m^2~\")\")), y = \"Growth (cm/week)\",\n       title = \"B)\") +\n  theme(plot.title.position = \"plot\",\n        text = element_text(size = 15))\n\ntemp_plot + light_plot\n```\n\n::: {.cell-output-display}\n![](communicating-results_files/figure-html/two-panel-predictions-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n**Example caption:**  \n\n::: {style=\"font-size: 90%; color: #787878;\"}\n**Figure 4. Predicted growth as a function of A) temperature and B) light.** In both panels, points represent observations, colored lines represent model predictions, and shaded areas represent 95% confidence intervals. In A), growth is predicted as a function of temperature for a constant light level of 0.98 watts/m<sup>2</sup> and pH 7. In B), growth is predicted as a function of light for a constant temperature of 27.9 °C and pH 7. \n:::\n\n:::{.callout-note collapse=\"true\"}\n### Understanding predictions\nRemember that for multiple linear regression, the slopes represent change in the response variable for each 1 unit change in the predictor for all else held constant. When getting model estimates for slopes, the \"constant\" values are the mean of the variable. When using `ggeffects::ggpredict()`, these values are printed below the prediction table (you can double check this by calculating the mean yourself!).\n:::\n\n### Test results\n\n**Example text:**  \n\nWe found that light and temperature significantly predicted plant growth, but not pH (Table 3). The overall model accounted for 87% of the variance in plant growth. For each 1 °C increase in temperature at constant light and pH, we expect 0.20 $\\pm$ 0.01 increase in plant growth (Figure 4A). For each 1 watt/m<sup>2</sup> increase in light at constant temperature and pH, we expect a 0.35 $\\pm$ 0.06 increase in plant growth (Figure 4B). \n\n:::{.callout-note collapse=\"true\"}\n### Choosing which parameters to highlight\nWith multiple linear regression and generalized linear models, you're usually working with pretty complex model structure. It'd be impossible (and not that interesting, necessarily) to discuss _all_ the predictors. You can choose which one(s) you want to highlight in your visualizations and text based on what _you_ think is most interesting/biologically relevant.\n:::\n",
    "supporting": [
      "communicating-results_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}